// <auto-generated />
using HumanCapitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanCapitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250717160526_TryToFixAgain")]
    partial class TryToFixAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanCapitalManagement.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5ad53192-de89-4d3b-ba04-64f1e16fea85",
                            ConcurrencyStamp = "6d7cd8aa-07e6-4cfe-9e93-000c4759d59f",
                            Email = "johndoe1@personal.gmail",
                            NormalizedEmail = "JOHNDOE1@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEItexUkIi9vfLoCUyiiEh7jthLJ5Xp7WL8TJTwWJjBpuuPrslQgOQjX/xMBgDTQF/Q==",
                            SecurityStamp = "6b79914a-2c32-4e33-b800-256f6b733652",
                            UserName = "JohnDoe1"
                        },
                        new
                        {
                            Id = "144130da-c375-4cdd-9d24-96944786d0cf",
                            ConcurrencyStamp = "2647e320-c389-471a-8a96-2ca5a7cc7015",
                            Email = "johndoe2@personal.gmail",
                            NormalizedEmail = "JOHNDOE2@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE2",
                            PasswordHash = "AQAAAAIAAYagAAAAENKxk3fE2b35wacbosAu464Adiw/2S+JmA6fFLmxgqjP4gMUFvY7xipSeJi4lpSwqg==",
                            SecurityStamp = "6ceb1050-a8ec-4343-b18e-6ab9c84bbdbd",
                            UserName = "JohnDoe2"
                        },
                        new
                        {
                            Id = "f9c57357-af13-46ce-8fce-fd2565902431",
                            ConcurrencyStamp = "e68a62e2-c6f3-4bf5-8d0b-ef4629cbcfa7",
                            Email = "johndoe3@personal.gmail",
                            NormalizedEmail = "JOHNDOE3@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE3",
                            PasswordHash = "AQAAAAIAAYagAAAAEAWNehR0NpJWQq7960eaiBlFTiUVekccYCJQovbGcJBOPI9l+hBuCaJWbA3JB8BjaA==",
                            SecurityStamp = "60e4895c-b3a0-4f84-a2f3-85aefe5920e0",
                            UserName = "JohnDoe3"
                        },
                        new
                        {
                            Id = "6408f506-777d-49a2-95d8-caca851659bb",
                            ConcurrencyStamp = "ccc2a10f-7f79-4896-877c-1129a8af04b9",
                            Email = "johndoe4@personal.gmail",
                            NormalizedEmail = "JOHNDOE4@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEFxq2IMyfchHzFj2mXMlu0+oTRNpuHBoGf33XGCfo6tCIa3Z9Afbq1yEhNmGldw1HA==",
                            SecurityStamp = "6edb18d0-7e5b-4cb7-a3df-d30101fc4afb",
                            UserName = "JohnDoe4"
                        },
                        new
                        {
                            Id = "608675be-be73-467b-b7de-0c5cbcc02f66",
                            ConcurrencyStamp = "d58faf64-eb81-4335-ad5b-6807946ec2b7",
                            Email = "johndoe5@personal.gmail",
                            NormalizedEmail = "JOHNDOE5@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE5",
                            PasswordHash = "AQAAAAIAAYagAAAAEG8e8p3iXl3eZd0ZuNc7HqMwAr4YPuYQ7kEbIdGPnw7y/gCTIs6ItwHnMprPsDmwXA==",
                            SecurityStamp = "e07d18e9-a9b7-4b50-9cd0-a2b277bcf913",
                            UserName = "JohnDoe5"
                        },
                        new
                        {
                            Id = "da0be6f6-efa0-4623-98b7-f0b379022cca",
                            ConcurrencyStamp = "9f26d16d-d757-409c-bd03-226951beb90b",
                            Email = "johndoe6@personal.gmail",
                            NormalizedEmail = "JOHNDOE6@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE6",
                            PasswordHash = "AQAAAAIAAYagAAAAEAezp/K7RvXIjbazXFrbw51Gstx8vJW2OPNfcPOeoj3XYgeZ1SD21g/QomkZOb1h1g==",
                            SecurityStamp = "e9496b5b-a66a-4136-9b22-57bbbc216ce6",
                            UserName = "JohnDoe6"
                        },
                        new
                        {
                            Id = "0b605576-77bc-45f5-aabc-e4953d47f8ad",
                            ConcurrencyStamp = "1a947578-eefb-4d3b-a85d-1033d9e45107",
                            Email = "johndoe7@personal.gmail",
                            NormalizedEmail = "JOHNDOE7@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE7",
                            PasswordHash = "AQAAAAIAAYagAAAAEFyMOnFqp0O53GiYJfNNUNNz2cAUtDqLyAappJsgIvkUiqLAfmVB+uxqk1wL077ziw==",
                            SecurityStamp = "8b2946c0-0fa8-4321-8ef6-d388b922c9fd",
                            UserName = "JohnDoe7"
                        },
                        new
                        {
                            Id = "a0266ed4-1792-4fa7-ac84-96496b9de7b5",
                            ConcurrencyStamp = "2e14efe1-f744-4603-9a16-11635832e9fd",
                            Email = "johndoe8@personal.gmail",
                            NormalizedEmail = "JOHNDOE8@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE8",
                            PasswordHash = "AQAAAAIAAYagAAAAEPMir1uTCkeZkjOoH5LTWE1NN7mCg3Vg64hk73bsUKOOPq0BOuNbzb6DGIWGrGiIbQ==",
                            SecurityStamp = "484000ca-2f0e-4e58-b66e-810a38b8fd75",
                            UserName = "JohnDoe8"
                        },
                        new
                        {
                            Id = "4755c5cc-7a2f-4b65-92df-862049afa63a",
                            ConcurrencyStamp = "77258b0e-2f90-4890-8df3-08ed9b676455",
                            Email = "johndoe9@personal.gmail",
                            NormalizedEmail = "JOHNDOE9@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE9",
                            PasswordHash = "AQAAAAIAAYagAAAAEOBlTC+a6gnGqeFiq+kgs/39W9a1B+hGUmn755HAGhY9NEdTkStAKqxaIi3QvtL77g==",
                            SecurityStamp = "02aab94b-877c-4c8b-ab97-fc52f5eed1b6",
                            UserName = "JohnDoe9"
                        },
                        new
                        {
                            Id = "27d67d92-b6d9-4aa3-a08a-c27a898553af",
                            ConcurrencyStamp = "10539180-68b4-457b-84c5-207dd73568bc",
                            Email = "johndoe10@personal.gmail",
                            NormalizedEmail = "JOHNDOE10@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE10",
                            PasswordHash = "AQAAAAIAAYagAAAAEAKiIBk6SvrtxUoneMfNlBnGHeLa7gmOUL/6wcF+5gg0AzueJokuDBElJdSMctlhOQ==",
                            SecurityStamp = "4a52329f-99e5-4d48-8346-c545e701f2d9",
                            UserName = "JohnDoe10"
                        },
                        new
                        {
                            Id = "d63eb99e-8aa0-4c32-902a-253cc4cb8df3",
                            ConcurrencyStamp = "c95ac415-dcca-498e-88a4-96bbbe86d450",
                            Email = "johndoe11@personal.gmail",
                            NormalizedEmail = "JOHNDOE11@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE11",
                            PasswordHash = "AQAAAAIAAYagAAAAEHXJRt+OKloHq/yHnXt1w50aJQjLHUEX+cemvPqz90taDZgrat/xdnhWrDDHiILbwA==",
                            SecurityStamp = "39fcc566-c2de-4ab4-89e8-f2576f49dc9f",
                            UserName = "JohnDoe11"
                        },
                        new
                        {
                            Id = "1b1f7829-ca7b-41d6-aaa7-c4c8b236729b",
                            ConcurrencyStamp = "0212f789-b1ac-4ee7-a43e-d15abca4cd6f",
                            Email = "johndoe12@personal.gmail",
                            NormalizedEmail = "JOHNDOE12@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE12",
                            PasswordHash = "AQAAAAIAAYagAAAAEH2W3W83AmBOhfHmfXn1UfYZLZvqF50regTQNhNFTC2kBLOQtMcWBM2jsqA2mYruxA==",
                            SecurityStamp = "d90bb394-66d9-49cc-bb02-9caaa3203900",
                            UserName = "JohnDoe12"
                        },
                        new
                        {
                            Id = "3a335e8e-f962-4bf5-ac3d-dbcd381977f8",
                            ConcurrencyStamp = "4dde1270-e00b-45e8-859d-b6b1f4be3df8",
                            Email = "johndoe13@personal.gmail",
                            NormalizedEmail = "JOHNDOE13@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE13",
                            PasswordHash = "AQAAAAIAAYagAAAAEKGi1uhXlCjtQ3zdyupZfx8ATdLn0rR5rY0p0nDgeYoACrfD7J1/+MnOkao377z5Ig==",
                            SecurityStamp = "be663043-8071-46a0-a7c6-a54f64b4afd0",
                            UserName = "JohnDoe13"
                        },
                        new
                        {
                            Id = "f07d1174-a712-4118-bf7a-3f17663b5e44",
                            ConcurrencyStamp = "a3a011a3-03df-47b7-8a5e-2839a545d784",
                            Email = "johndoe14@personal.gmail",
                            NormalizedEmail = "JOHNDOE14@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE14",
                            PasswordHash = "AQAAAAIAAYagAAAAEB7BWtObU9PuLI4aINKpCCBP73I5jedjoeJrDid1HnZJO89ye5MYEtmi8zPAfCqYyA==",
                            SecurityStamp = "9844d14e-a149-4182-b162-a311b1453ded",
                            UserName = "JohnDoe14"
                        },
                        new
                        {
                            Id = "2611bcac-eeda-4978-a9ae-96bea754e763",
                            ConcurrencyStamp = "726f85aa-15b0-443e-9e77-2937d14d0943",
                            Email = "johndoe15@personal.gmail",
                            NormalizedEmail = "JOHNDOE15@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE15",
                            PasswordHash = "AQAAAAIAAYagAAAAEDoWQl+GtmmcUoIzYQ1Rd0O6VYrv3meqDHHm83H2PAtI+cEn/jlkc9MJ9ZVcZaYdww==",
                            SecurityStamp = "3f2349e7-4340-4f45-9a74-597f06c062c8",
                            UserName = "JohnDoe15"
                        },
                        new
                        {
                            Id = "deab66c4-afa6-49fb-87ff-8db028e02c6c",
                            ConcurrencyStamp = "bf1023e2-a6ca-4d6d-b8ea-5ef6ecfd75d7",
                            Email = "johndoe16@personal.gmail",
                            NormalizedEmail = "JOHNDOE16@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE16",
                            PasswordHash = "AQAAAAIAAYagAAAAEA41riUO6i9cAks+UYVLB4Q6uaWi3INZRvcZASNGvNdo/HCTyt2DeeSjWlhtLGpLbQ==",
                            SecurityStamp = "1aa65c6b-4209-440c-8bc3-29f43f23cc88",
                            UserName = "JohnDoe16"
                        },
                        new
                        {
                            Id = "bd875332-d78a-4e50-9c58-0c42921aa70a",
                            ConcurrencyStamp = "b0c61630-c53c-4565-9ce9-74e44409ab2a",
                            Email = "johndoe17@personal.gmail",
                            NormalizedEmail = "JOHNDOE17@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE17",
                            PasswordHash = "AQAAAAIAAYagAAAAENsdqbieK8mbweOIX5/4uaZteyYpA5EaHrZ7MgVtPlNfLBIpfyXjnZQPuI3Paa/UYw==",
                            SecurityStamp = "c3a7dc5e-8de4-4973-8995-9cf37b09d854",
                            UserName = "JohnDoe17"
                        },
                        new
                        {
                            Id = "7985e76b-c94e-4a6e-bbbd-abece7d3a407",
                            ConcurrencyStamp = "53fb9891-0dce-4cb7-bd78-5ef1d10abcf7",
                            Email = "johndoe18@personal.gmail",
                            NormalizedEmail = "JOHNDOE18@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE18",
                            PasswordHash = "AQAAAAIAAYagAAAAEJEnrH9owGHe+1xFojAJeoFJ15EzyiWIWiD2P+vQT5ZIZ/VeJb0j29tqcaTjCcP1Ag==",
                            SecurityStamp = "b389f6e6-48ef-43d2-9ec9-59e3b4eb7fdb",
                            UserName = "JohnDoe18"
                        },
                        new
                        {
                            Id = "8792960b-d7d3-49f9-891c-d6c9955b6d4d",
                            ConcurrencyStamp = "04a83efb-eaef-4efb-85aa-9b87695d4755",
                            Email = "johndoe19@personal.gmail",
                            NormalizedEmail = "JOHNDOE19@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE19",
                            PasswordHash = "AQAAAAIAAYagAAAAEHDQ4hR9bNkq7qMqM1IJexxLGu35B5zacFYbEH36Am67X0Av/CUoAK7Xdtw1M4U7wg==",
                            SecurityStamp = "4b3c3dfa-5822-4f48-926d-bf100459ecc0",
                            UserName = "JohnDoe19"
                        },
                        new
                        {
                            Id = "adbe2dec-f42c-4219-999d-06af7770cfaf",
                            ConcurrencyStamp = "b4c8fd0c-4699-4056-b4e4-cd4cddd7210d",
                            Email = "johndoe20@personal.gmail",
                            NormalizedEmail = "JOHNDOE20@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE20",
                            PasswordHash = "AQAAAAIAAYagAAAAEBbgQ2YMf3vYsCXGNDdRnE+patls20SFn2p6pV/X3mhT4hZaDvhVT9IDvOiEgynoEA==",
                            SecurityStamp = "c2491059-2f68-471c-b72c-95f7e6c87145",
                            UserName = "JohnDoe20"
                        },
                        new
                        {
                            Id = "0eaa772f-2e6f-413e-accd-9b97c0fc9817",
                            ConcurrencyStamp = "9e1a63d5-cdd4-4bc5-b434-e6bc5d115fc7",
                            Email = "johndoe21@personal.gmail",
                            NormalizedEmail = "JOHNDOE21@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE21",
                            PasswordHash = "AQAAAAIAAYagAAAAEHUROYiVwtweWu9KW/i6iINSQFt4LTW9F9nu0ikwe0TfaD/D5hZmr7miM+aqnoQwjQ==",
                            SecurityStamp = "46e14df6-6579-4cde-bfd9-080c4a04dbe6",
                            UserName = "JohnDoe21"
                        },
                        new
                        {
                            Id = "a0a41562-9780-4178-bbc2-55e89cee8fd1",
                            ConcurrencyStamp = "b798dcce-97c8-4c56-9d92-cb82ac7a8528",
                            Email = "johndoe22@personal.gmail",
                            NormalizedEmail = "JOHNDOE22@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE22",
                            PasswordHash = "AQAAAAIAAYagAAAAEAAIs44XN092Mlrt0EmLYnajEM+IMawzp4BxRwg0o0aXl1MX/VlKWgHfVGSyHgXFkQ==",
                            SecurityStamp = "74be6b64-21d7-412e-accf-7eacf64cac70",
                            UserName = "JohnDoe22"
                        },
                        new
                        {
                            Id = "ae73bd2b-a05a-4411-b079-2babd206f6a5",
                            ConcurrencyStamp = "4da74559-723c-4b5c-b9a0-3db5b08a8d04",
                            Email = "johndoe23@personal.gmail",
                            NormalizedEmail = "JOHNDOE23@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE23",
                            PasswordHash = "AQAAAAIAAYagAAAAEHH8rTfT6XMMJK2ugUKkAQkJb4dCeR+pNYXF1XWjQcZJ12VivbR+aGxZUvNwHrO3Sw==",
                            SecurityStamp = "0961815c-128f-4a40-b3ee-d0ffa7866087",
                            UserName = "JohnDoe23"
                        },
                        new
                        {
                            Id = "b5a8bab7-03d0-418e-943a-01d836ddb42c",
                            ConcurrencyStamp = "437c1c43-d493-4796-ac5c-556e3dc7c4f0",
                            Email = "johndoe24@personal.gmail",
                            NormalizedEmail = "JOHNDOE24@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE24",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ7uq8Sdoy143EQ/88NzDGm5SzlT6OZQQ27yWmjEwn4kykrt1cVKMRJT05S2kvNFZQ==",
                            SecurityStamp = "a022fb6b-9743-4a28-83c7-65be536f5774",
                            UserName = "JohnDoe24"
                        },
                        new
                        {
                            Id = "5dcf3f43-7f26-4ff6-8424-7ecc46e376fd",
                            ConcurrencyStamp = "e4a96939-e045-4efd-a508-350368e05281",
                            Email = "johndoe25@personal.gmail",
                            NormalizedEmail = "JOHNDOE25@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE25",
                            PasswordHash = "AQAAAAIAAYagAAAAEGrhd1a+QwPmSt38B26ibE07kZx6I/kwqjFa2Jqv3Wqqk2YApSy8i5hNIUZNYKXUyQ==",
                            SecurityStamp = "c43f01c9-3f80-42b3-9980-288c819782e5",
                            UserName = "JohnDoe25"
                        },
                        new
                        {
                            Id = "7ee4dff1-e5b6-47a1-a2b9-3d9171f974e7",
                            ConcurrencyStamp = "9ba7af94-2182-4315-a4f9-6e428748ca52",
                            Email = "johndoe26@personal.gmail",
                            NormalizedEmail = "JOHNDOE26@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE26",
                            PasswordHash = "AQAAAAIAAYagAAAAEPQ8aAPU7qUEygPL5OqdHX2NLgGMqocmUw5rxqoYFWXu0NvGBUeHz+GDmaZGolBurg==",
                            SecurityStamp = "941b1882-3dda-47e8-baba-48a87daf4010",
                            UserName = "JohnDoe26"
                        },
                        new
                        {
                            Id = "61bc6b48-601e-4f7d-9ff9-b6f58428962b",
                            ConcurrencyStamp = "156746cd-3e1b-4955-83b3-e0126b6bbfd3",
                            Email = "johndoe27@personal.gmail",
                            NormalizedEmail = "JOHNDOE27@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE27",
                            PasswordHash = "AQAAAAIAAYagAAAAEHCSq8wB5PvtWrfimoqfOm3zSAeMXMSQTu94Yjx7MmyYKQUe3b0X6dF4zZTxmIy2Dg==",
                            SecurityStamp = "d07d99f6-c974-40c0-a4a4-180a359bd890",
                            UserName = "JohnDoe27"
                        },
                        new
                        {
                            Id = "04bfbe69-1dbb-4410-8323-3354d31defb7",
                            ConcurrencyStamp = "7e7ddd86-9ec3-4c02-bf48-0ef5a03983e7",
                            Email = "johndoe28@personal.gmail",
                            NormalizedEmail = "JOHNDOE28@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE28",
                            PasswordHash = "AQAAAAIAAYagAAAAEN3K5WcOrgw82GQOPTM/57OlVJ1ps4WB4b7CIk0SizMGetWvIiBhDKMGHMjwvzHMRA==",
                            SecurityStamp = "fc2610ad-c754-4f7a-b773-d5fba4ef851b",
                            UserName = "JohnDoe28"
                        },
                        new
                        {
                            Id = "12fd4dcb-93a8-47bf-a846-9dfcdd73133a",
                            ConcurrencyStamp = "98f9258b-7dff-462d-aec6-35cac5a0d371",
                            Email = "johndoe29@personal.gmail",
                            NormalizedEmail = "JOHNDOE29@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE29",
                            PasswordHash = "AQAAAAIAAYagAAAAECW3svHDeXC5l9aePU+GHkSw9KQBJPf3bwadUaBmFsUVD3zWNJ85Y390gGCXIOfWPg==",
                            SecurityStamp = "257f669a-6f38-4c36-8216-097498f5954e",
                            UserName = "JohnDoe29"
                        },
                        new
                        {
                            Id = "e0cee4fa-2379-4377-abaa-0de2b8993805",
                            ConcurrencyStamp = "7728233c-bc55-4ba0-a55d-dcff9c872067",
                            Email = "johndoe30@personal.gmail",
                            NormalizedEmail = "JOHNDOE30@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE30",
                            PasswordHash = "AQAAAAIAAYagAAAAENboHrhooqhWAOwrRxDBaAU88umTijbu0kS8hwGfL3hLaCaUN7LzFBZBo/ozhAIQow==",
                            SecurityStamp = "450c9127-1bad-40f2-95c4-0e968391be12",
                            UserName = "JohnDoe30"
                        },
                        new
                        {
                            Id = "6324a8a4-d5fe-4faf-a079-aee91be2f6fa",
                            ConcurrencyStamp = "f4fed0a1-192e-4c4c-a5fb-8a850b2e196e",
                            Email = "johndoe31@personal.gmail",
                            NormalizedEmail = "JOHNDOE31@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE31",
                            PasswordHash = "AQAAAAIAAYagAAAAEMx9aECB1FFZHUc8W7Gq6j2KuYS9YWqiUnsjMSMXz4SWCjosfcSV1Cwv3Wq9gCBC2Q==",
                            SecurityStamp = "eecc18ee-4327-4be0-b46c-e594ccde4fc6",
                            UserName = "JohnDoe31"
                        },
                        new
                        {
                            Id = "b0e7d16e-faa6-4da0-a0b1-b7129ffeffc8",
                            ConcurrencyStamp = "865a4034-e04b-4851-8e5c-e179fbd31c90",
                            Email = "johndoe32@personal.gmail",
                            NormalizedEmail = "JOHNDOE32@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE32",
                            PasswordHash = "AQAAAAIAAYagAAAAEKkUgAP/WyeeTbL/+m5wjK8UQFW3Henmd4bIO0Ifo2I7Yyvk4TGxGS7YNHYc0hEDeg==",
                            SecurityStamp = "c7cbf98c-e49c-404b-9a2f-4f488227b38c",
                            UserName = "JohnDoe32"
                        },
                        new
                        {
                            Id = "b20d6ec2-9ef2-47e0-b38d-2044f0939a9a",
                            ConcurrencyStamp = "551ac668-4f1e-4ec9-966f-c58462b4e629",
                            Email = "johndoe33@personal.gmail",
                            NormalizedEmail = "JOHNDOE33@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE33",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ3lQDs8oO9Xpzwfg5owcOdGCut2he2JLELCrWJe3lm99ixost1AeVeFlIf5g4VUkQ==",
                            SecurityStamp = "bf29b7ac-8702-45cf-9624-3e263f17330a",
                            UserName = "JohnDoe33"
                        },
                        new
                        {
                            Id = "9be446bc-5f79-4fd2-9a45-86b6bf18164c",
                            ConcurrencyStamp = "af7251b0-404d-4d05-b29e-3f6105accd94",
                            Email = "johndoe34@personal.gmail",
                            NormalizedEmail = "JOHNDOE34@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE34",
                            PasswordHash = "AQAAAAIAAYagAAAAEKMEI3UJ072d+fetKiGNFraPWqh9m7U9c72TMOVncKni8c7gQO2Ifbua1OPUu3+BRA==",
                            SecurityStamp = "268c95ac-9234-494f-9abc-c7d01e306a3d",
                            UserName = "JohnDoe34"
                        },
                        new
                        {
                            Id = "fd54cf62-3166-455e-bc4a-5542d2fcbece",
                            ConcurrencyStamp = "b6b818c2-3222-4769-9c03-3d6dd98a5949",
                            Email = "johndoe35@personal.gmail",
                            NormalizedEmail = "JOHNDOE35@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE35",
                            PasswordHash = "AQAAAAIAAYagAAAAEGRE7GImGEvfUSkiyZqQ/JuRkkAw1IoMndteYnEv3EoAVHvxdGDxQ78A22dfv050Yg==",
                            SecurityStamp = "d40445f1-2174-4e72-b56d-1330d8df0ce9",
                            UserName = "JohnDoe35"
                        },
                        new
                        {
                            Id = "49e94bd6-900c-4f09-bfdb-1b8494c6c0b2",
                            ConcurrencyStamp = "7087e3de-c151-4552-9add-267edf56ede1",
                            Email = "johndoe36@personal.gmail",
                            NormalizedEmail = "JOHNDOE36@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE36",
                            PasswordHash = "AQAAAAIAAYagAAAAENb7yWpDxL4ww1A1qoJVSNVKKEEgOoOzFPNFumHtfiyzONbP4X1Im1aKeGhsi835Gg==",
                            SecurityStamp = "2d9a2927-953f-415a-bfe7-58087b5847cb",
                            UserName = "JohnDoe36"
                        },
                        new
                        {
                            Id = "7f992068-c774-4143-a93e-f7505d6558fd",
                            ConcurrencyStamp = "1910d03b-2cb3-492a-9137-15d4ddc9020c",
                            Email = "johndoe37@personal.gmail",
                            NormalizedEmail = "JOHNDOE37@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE37",
                            PasswordHash = "AQAAAAIAAYagAAAAEDng7S3hTaFjUQ5nk7WCLD4DWE0pdYcYF0oYYufq5nKCy4wnfJX4AzRj0QeJbDa/bw==",
                            SecurityStamp = "a7f99ec7-df7e-4476-99cf-da2958b90fd3",
                            UserName = "JohnDoe37"
                        },
                        new
                        {
                            Id = "03e3ebe7-f715-4953-a745-5adda48a1175",
                            ConcurrencyStamp = "e4f1cb75-a641-4829-af7a-6308c73392b4",
                            Email = "johndoe38@personal.gmail",
                            NormalizedEmail = "JOHNDOE38@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE38",
                            PasswordHash = "AQAAAAIAAYagAAAAEDbWhDfi3OK4f1G/uG545U2JDu0jWJYUfygdDaaUQ7gKG/lPFqRjB85n0c3hv6x7dw==",
                            SecurityStamp = "53a7ce48-b64a-4eb9-ae6b-8f7c67af9c49",
                            UserName = "JohnDoe38"
                        },
                        new
                        {
                            Id = "b11c433c-ed78-4206-a7ce-49750e738457",
                            ConcurrencyStamp = "f968c4b1-2c17-4042-a257-ed5d1452c794",
                            Email = "johndoe39@personal.gmail",
                            NormalizedEmail = "JOHNDOE39@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE39",
                            PasswordHash = "AQAAAAIAAYagAAAAEI39r6kmWd1k29B4/VFF82w+pOgdPhjZVoXUGXSa3xeutpUR3qhNvwk8+1/Y+ccvLQ==",
                            SecurityStamp = "63552942-3a43-452d-9d7d-f402efa836bc",
                            UserName = "JohnDoe39"
                        },
                        new
                        {
                            Id = "1745ee14-4c5e-472b-83a3-cf9bf6d286a8",
                            ConcurrencyStamp = "93aae51a-4459-48ae-ac5f-5436542e1380",
                            Email = "johndoe40@personal.gmail",
                            NormalizedEmail = "JOHNDOE40@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE40",
                            PasswordHash = "AQAAAAIAAYagAAAAEE0p4z79Qu+ELK+WgBQBFj7qIhVAtuICTzgRoWHOHjpKjcd78UaimflfNPMA0Ta4DQ==",
                            SecurityStamp = "7b1d8abb-402c-4cfd-8399-93bc4aa2b070",
                            UserName = "JohnDoe40"
                        },
                        new
                        {
                            Id = "ba68f8d6-86b8-452a-a4ac-2629e965a317",
                            ConcurrencyStamp = "b93a518d-c3ba-472c-9d4d-d89af5996825",
                            Email = "johndoe41@personal.gmail",
                            NormalizedEmail = "JOHNDOE41@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE41",
                            PasswordHash = "AQAAAAIAAYagAAAAEDJKb87ifUF+mI+Vu93Sw86tvPahr4AjtDRxAUAPI0C1+9f2TnFQSrTKwL4biYuJCQ==",
                            SecurityStamp = "b27e1556-9189-463f-9907-e83bb941a6a3",
                            UserName = "JohnDoe41"
                        },
                        new
                        {
                            Id = "46f89730-8934-4810-baa0-a97b69643ecf",
                            ConcurrencyStamp = "1af4508a-d5ff-4a94-93ce-2c8e5436a03f",
                            Email = "johndoe42@personal.gmail",
                            NormalizedEmail = "JOHNDOE42@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE42",
                            PasswordHash = "AQAAAAIAAYagAAAAEG07vdC7LtGCG/BQ4zfV66+y2wbtPmcO9WImWLeS0MujWfCZqoC34YOmF06mmHRdoA==",
                            SecurityStamp = "e5938d03-9cda-4e5f-96e6-a4d4388f58ef",
                            UserName = "JohnDoe42"
                        },
                        new
                        {
                            Id = "212aa15c-217e-4f1f-958a-652f6b30affd",
                            ConcurrencyStamp = "ff00b96a-132c-4237-b7c5-786881534363",
                            Email = "johndoe43@personal.gmail",
                            NormalizedEmail = "JOHNDOE43@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE43",
                            PasswordHash = "AQAAAAIAAYagAAAAEL7TRONWs0Zyt4K2r/VU1R+B6jyCmt5X9LOyXXQzp+IGb3PsDJ179LUtXlG9k/COXg==",
                            SecurityStamp = "fde44a19-560d-4a31-b7a5-d6496311e4a7",
                            UserName = "JohnDoe43"
                        },
                        new
                        {
                            Id = "62486b56-916a-4386-97e9-daecab4baad3",
                            ConcurrencyStamp = "0daa65e8-5fdf-420b-a248-9cf0690a7bcf",
                            Email = "johndoe44@personal.gmail",
                            NormalizedEmail = "JOHNDOE44@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE44",
                            PasswordHash = "AQAAAAIAAYagAAAAENfFTBFM7w5ZQ7q7kWcUf9JVS/eLEVrhDbrG/QiUdIm7hAmkynZK5cGsjd/JQJ1HxQ==",
                            SecurityStamp = "711fc7c9-d74d-48a9-a5b2-63d29752a3a9",
                            UserName = "JohnDoe44"
                        },
                        new
                        {
                            Id = "1344fe82-c7f0-4a71-a9e7-dd24b68a0ef5",
                            ConcurrencyStamp = "042b6f47-7ace-488e-a6b1-bc03c424da05",
                            Email = "johndoe45@personal.gmail",
                            NormalizedEmail = "JOHNDOE45@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE45",
                            PasswordHash = "AQAAAAIAAYagAAAAEO5hzTlLvHL1Fu5UYSUeBD72iyZAcIeMX3ZUw9tKKK1DdMw71sGpnxLiAJXtZDX82g==",
                            SecurityStamp = "f4506293-2441-440f-9936-8ff243f18c84",
                            UserName = "JohnDoe45"
                        },
                        new
                        {
                            Id = "a6b956d5-5419-4d48-803c-89bb45fc8223",
                            ConcurrencyStamp = "493e1ce1-f635-4174-88dc-032d2f975af3",
                            Email = "johndoe46@personal.gmail",
                            NormalizedEmail = "JOHNDOE46@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE46",
                            PasswordHash = "AQAAAAIAAYagAAAAENOecNlSL1Vehshe/qH+m6sOjt+uWr9bVk0/nTZOUu/ufR1nfN/dM309bu1w+1ljxg==",
                            SecurityStamp = "ecd66908-80c2-48b9-aed6-9d81cdcaa650",
                            UserName = "JohnDoe46"
                        },
                        new
                        {
                            Id = "3e04b0d5-6a68-402a-b988-285d4ecef50e",
                            ConcurrencyStamp = "7ff4a32c-9fd2-4845-8d0a-74f2a8f375fa",
                            Email = "johndoe47@personal.gmail",
                            NormalizedEmail = "JOHNDOE47@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE47",
                            PasswordHash = "AQAAAAIAAYagAAAAEDp7rz0s2zuC0Vc5bCTWmsinbnAjmuYksa6oh5dKHhg/a0o3unTIZs2y6V+lKA4mQw==",
                            SecurityStamp = "e680f5d3-1d78-499e-a9bd-f59bb2bf448d",
                            UserName = "JohnDoe47"
                        },
                        new
                        {
                            Id = "0d86360c-c794-42b8-876f-7b3138fbb907",
                            ConcurrencyStamp = "03a20d69-072b-46ca-92ed-36f495e220c8",
                            Email = "johndoe48@personal.gmail",
                            NormalizedEmail = "JOHNDOE48@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE48",
                            PasswordHash = "AQAAAAIAAYagAAAAEA9zKwqk5zC9ckUDue+tMvY9NCUnGgmmTudDIgcTMCOp57YVhCQrCa39Wtas+N59Lw==",
                            SecurityStamp = "4649c0b4-a7d1-4089-b4cf-6c5969768306",
                            UserName = "JohnDoe48"
                        },
                        new
                        {
                            Id = "b7a67b62-34b5-40c2-93d1-a5c7c8f8f9e4",
                            ConcurrencyStamp = "bfee7210-a7f9-44cd-8807-846dc4962af5",
                            Email = "johndoe49@personal.gmail",
                            NormalizedEmail = "JOHNDOE49@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE49",
                            PasswordHash = "AQAAAAIAAYagAAAAEGpDpgaTgc6J7lZR/BAr46cX9+NFYVxqH/rf7A7ztGxTAU/5CYF7Dk8+PLLk1REtBw==",
                            SecurityStamp = "d39057bb-9d7a-4eae-989f-3aa7c77d0cce",
                            UserName = "JohnDoe49"
                        },
                        new
                        {
                            Id = "d251a522-baf7-43c7-8b9c-476dac1f0d06",
                            ConcurrencyStamp = "88bfdd28-b9f8-4fe2-a3c9-1b7f32662af9",
                            Email = "johndoe50@personal.gmail",
                            NormalizedEmail = "JOHNDOE50@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE50",
                            PasswordHash = "AQAAAAIAAYagAAAAEO09reWYfsZN5DEZDEV/htdv5mrQThQaYzzNH0QbrTlfGN3Jh62aYrr5B5YLvplAXw==",
                            SecurityStamp = "48357c8d-749d-4a8d-a907-47afed9b27bb",
                            UserName = "JohnDoe50"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CompanyEmail = "johndoe1@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Finance Manager",
                            LastName = "Doe",
                            Salary = 3249.0m,
                            UserId = "5ad53192-de89-4d3b-ba04-64f1e16fea85"
                        },
                        new
                        {
                            Id = 102,
                            CompanyEmail = "johndoe2@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "IT Manager",
                            LastName = "Doe",
                            Salary = 6411.0m,
                            UserId = "144130da-c375-4cdd-9d24-96944786d0cf"
                        },
                        new
                        {
                            Id = 103,
                            CompanyEmail = "johndoe3@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Manager",
                            LastName = "Doe",
                            Salary = 3040.5m,
                            UserId = "f9c57357-af13-46ce-8fce-fd2565902431"
                        },
                        new
                        {
                            Id = 104,
                            CompanyEmail = "johndoe4@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Manager",
                            LastName = "Doe",
                            Salary = 5959.5m,
                            UserId = "6408f506-777d-49a2-95d8-caca851659bb"
                        },
                        new
                        {
                            Id = 105,
                            CompanyEmail = "johndoe5@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Manager",
                            LastName = "Doe",
                            Salary = 4462.5m,
                            UserId = "608675be-be73-467b-b7de-0c5cbcc02f66"
                        },
                        new
                        {
                            Id = 106,
                            CompanyEmail = "johndoe6@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Salary = 2250.0m,
                            UserId = "da0be6f6-efa0-4623-98b7-f0b379022cca"
                        },
                        new
                        {
                            Id = 107,
                            CompanyEmail = "johndoe7@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2091m,
                            UserId = "0b605576-77bc-45f5-aabc-e4953d47f8ad"
                        },
                        new
                        {
                            Id = 108,
                            CompanyEmail = "johndoe8@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4383m,
                            UserId = "a0266ed4-1792-4fa7-ac84-96496b9de7b5"
                        },
                        new
                        {
                            Id = 109,
                            CompanyEmail = "johndoe9@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2195m,
                            UserId = "4755c5cc-7a2f-4b65-92df-862049afa63a"
                        },
                        new
                        {
                            Id = 110,
                            CompanyEmail = "johndoe10@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 2070m,
                            UserId = "27d67d92-b6d9-4aa3-a08a-c27a898553af"
                        },
                        new
                        {
                            Id = 111,
                            CompanyEmail = "johndoe11@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2619m,
                            UserId = "d63eb99e-8aa0-4c32-902a-253cc4cb8df3"
                        },
                        new
                        {
                            Id = 112,
                            CompanyEmail = "johndoe12@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1583m,
                            UserId = "1b1f7829-ca7b-41d6-aaa7-c4c8b236729b"
                        },
                        new
                        {
                            Id = 113,
                            CompanyEmail = "johndoe13@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2098m,
                            UserId = "3a335e8e-f962-4bf5-ac3d-dbcd381977f8"
                        },
                        new
                        {
                            Id = 114,
                            CompanyEmail = "johndoe14@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4064m,
                            UserId = "f07d1174-a712-4118-bf7a-3f17663b5e44"
                        },
                        new
                        {
                            Id = 115,
                            CompanyEmail = "johndoe15@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2040m,
                            UserId = "2611bcac-eeda-4978-a9ae-96bea754e763"
                        },
                        new
                        {
                            Id = 116,
                            CompanyEmail = "johndoe16@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 2598m,
                            UserId = "deab66c4-afa6-49fb-87ff-8db028e02c6c"
                        },
                        new
                        {
                            Id = 117,
                            CompanyEmail = "johndoe17@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2597m,
                            UserId = "bd875332-d78a-4e50-9c58-0c42921aa70a"
                        },
                        new
                        {
                            Id = 118,
                            CompanyEmail = "johndoe18@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1517m,
                            UserId = "7985e76b-c94e-4a6e-bbbd-abece7d3a407"
                        },
                        new
                        {
                            Id = 119,
                            CompanyEmail = "johndoe19@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2066m,
                            UserId = "8792960b-d7d3-49f9-891c-d6c9955b6d4d"
                        },
                        new
                        {
                            Id = 120,
                            CompanyEmail = "johndoe20@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4085m,
                            UserId = "adbe2dec-f42c-4219-999d-06af7770cfaf"
                        },
                        new
                        {
                            Id = 121,
                            CompanyEmail = "johndoe21@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2055m,
                            UserId = "0eaa772f-2e6f-413e-accd-9b97c0fc9817"
                        },
                        new
                        {
                            Id = 122,
                            CompanyEmail = "johndoe22@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 3136m,
                            UserId = "a0a41562-9780-4178-bbc2-55e89cee8fd1"
                        },
                        new
                        {
                            Id = 123,
                            CompanyEmail = "johndoe23@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2614m,
                            UserId = "ae73bd2b-a05a-4411-b079-2babd206f6a5"
                        },
                        new
                        {
                            Id = 124,
                            CompanyEmail = "johndoe24@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1595m,
                            UserId = "b5a8bab7-03d0-418e-943a-01d836ddb42c"
                        },
                        new
                        {
                            Id = 125,
                            CompanyEmail = "johndoe25@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2171m,
                            UserId = "5dcf3f43-7f26-4ff6-8424-7ecc46e376fd"
                        },
                        new
                        {
                            Id = 126,
                            CompanyEmail = "johndoe26@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4791m,
                            UserId = "7ee4dff1-e5b6-47a1-a2b9-3d9171f974e7"
                        },
                        new
                        {
                            Id = 127,
                            CompanyEmail = "johndoe27@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2057m,
                            UserId = "61bc6b48-601e-4f7d-9ff9-b6f58428962b"
                        },
                        new
                        {
                            Id = 128,
                            CompanyEmail = "johndoe28@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 3473m,
                            UserId = "04bfbe69-1dbb-4410-8323-3354d31defb7"
                        },
                        new
                        {
                            Id = 129,
                            CompanyEmail = "johndoe29@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2545m,
                            UserId = "12fd4dcb-93a8-47bf-a846-9dfcdd73133a"
                        },
                        new
                        {
                            Id = 130,
                            CompanyEmail = "johndoe30@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1651m,
                            UserId = "e0cee4fa-2379-4377-abaa-0de2b8993805"
                        },
                        new
                        {
                            Id = 131,
                            CompanyEmail = "johndoe31@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2060m,
                            UserId = "6324a8a4-d5fe-4faf-a079-aee91be2f6fa"
                        },
                        new
                        {
                            Id = 132,
                            CompanyEmail = "johndoe32@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4308m,
                            UserId = "b0e7d16e-faa6-4da0-a0b1-b7129ffeffc8"
                        },
                        new
                        {
                            Id = 133,
                            CompanyEmail = "johndoe33@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2060m,
                            UserId = "b20d6ec2-9ef2-47e0-b38d-2044f0939a9a"
                        },
                        new
                        {
                            Id = 134,
                            CompanyEmail = "johndoe34@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 2763m,
                            UserId = "9be446bc-5f79-4fd2-9a45-86b6bf18164c"
                        },
                        new
                        {
                            Id = 135,
                            CompanyEmail = "johndoe35@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2530m,
                            UserId = "fd54cf62-3166-455e-bc4a-5542d2fcbece"
                        },
                        new
                        {
                            Id = 136,
                            CompanyEmail = "johndoe36@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1704m,
                            UserId = "49e94bd6-900c-4f09-bfdb-1b8494c6c0b2"
                        },
                        new
                        {
                            Id = 137,
                            CompanyEmail = "johndoe37@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2039m,
                            UserId = "7f992068-c774-4143-a93e-f7505d6558fd"
                        },
                        new
                        {
                            Id = 138,
                            CompanyEmail = "johndoe38@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4449m,
                            UserId = "03e3ebe7-f715-4953-a745-5adda48a1175"
                        },
                        new
                        {
                            Id = 139,
                            CompanyEmail = "johndoe39@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2185m,
                            UserId = "b11c433c-ed78-4206-a7ce-49750e738457"
                        },
                        new
                        {
                            Id = 140,
                            CompanyEmail = "johndoe40@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 4709m,
                            UserId = "1745ee14-4c5e-472b-83a3-cf9bf6d286a8"
                        },
                        new
                        {
                            Id = 141,
                            CompanyEmail = "johndoe41@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2726m,
                            UserId = "ba68f8d6-86b8-452a-a4ac-2629e965a317"
                        },
                        new
                        {
                            Id = 142,
                            CompanyEmail = "johndoe42@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1565m,
                            UserId = "46f89730-8934-4810-baa0-a97b69643ecf"
                        },
                        new
                        {
                            Id = 143,
                            CompanyEmail = "johndoe43@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2185m,
                            UserId = "212aa15c-217e-4f1f-958a-652f6b30affd"
                        },
                        new
                        {
                            Id = 144,
                            CompanyEmail = "johndoe44@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4436m,
                            UserId = "62486b56-916a-4386-97e9-daecab4baad3"
                        },
                        new
                        {
                            Id = 145,
                            CompanyEmail = "johndoe45@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2095m,
                            UserId = "1344fe82-c7f0-4a71-a9e7-dd24b68a0ef5"
                        },
                        new
                        {
                            Id = 146,
                            CompanyEmail = "johndoe46@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 4997m,
                            UserId = "a6b956d5-5419-4d48-803c-89bb45fc8223"
                        },
                        new
                        {
                            Id = 147,
                            CompanyEmail = "johndoe47@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2904m,
                            UserId = "3e04b0d5-6a68-402a-b988-285d4ecef50e"
                        },
                        new
                        {
                            Id = 148,
                            CompanyEmail = "johndoe48@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1604m,
                            UserId = "0d86360c-c794-42b8-876f-7b3138fbb907"
                        },
                        new
                        {
                            Id = 149,
                            CompanyEmail = "johndoe49@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2129m,
                            UserId = "b7a67b62-34b5-40c2-93d1-a5c7c8f8f9e4"
                        },
                        new
                        {
                            Id = 150,
                            CompanyEmail = "johndoe50@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4313m,
                            UserId = "d251a522-baf7-43c7-8b9c-476dac1f0d06"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "112b2b72-9326-4077-85d1-7b89f77e4340",
                            Name = "HR Admin",
                            NormalizedName = "HR ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "4a8c1c6f-3540-4f21-9651-fda27a20e4dd",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "5ffa392f-15d3-4427-90f7-a22d0a2d568b",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "5ad53192-de89-4d3b-ba04-64f1e16fea85",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "144130da-c375-4cdd-9d24-96944786d0cf",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "f9c57357-af13-46ce-8fce-fd2565902431",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "6408f506-777d-49a2-95d8-caca851659bb",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "608675be-be73-467b-b7de-0c5cbcc02f66",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "da0be6f6-efa0-4623-98b7-f0b379022cca",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "0b605576-77bc-45f5-aabc-e4953d47f8ad",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a0266ed4-1792-4fa7-ac84-96496b9de7b5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4755c5cc-7a2f-4b65-92df-862049afa63a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "27d67d92-b6d9-4aa3-a08a-c27a898553af",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d63eb99e-8aa0-4c32-902a-253cc4cb8df3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "1b1f7829-ca7b-41d6-aaa7-c4c8b236729b",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "3a335e8e-f962-4bf5-ac3d-dbcd381977f8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "f07d1174-a712-4118-bf7a-3f17663b5e44",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2611bcac-eeda-4978-a9ae-96bea754e763",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "deab66c4-afa6-49fb-87ff-8db028e02c6c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "bd875332-d78a-4e50-9c58-0c42921aa70a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7985e76b-c94e-4a6e-bbbd-abece7d3a407",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "8792960b-d7d3-49f9-891c-d6c9955b6d4d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "adbe2dec-f42c-4219-999d-06af7770cfaf",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0eaa772f-2e6f-413e-accd-9b97c0fc9817",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a0a41562-9780-4178-bbc2-55e89cee8fd1",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ae73bd2b-a05a-4411-b079-2babd206f6a5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b5a8bab7-03d0-418e-943a-01d836ddb42c",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "5dcf3f43-7f26-4ff6-8424-7ecc46e376fd",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7ee4dff1-e5b6-47a1-a2b9-3d9171f974e7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "61bc6b48-601e-4f7d-9ff9-b6f58428962b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "04bfbe69-1dbb-4410-8323-3354d31defb7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "12fd4dcb-93a8-47bf-a846-9dfcdd73133a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e0cee4fa-2379-4377-abaa-0de2b8993805",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "6324a8a4-d5fe-4faf-a079-aee91be2f6fa",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b0e7d16e-faa6-4da0-a0b1-b7129ffeffc8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b20d6ec2-9ef2-47e0-b38d-2044f0939a9a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9be446bc-5f79-4fd2-9a45-86b6bf18164c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "fd54cf62-3166-455e-bc4a-5542d2fcbece",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "49e94bd6-900c-4f09-bfdb-1b8494c6c0b2",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "7f992068-c774-4143-a93e-f7505d6558fd",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "03e3ebe7-f715-4953-a745-5adda48a1175",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b11c433c-ed78-4206-a7ce-49750e738457",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "1745ee14-4c5e-472b-83a3-cf9bf6d286a8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ba68f8d6-86b8-452a-a4ac-2629e965a317",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "46f89730-8934-4810-baa0-a97b69643ecf",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "212aa15c-217e-4f1f-958a-652f6b30affd",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "62486b56-916a-4386-97e9-daecab4baad3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "1344fe82-c7f0-4a71-a9e7-dd24b68a0ef5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a6b956d5-5419-4d48-803c-89bb45fc8223",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3e04b0d5-6a68-402a-b988-285d4ecef50e",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0d86360c-c794-42b8-876f-7b3138fbb907",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "b7a67b62-34b5-40c2-93d1-a5c7c8f8f9e4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d251a522-baf7-43c7-8b9c-476dac1f0d06",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HumanCapitalManagement.Data.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
