// <auto-generated />
using HumanCapitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanCapitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250717161507_SeedNewDb")]
    partial class SeedNewDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanCapitalManagement.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "84c9f667-1b92-4e71-bca0-ffbe2d448d77",
                            ConcurrencyStamp = "3dba5056-525d-48ef-b518-6f93d53577aa",
                            Email = "johndoe1@personal.gmail",
                            NormalizedEmail = "JOHNDOE1@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEPZgZ2gN7PkZJrGyO+LOILhi/9lQiozACTJ3fq687nWNNCn5SssutPJEWvOHhO1F7g==",
                            SecurityStamp = "21ef3c9a-0b2a-4b11-bb8b-16d09b34a962",
                            UserName = "JohnDoe1"
                        },
                        new
                        {
                            Id = "8dad293a-e2da-43dc-b4aa-03b2b947c921",
                            ConcurrencyStamp = "4e4e2f90-5ced-424e-ab08-e7236cf36e44",
                            Email = "johndoe2@personal.gmail",
                            NormalizedEmail = "JOHNDOE2@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE2",
                            PasswordHash = "AQAAAAIAAYagAAAAELsU/czUH6UzoSwp2iyXuSZpRYGqmd6hgeKf6NErv6nmPyzkLx+Jw19ANpg9UvxFww==",
                            SecurityStamp = "434e6aea-1452-432b-8b58-20c189ce1219",
                            UserName = "JohnDoe2"
                        },
                        new
                        {
                            Id = "583b51c7-92ac-483d-817b-8f5e879347dd",
                            ConcurrencyStamp = "d67ac67f-4f2e-41c3-a323-2769b4c81438",
                            Email = "johndoe3@personal.gmail",
                            NormalizedEmail = "JOHNDOE3@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE3",
                            PasswordHash = "AQAAAAIAAYagAAAAEE253qlxGONORvInqjhFd2lfjqwpn4IbqM+BD48pUHa7miRQ9SawyxRCHul4YnhupQ==",
                            SecurityStamp = "012c8c4d-9ae5-4de0-aec8-f0b4d7a1654d",
                            UserName = "JohnDoe3"
                        },
                        new
                        {
                            Id = "fed6a67c-4e0b-430a-a1e7-12dec58a2c7f",
                            ConcurrencyStamp = "8564db79-4d35-4790-8ea6-f92cd8d913c2",
                            Email = "johndoe4@personal.gmail",
                            NormalizedEmail = "JOHNDOE4@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEP+oVIHZ2PZPBhxeWnBFdXA8qc7jSTxqbVbFQAD3fk8qa5IZmarh0kGjVdhja2pVqg==",
                            SecurityStamp = "99b056de-9ac8-4520-8808-1cbc861a42a3",
                            UserName = "JohnDoe4"
                        },
                        new
                        {
                            Id = "16363638-ce9f-4c56-a071-8c8bb4dac1d4",
                            ConcurrencyStamp = "528173b9-48e4-4dd2-8fbf-239e20b22ee3",
                            Email = "johndoe5@personal.gmail",
                            NormalizedEmail = "JOHNDOE5@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE5",
                            PasswordHash = "AQAAAAIAAYagAAAAEPl9JfY3k7K78iodD/5QtrcADYwZ5zVZaf2167Gqj9L74J728iaqRsQVJQ1Tzyp8hg==",
                            SecurityStamp = "2ca832be-8143-41a8-ac87-7e48d09a47ab",
                            UserName = "JohnDoe5"
                        },
                        new
                        {
                            Id = "b8cab2d7-8a04-4a7f-83e8-5f6c8d683532",
                            ConcurrencyStamp = "363e7ed3-0e22-4b4f-be8a-f7022d38aab8",
                            Email = "johndoe6@personal.gmail",
                            NormalizedEmail = "JOHNDOE6@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE6",
                            PasswordHash = "AQAAAAIAAYagAAAAEI0+cOQqGKBPkXSbROT0xIykZo7AFqxEf76N9rrQPkG+6D3i6HltwXlP+7vLZBQz0A==",
                            SecurityStamp = "e9a871e7-e2d9-431e-aec9-33277944cb56",
                            UserName = "JohnDoe6"
                        },
                        new
                        {
                            Id = "963f193f-d637-4298-b34e-50cd195e9ca0",
                            ConcurrencyStamp = "616d6eb9-2995-4c07-a086-1d769d828356",
                            Email = "johndoe7@personal.gmail",
                            NormalizedEmail = "JOHNDOE7@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE7",
                            PasswordHash = "AQAAAAIAAYagAAAAENp5mP1pkh7lyonyRNZ2DruCs11aTwOEbP7Lx8ejGoYnser3DSa3dTsb2SKLY7fU9Q==",
                            SecurityStamp = "efc2aec8-cb95-43f9-9299-7b532688270a",
                            UserName = "JohnDoe7"
                        },
                        new
                        {
                            Id = "008d35f8-df6d-4042-8a99-e9f785afab49",
                            ConcurrencyStamp = "38cc16fc-fb22-4d9a-af07-467ba5034283",
                            Email = "johndoe8@personal.gmail",
                            NormalizedEmail = "JOHNDOE8@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE8",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkkG/+oJwGA17oo6vlGEP3M7BKi8koQt7v3KxgW5AGvRH6ZDi59lSdAyz4YnF+Eyw==",
                            SecurityStamp = "c8348b94-6180-4334-9c00-b46cd4b0432b",
                            UserName = "JohnDoe8"
                        },
                        new
                        {
                            Id = "3a901c1f-4c78-4500-90e4-91be3686cc6d",
                            ConcurrencyStamp = "cee89cfb-e0dd-47db-9899-340c65fbd38c",
                            Email = "johndoe9@personal.gmail",
                            NormalizedEmail = "JOHNDOE9@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE9",
                            PasswordHash = "AQAAAAIAAYagAAAAEF8aQBTd2IukBQTqGAThG/GZss7jVWwwu4Pdpc4bY9n+bFsvt521OzC+SWySjhAkSw==",
                            SecurityStamp = "9f60887d-f593-4295-9aad-df600dabeab3",
                            UserName = "JohnDoe9"
                        },
                        new
                        {
                            Id = "8a9ce2d8-f247-4faf-96df-311a461160e8",
                            ConcurrencyStamp = "e8935dfe-e4ef-4ac2-8dc6-2f8ad13b1efb",
                            Email = "johndoe10@personal.gmail",
                            NormalizedEmail = "JOHNDOE10@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE10",
                            PasswordHash = "AQAAAAIAAYagAAAAEC9Pc6ZoXgF+avK0c55lzjVld4R+KWg7BXt0V/da1AwVngM/OpexmPuEFZS9BsMIYQ==",
                            SecurityStamp = "e87ecff3-d8ed-42fa-bf24-350d958d0927",
                            UserName = "JohnDoe10"
                        },
                        new
                        {
                            Id = "87bf58ea-f556-484f-a6a5-afd85779004d",
                            ConcurrencyStamp = "f55d1388-9775-42cf-80fd-60e40ba6b336",
                            Email = "johndoe11@personal.gmail",
                            NormalizedEmail = "JOHNDOE11@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE11",
                            PasswordHash = "AQAAAAIAAYagAAAAEC8mwB6mnKYtdrbM2Jm5crfSwS15yXPuAXR83lIH9uAzg2TAbeMQFvEaSJWWZmCXpw==",
                            SecurityStamp = "584cf930-f345-42f7-bcdc-53fa0b9dde36",
                            UserName = "JohnDoe11"
                        },
                        new
                        {
                            Id = "e81725c0-99cd-40c0-a922-c6e472d026e2",
                            ConcurrencyStamp = "b5c3b5e0-2237-4507-9c55-407da5ec1690",
                            Email = "johndoe12@personal.gmail",
                            NormalizedEmail = "JOHNDOE12@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE12",
                            PasswordHash = "AQAAAAIAAYagAAAAEL5MSV05JnuCnJW0uudAFk7S/vnoQSTtgcsu6r1+5v3Q+vQffvIRsoXDMjg5cRQ8YQ==",
                            SecurityStamp = "258847b8-31f2-4d7c-a357-c1c6c9aefdee",
                            UserName = "JohnDoe12"
                        },
                        new
                        {
                            Id = "3a5b3325-6e0b-413c-a00d-5e7370b8aabd",
                            ConcurrencyStamp = "976c9ddb-35b0-40fc-b302-deb8afd2eb7e",
                            Email = "johndoe13@personal.gmail",
                            NormalizedEmail = "JOHNDOE13@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE13",
                            PasswordHash = "AQAAAAIAAYagAAAAEEAe41tQq/8wa5uLMOw0IZRv/ULm2LApgS8kn4Und3EZnFHcfMj3ndvxcbILgbIXPw==",
                            SecurityStamp = "2492429e-f6bd-4c6c-81aa-f84c95b4b8ee",
                            UserName = "JohnDoe13"
                        },
                        new
                        {
                            Id = "3909fecf-da7b-4121-9d46-c12af8c303d6",
                            ConcurrencyStamp = "d8a33cb1-834c-434d-b999-a2cb2b7ee044",
                            Email = "johndoe14@personal.gmail",
                            NormalizedEmail = "JOHNDOE14@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE14",
                            PasswordHash = "AQAAAAIAAYagAAAAENOf3Y+nvrq5XgGV91Gs7Cfe09XKBoLqbCXS9X429WUsjFK9n0tpcXrHWWeHOHQ4IQ==",
                            SecurityStamp = "dd8917de-4655-4356-ad67-3d8977f8e8b5",
                            UserName = "JohnDoe14"
                        },
                        new
                        {
                            Id = "92f2ce89-f16d-4eda-a7a8-39e9de09ac88",
                            ConcurrencyStamp = "6ebb2dd1-a6ed-46c5-b4c9-608c196b5c8a",
                            Email = "johndoe15@personal.gmail",
                            NormalizedEmail = "JOHNDOE15@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE15",
                            PasswordHash = "AQAAAAIAAYagAAAAEO/SbucccmPvrddEPF+ijjwlj69DYhnsR+yUTttWe5kBVBpixzycDjVSrLSxH/h2lQ==",
                            SecurityStamp = "a75e526f-9a27-482f-9e49-a12d0b370792",
                            UserName = "JohnDoe15"
                        },
                        new
                        {
                            Id = "5577d2a8-529e-4b13-8745-a294d1adb44d",
                            ConcurrencyStamp = "d03c3558-134f-47e2-b983-698f0802215c",
                            Email = "johndoe16@personal.gmail",
                            NormalizedEmail = "JOHNDOE16@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE16",
                            PasswordHash = "AQAAAAIAAYagAAAAEG+UbP4Idg//hggJA+HqnKxRwfEC1KjFi4NDZ/3oV2G7JY/fqpkVi8qmlUH2jdN80A==",
                            SecurityStamp = "7a83bc38-f6c3-4eb1-b0e6-8cc565aee4c9",
                            UserName = "JohnDoe16"
                        },
                        new
                        {
                            Id = "5ddb52bf-2fb1-4c49-8c2b-6db76ac38e8d",
                            ConcurrencyStamp = "8f9ddcaa-c308-432e-ac4d-e8ac17d65b26",
                            Email = "johndoe17@personal.gmail",
                            NormalizedEmail = "JOHNDOE17@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE17",
                            PasswordHash = "AQAAAAIAAYagAAAAENrLC+DXqZAnYh4a49B8/bfS6Yq4ng/cqkl4+qiTDygr/3uEtSSR/31bYUyajPQDww==",
                            SecurityStamp = "32b7d0cb-90b1-4e40-b3d0-8a6dd97f89c9",
                            UserName = "JohnDoe17"
                        },
                        new
                        {
                            Id = "cb7b5ecd-3a09-4a3c-8be6-69394de9f7af",
                            ConcurrencyStamp = "1ac781b5-8b48-412f-802d-91c5634ad3db",
                            Email = "johndoe18@personal.gmail",
                            NormalizedEmail = "JOHNDOE18@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE18",
                            PasswordHash = "AQAAAAIAAYagAAAAEAfW1YDAgb05fGHG4kAjuaqot+OIt8JkBG8NO7hOl1rPqazatPcfC2rjx9gGyB5LcA==",
                            SecurityStamp = "e7c8be31-e45c-4930-8405-bfa00c5c8116",
                            UserName = "JohnDoe18"
                        },
                        new
                        {
                            Id = "0491dece-792d-4ac5-8afc-37f791359c6b",
                            ConcurrencyStamp = "e9f382ff-ce85-4b42-b30b-936159da680a",
                            Email = "johndoe19@personal.gmail",
                            NormalizedEmail = "JOHNDOE19@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE19",
                            PasswordHash = "AQAAAAIAAYagAAAAENDCTzndA0XArOjBo4cY3TtGTMHraxzW09RN7jKIhlSJvpqw/3/DK1b007zeCvT+fQ==",
                            SecurityStamp = "6eea31b6-06a0-4534-8a31-b4518a9e4a78",
                            UserName = "JohnDoe19"
                        },
                        new
                        {
                            Id = "6fabdf76-3369-43b6-8a57-6a45925c0977",
                            ConcurrencyStamp = "f3438fea-7c5c-4429-aa8b-681971d9a414",
                            Email = "johndoe20@personal.gmail",
                            NormalizedEmail = "JOHNDOE20@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE20",
                            PasswordHash = "AQAAAAIAAYagAAAAEGzFjg4Rwx215ZD5b1gXwWhEY1uLHEaQk+zDOV3rHHan9o/JWYNMYYqGTtWHyGN8Jg==",
                            SecurityStamp = "f20e850d-a396-4518-9e0c-19950b3dcaf8",
                            UserName = "JohnDoe20"
                        },
                        new
                        {
                            Id = "d18f7900-09a2-4fe5-bbc6-28546370498b",
                            ConcurrencyStamp = "77af08c0-8319-49d9-ba18-b7a8c17311f7",
                            Email = "johndoe21@personal.gmail",
                            NormalizedEmail = "JOHNDOE21@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE21",
                            PasswordHash = "AQAAAAIAAYagAAAAENaOCgWy7rzTFSUJnrCWZQ2vCfmyDNBpR6gzxVAEcs3nbREXm+zBbTTuaE4RPHe1qw==",
                            SecurityStamp = "ff8c2031-0d06-434c-b5d8-d86ebcfab1db",
                            UserName = "JohnDoe21"
                        },
                        new
                        {
                            Id = "4d94921e-282f-49a3-ab6f-d5cca7ac33ed",
                            ConcurrencyStamp = "fb2136c1-a054-44d7-a950-9e6a1e277e99",
                            Email = "johndoe22@personal.gmail",
                            NormalizedEmail = "JOHNDOE22@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE22",
                            PasswordHash = "AQAAAAIAAYagAAAAEEc94IjyvnULRFe9pr+zvyEpS7CbKFiLPMkTPoPySXdYb+vKGjRjSS9IJsRs5PS1Pw==",
                            SecurityStamp = "51796f96-4e55-4221-bc9f-4abe805d148c",
                            UserName = "JohnDoe22"
                        },
                        new
                        {
                            Id = "f81818ee-6da0-4b7a-8e2e-7f52fca8415a",
                            ConcurrencyStamp = "ad545e5b-00d1-4fe2-bf83-4541246b940f",
                            Email = "johndoe23@personal.gmail",
                            NormalizedEmail = "JOHNDOE23@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE23",
                            PasswordHash = "AQAAAAIAAYagAAAAEPLUmUbLiEMti5ojVRRBXSd6GRIwqKAeK6HrgzSQFwsL27EK8cNMQkmj3XDhIXC8mA==",
                            SecurityStamp = "48449cc8-78a2-4c02-8605-d03157d40268",
                            UserName = "JohnDoe23"
                        },
                        new
                        {
                            Id = "326c775f-bd4c-47f6-8362-d1434fa33d55",
                            ConcurrencyStamp = "9e9d3859-7375-4e9b-9ee7-d1acfec0749f",
                            Email = "johndoe24@personal.gmail",
                            NormalizedEmail = "JOHNDOE24@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE24",
                            PasswordHash = "AQAAAAIAAYagAAAAEFOp7kA2W51fse90cdCijT0qJANaxJ1G1SHthsfLww9nzJG846PuksZt88GlXR2igg==",
                            SecurityStamp = "9922bbd2-5280-4f78-880d-45f77ad46a9e",
                            UserName = "JohnDoe24"
                        },
                        new
                        {
                            Id = "e7af04cd-637d-4d6b-a4c6-d5375823a78f",
                            ConcurrencyStamp = "822bd5f1-67b4-4064-9d9f-4efccd9576a9",
                            Email = "johndoe25@personal.gmail",
                            NormalizedEmail = "JOHNDOE25@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE25",
                            PasswordHash = "AQAAAAIAAYagAAAAEBGSMkY2zubxguHOKCKzOnc+9CmWd5Utaj3OoXVii81kwyaTbUmq/foA8CvVMK0gEQ==",
                            SecurityStamp = "0c10aa5a-d137-4db9-99f1-844903b20da9",
                            UserName = "JohnDoe25"
                        },
                        new
                        {
                            Id = "4679c7ad-a82c-4cff-ae95-fc1a9f3cc3aa",
                            ConcurrencyStamp = "37d476cc-48a3-461b-b591-708fd0e27839",
                            Email = "johndoe26@personal.gmail",
                            NormalizedEmail = "JOHNDOE26@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE26",
                            PasswordHash = "AQAAAAIAAYagAAAAEGCSpGZYZ6OFljApbdrglVYfWdCTAril8LLSAzq4S9MbYu5n07RLMIAqUfESRkPpYA==",
                            SecurityStamp = "c25ebbcd-479c-4e2e-9182-6cb77e628a82",
                            UserName = "JohnDoe26"
                        },
                        new
                        {
                            Id = "6aa769ad-610d-43e3-be3b-80d5fd905639",
                            ConcurrencyStamp = "18f581e9-4b8d-4964-aec5-df729c30c515",
                            Email = "johndoe27@personal.gmail",
                            NormalizedEmail = "JOHNDOE27@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE27",
                            PasswordHash = "AQAAAAIAAYagAAAAECsCPyVehI/Xd5YYyoxXs/04rxWL/xhCxpDnjGUuhL7htJ7lm/LekcFgDJSeBTHV3A==",
                            SecurityStamp = "e122e81c-e885-47a7-8215-8dba0e4fcf80",
                            UserName = "JohnDoe27"
                        },
                        new
                        {
                            Id = "c4da5967-ffd0-4d4d-97d7-5f498c1057df",
                            ConcurrencyStamp = "be823d3a-c245-497e-b87d-3a65dd3bc5b7",
                            Email = "johndoe28@personal.gmail",
                            NormalizedEmail = "JOHNDOE28@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE28",
                            PasswordHash = "AQAAAAIAAYagAAAAEAmq6fio15bT/qa0vKkItgoDFHKJQLbpBFJCtHsSWnGfiKH2rix6jfNz4dHEL75kWw==",
                            SecurityStamp = "e777e8d9-3839-4204-9d0e-7ce0fc2b0c4f",
                            UserName = "JohnDoe28"
                        },
                        new
                        {
                            Id = "4d9edf85-1092-4aff-a502-03a110413a79",
                            ConcurrencyStamp = "97c55825-ab89-470f-bf93-c293e34c41d9",
                            Email = "johndoe29@personal.gmail",
                            NormalizedEmail = "JOHNDOE29@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE29",
                            PasswordHash = "AQAAAAIAAYagAAAAEBoAhH2nYxpie9KTOpO39tiF9BqJ+CaWC/x967QCnB9c2GpUhks2Nfa5dr9/n9LzmA==",
                            SecurityStamp = "f9e1240d-fbfd-496a-8c4e-2e26d5dc2165",
                            UserName = "JohnDoe29"
                        },
                        new
                        {
                            Id = "59bbdfb1-0b27-4e75-9003-24858abb3d6e",
                            ConcurrencyStamp = "eaa44b5e-2230-4011-b6ff-da7c4939e081",
                            Email = "johndoe30@personal.gmail",
                            NormalizedEmail = "JOHNDOE30@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE30",
                            PasswordHash = "AQAAAAIAAYagAAAAEEWsrG4bRbUH5/xvjkthmbHwcIEwEdELqYdxYQh7ts22d6SZue7Yqmo590MaLJ0JlQ==",
                            SecurityStamp = "e4ae51af-b674-46b8-bc38-3d1a317c3e42",
                            UserName = "JohnDoe30"
                        },
                        new
                        {
                            Id = "f06c0527-9ef9-484d-90ec-50f79d239319",
                            ConcurrencyStamp = "e4de4e49-a054-40d0-af25-92408ec9dca4",
                            Email = "johndoe31@personal.gmail",
                            NormalizedEmail = "JOHNDOE31@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE31",
                            PasswordHash = "AQAAAAIAAYagAAAAEDQN7yGtE8jjiPya3F6b4LI7shmRjGTjj33LTs/V/APDeGpipNduHvZ+tV5R2EiC1g==",
                            SecurityStamp = "6b8ff663-1976-477a-9882-b9055498aa7e",
                            UserName = "JohnDoe31"
                        },
                        new
                        {
                            Id = "3c2a878e-948e-4ed8-9e92-b1a7178e8be0",
                            ConcurrencyStamp = "e6650a47-90a4-4e67-a6ad-d41ae0fa8983",
                            Email = "johndoe32@personal.gmail",
                            NormalizedEmail = "JOHNDOE32@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE32",
                            PasswordHash = "AQAAAAIAAYagAAAAEH5yNKRDjRXxjIW/SK+P/5sjOEcb2cGK5iv/yk8qJPIT/D10PSybO0WofqI+3P9XBQ==",
                            SecurityStamp = "dd973166-f6be-4785-96e5-8ebc7c8fcde4",
                            UserName = "JohnDoe32"
                        },
                        new
                        {
                            Id = "76aee70a-d812-460b-962f-3179337de576",
                            ConcurrencyStamp = "bdc828cb-6a71-46db-9ff0-a4590ba3b33f",
                            Email = "johndoe33@personal.gmail",
                            NormalizedEmail = "JOHNDOE33@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE33",
                            PasswordHash = "AQAAAAIAAYagAAAAEJDtbh75Qp0D4NgzERneb9GyLWJvDf9IDXjwfEPz+Tqo43nUpP5VCVEvdLUDv5gRTA==",
                            SecurityStamp = "5457eedf-6620-4649-ad4b-99a3e77cd182",
                            UserName = "JohnDoe33"
                        },
                        new
                        {
                            Id = "9442cbef-8313-4f5c-bdc3-ec7e9482191a",
                            ConcurrencyStamp = "bdfc906f-1c53-4134-a698-4c2acafff1d1",
                            Email = "johndoe34@personal.gmail",
                            NormalizedEmail = "JOHNDOE34@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE34",
                            PasswordHash = "AQAAAAIAAYagAAAAEK2sd/N4ppjLvqmEY3hbkE1KAizzrYNlPfvIZvOs8W//+BJTSFd0E/ctk/GM39WZ7A==",
                            SecurityStamp = "6fe30343-73a5-43a2-aa9d-e6dfb3c1c9a2",
                            UserName = "JohnDoe34"
                        },
                        new
                        {
                            Id = "2ff08c27-0d22-48e6-b4dd-e1bd276102e3",
                            ConcurrencyStamp = "25b5614b-ee57-4244-b529-b17f9f903ed0",
                            Email = "johndoe35@personal.gmail",
                            NormalizedEmail = "JOHNDOE35@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE35",
                            PasswordHash = "AQAAAAIAAYagAAAAELEfAU4b+obHQnPug2uGhF4R4rIj+E5tqWGNtEVEhydpuwdd1D+vOjS2dN6Nji/5qA==",
                            SecurityStamp = "7b57d3c5-6253-42dd-a129-be1178de7999",
                            UserName = "JohnDoe35"
                        },
                        new
                        {
                            Id = "d66ce665-f7b6-4a29-80d0-2d796ecd854f",
                            ConcurrencyStamp = "1f58cfd2-f6ad-4737-a68c-e210c0d50d07",
                            Email = "johndoe36@personal.gmail",
                            NormalizedEmail = "JOHNDOE36@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE36",
                            PasswordHash = "AQAAAAIAAYagAAAAEM06jxe3gOtpVkr4ZkL4p2b/wrvKiofO7MOyH8oCXNhF7LzMftW4RHyydcZS+6Q/5g==",
                            SecurityStamp = "23d20a39-ec54-4010-a7aa-5e6500740699",
                            UserName = "JohnDoe36"
                        },
                        new
                        {
                            Id = "2d774fb2-742c-43d7-b578-88d2f37fb5ec",
                            ConcurrencyStamp = "df00db14-b4d9-4d23-b4a8-a1af9e56132d",
                            Email = "johndoe37@personal.gmail",
                            NormalizedEmail = "JOHNDOE37@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE37",
                            PasswordHash = "AQAAAAIAAYagAAAAEGPxQvbv1tTFc+PIchFPM77iRKU6EhwK7CJnwr1iij9zab/MCIzy6gfw91nEs8Yk9g==",
                            SecurityStamp = "7f708231-5e12-48c5-b8eb-d17c9c31b111",
                            UserName = "JohnDoe37"
                        },
                        new
                        {
                            Id = "da53eab8-d2e7-410c-bae0-a50bff9de255",
                            ConcurrencyStamp = "14beb5cb-58c8-4dc5-8751-f79400def71a",
                            Email = "johndoe38@personal.gmail",
                            NormalizedEmail = "JOHNDOE38@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE38",
                            PasswordHash = "AQAAAAIAAYagAAAAEGGSo99RsyCffd1uXXwZ/fDNqy1PviivvxF//2x/+mGyhd7/F6bViE0A+ID9N9KXiw==",
                            SecurityStamp = "79b1628f-631d-41fe-8c69-6ecf2d4bdaa1",
                            UserName = "JohnDoe38"
                        },
                        new
                        {
                            Id = "d7d9235e-ab6f-4740-b093-5438ebce3efb",
                            ConcurrencyStamp = "ddd79e80-c237-4c76-a0ed-48a347278a0c",
                            Email = "johndoe39@personal.gmail",
                            NormalizedEmail = "JOHNDOE39@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE39",
                            PasswordHash = "AQAAAAIAAYagAAAAEMkb2omP3pvZBjeyyrKKbDlOZvilknNeuYVZor2IoXcKhQb2BhHXlPSEcLQyc/Kcuw==",
                            SecurityStamp = "4f07878c-bee8-4c57-99ee-033595bb0a46",
                            UserName = "JohnDoe39"
                        },
                        new
                        {
                            Id = "63e8c216-3c5c-45ef-a265-090733151f9c",
                            ConcurrencyStamp = "f55e62d7-4699-475a-978d-b4855bc1dea6",
                            Email = "johndoe40@personal.gmail",
                            NormalizedEmail = "JOHNDOE40@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE40",
                            PasswordHash = "AQAAAAIAAYagAAAAEPb7FN6LN5SD5xcBHJrXdJwqP4rRu0DUEu3WDSBGEMarpJS0nPBx/f168e03XOlRDg==",
                            SecurityStamp = "1853c362-62c6-4997-a089-ed5bfc599c97",
                            UserName = "JohnDoe40"
                        },
                        new
                        {
                            Id = "95e3c6ad-1e46-408d-a06e-7a9144972d73",
                            ConcurrencyStamp = "82628aab-c380-430d-9889-08049c443be2",
                            Email = "johndoe41@personal.gmail",
                            NormalizedEmail = "JOHNDOE41@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE41",
                            PasswordHash = "AQAAAAIAAYagAAAAELbvFO2JqRs/XBnbiJfXFB33aCMVMhf+B6IQ00oNFta1Fnqr7ZSnAGA8oiQCEM6Epg==",
                            SecurityStamp = "6254ba8c-6b29-4862-8828-8c9227b2d8cc",
                            UserName = "JohnDoe41"
                        },
                        new
                        {
                            Id = "84fe5a16-7952-4e2b-a7be-ffebbaff78f3",
                            ConcurrencyStamp = "864a3412-6d16-4acd-a09e-2f147a19ecb7",
                            Email = "johndoe42@personal.gmail",
                            NormalizedEmail = "JOHNDOE42@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE42",
                            PasswordHash = "AQAAAAIAAYagAAAAEOsqHG5UXaf8ZScM4z1PipXMpSLQA0bZwqblNsuTA+XG73cvfsSgumr3hkZPnqRgYg==",
                            SecurityStamp = "47001eb1-a3d8-4f1c-aa92-e10a2f446f92",
                            UserName = "JohnDoe42"
                        },
                        new
                        {
                            Id = "7d0ff76a-2f55-4c82-a04f-84cfce96ed4f",
                            ConcurrencyStamp = "2b03772b-901d-4e32-815b-9cadf1966c63",
                            Email = "johndoe43@personal.gmail",
                            NormalizedEmail = "JOHNDOE43@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE43",
                            PasswordHash = "AQAAAAIAAYagAAAAENxlSoBoqMsvtQ61cPaz6v1IsmEVa8b8ORreXacAr8moQ35BJhGcTBzwfsAPl8KkKw==",
                            SecurityStamp = "21964689-2c4e-4912-b29b-8eab559467cd",
                            UserName = "JohnDoe43"
                        },
                        new
                        {
                            Id = "d875b7ad-53ac-42e0-8489-e356650b4ac1",
                            ConcurrencyStamp = "0d8f0c09-19a6-4f1a-8b9f-94a87125445d",
                            Email = "johndoe44@personal.gmail",
                            NormalizedEmail = "JOHNDOE44@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE44",
                            PasswordHash = "AQAAAAIAAYagAAAAEIx0CbTkwxh8eIHhPxjZaSkBzwzJwtulWEf39Z8CQZxchWvopMrdPHu0ahNsDlXL9A==",
                            SecurityStamp = "c24c4f20-e2ac-4e49-b7c2-9f67207a140a",
                            UserName = "JohnDoe44"
                        },
                        new
                        {
                            Id = "5fb73638-24a3-4bb7-936f-79f116a9bf44",
                            ConcurrencyStamp = "23fc6ffd-bdcc-448a-9e7d-d65d7380110f",
                            Email = "johndoe45@personal.gmail",
                            NormalizedEmail = "JOHNDOE45@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE45",
                            PasswordHash = "AQAAAAIAAYagAAAAEPq1vTBP55Le0OxhSTsgD6/3N6cBix6zovCrEWW2vwofXkLzVmFrdK0CopCG77IwBg==",
                            SecurityStamp = "8ec602dd-a49e-4468-9068-d6df2e1f71e2",
                            UserName = "JohnDoe45"
                        },
                        new
                        {
                            Id = "89e49308-3a6d-44ac-bbd1-c55b06e3dd54",
                            ConcurrencyStamp = "b33c68c1-d64e-4dc8-89c6-bcfcb0c0e092",
                            Email = "johndoe46@personal.gmail",
                            NormalizedEmail = "JOHNDOE46@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE46",
                            PasswordHash = "AQAAAAIAAYagAAAAEB3p8jzpeEsCizufPiYq0NZNyemzPFcGKN/dI4P/Q4S5UxUDkycymMwyndNRUGFPeQ==",
                            SecurityStamp = "cb607695-740d-4b0b-9783-f15e3c06203c",
                            UserName = "JohnDoe46"
                        },
                        new
                        {
                            Id = "3747c1d4-72f6-4c55-a999-84270f0e8f97",
                            ConcurrencyStamp = "65b7dff1-044a-458d-a9e0-2434504d4f21",
                            Email = "johndoe47@personal.gmail",
                            NormalizedEmail = "JOHNDOE47@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE47",
                            PasswordHash = "AQAAAAIAAYagAAAAEIdHhU+s0U2YTcIKop0P5dzKSKBNKl5xxQBY1hyhr2M+TT4FfVKSTTGeEi1PHaoZ/g==",
                            SecurityStamp = "36ebed45-0af9-4b83-a427-525a53155da9",
                            UserName = "JohnDoe47"
                        },
                        new
                        {
                            Id = "cf367814-aee3-446a-b361-cd5f8ca9394c",
                            ConcurrencyStamp = "5123a8d0-99b3-436c-bb78-2e8ca9067e70",
                            Email = "johndoe48@personal.gmail",
                            NormalizedEmail = "JOHNDOE48@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE48",
                            PasswordHash = "AQAAAAIAAYagAAAAEJSyBcBj6K3eBbOILAgOty8PXx8HN2WtyHJO9NKVviyXAqIpEE4fvIpM7T3TXaPZNQ==",
                            SecurityStamp = "c804c559-4600-44a4-af6c-8f6854160662",
                            UserName = "JohnDoe48"
                        },
                        new
                        {
                            Id = "d993c0b3-4042-4fee-b72b-8164e6b2b488",
                            ConcurrencyStamp = "7fc06dd8-8361-4e35-9074-19e13d1d50ec",
                            Email = "johndoe49@personal.gmail",
                            NormalizedEmail = "JOHNDOE49@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE49",
                            PasswordHash = "AQAAAAIAAYagAAAAENeenMXbpQQuzPbnjN1RVJRMJF4ecRi9rFotDftYFTrmzNuJhn/59Rk4aAe9iEZ5mg==",
                            SecurityStamp = "91d5b291-6b92-4c6d-a66c-224b25af977b",
                            UserName = "JohnDoe49"
                        },
                        new
                        {
                            Id = "e8c9ba69-d160-4d6e-bf0c-0ed612357a15",
                            ConcurrencyStamp = "ba88eae3-d9cf-452a-a443-3c46d713e1a6",
                            Email = "johndoe50@personal.gmail",
                            NormalizedEmail = "JOHNDOE50@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE50",
                            PasswordHash = "AQAAAAIAAYagAAAAEM1MOu1NoTfyMwbJLI/xSGe4iT+lzgHScwKtBSukeMVUlSOQEOGbAihPNTAaYfwNsA==",
                            SecurityStamp = "cef35a9a-0215-478b-b8a3-8cf8a738753b",
                            UserName = "JohnDoe50"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "johndoe1@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Finance Manager",
                            LastName = "Doe",
                            Salary = 3183.0m,
                            UserId = "84c9f667-1b92-4e71-bca0-ffbe2d448d77"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "johndoe2@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "IT Manager",
                            LastName = "Doe",
                            Salary = 6735.0m,
                            UserId = "8dad293a-e2da-43dc-b4aa-03b2b947c921"
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "johndoe3@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Manager",
                            LastName = "Doe",
                            Salary = 3196.5m,
                            UserId = "583b51c7-92ac-483d-817b-8f5e879347dd"
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "johndoe4@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Manager",
                            LastName = "Doe",
                            Salary = 5113.5m,
                            UserId = "fed6a67c-4e0b-430a-a1e7-12dec58a2c7f"
                        },
                        new
                        {
                            Id = 5,
                            CompanyEmail = "johndoe5@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Manager",
                            LastName = "Doe",
                            Salary = 4020.0m,
                            UserId = "16363638-ce9f-4c56-a071-8c8bb4dac1d4"
                        },
                        new
                        {
                            Id = 6,
                            CompanyEmail = "johndoe6@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Salary = 2487.0m,
                            UserId = "b8cab2d7-8a04-4a7f-83e8-5f6c8d683532"
                        },
                        new
                        {
                            Id = 7,
                            CompanyEmail = "johndoe7@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2100m,
                            UserId = "963f193f-d637-4298-b34e-50cd195e9ca0"
                        },
                        new
                        {
                            Id = 8,
                            CompanyEmail = "johndoe8@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4175m,
                            UserId = "008d35f8-df6d-4042-8a99-e9f785afab49"
                        },
                        new
                        {
                            Id = 9,
                            CompanyEmail = "johndoe9@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2121m,
                            UserId = "3a901c1f-4c78-4500-90e4-91be3686cc6d"
                        },
                        new
                        {
                            Id = 10,
                            CompanyEmail = "johndoe10@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 2673m,
                            UserId = "8a9ce2d8-f247-4faf-96df-311a461160e8"
                        },
                        new
                        {
                            Id = 11,
                            CompanyEmail = "johndoe11@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2503m,
                            UserId = "87bf58ea-f556-484f-a6a5-afd85779004d"
                        },
                        new
                        {
                            Id = 12,
                            CompanyEmail = "johndoe12@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1693m,
                            UserId = "e81725c0-99cd-40c0-a922-c6e472d026e2"
                        },
                        new
                        {
                            Id = 13,
                            CompanyEmail = "johndoe13@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2149m,
                            UserId = "3a5b3325-6e0b-413c-a00d-5e7370b8aabd"
                        },
                        new
                        {
                            Id = 14,
                            CompanyEmail = "johndoe14@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4261m,
                            UserId = "3909fecf-da7b-4121-9d46-c12af8c303d6"
                        },
                        new
                        {
                            Id = 15,
                            CompanyEmail = "johndoe15@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2182m,
                            UserId = "92f2ce89-f16d-4eda-a7a8-39e9de09ac88"
                        },
                        new
                        {
                            Id = 16,
                            CompanyEmail = "johndoe16@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 2769m,
                            UserId = "5577d2a8-529e-4b13-8745-a294d1adb44d"
                        },
                        new
                        {
                            Id = 17,
                            CompanyEmail = "johndoe17@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2937m,
                            UserId = "5ddb52bf-2fb1-4c49-8c2b-6db76ac38e8d"
                        },
                        new
                        {
                            Id = 18,
                            CompanyEmail = "johndoe18@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1558m,
                            UserId = "cb7b5ecd-3a09-4a3c-8be6-69394de9f7af"
                        },
                        new
                        {
                            Id = 19,
                            CompanyEmail = "johndoe19@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2117m,
                            UserId = "0491dece-792d-4ac5-8afc-37f791359c6b"
                        },
                        new
                        {
                            Id = 20,
                            CompanyEmail = "johndoe20@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4339m,
                            UserId = "6fabdf76-3369-43b6-8a57-6a45925c0977"
                        },
                        new
                        {
                            Id = 21,
                            CompanyEmail = "johndoe21@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2023m,
                            UserId = "d18f7900-09a2-4fe5-bbc6-28546370498b"
                        },
                        new
                        {
                            Id = 22,
                            CompanyEmail = "johndoe22@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 2736m,
                            UserId = "4d94921e-282f-49a3-ab6f-d5cca7ac33ed"
                        },
                        new
                        {
                            Id = 23,
                            CompanyEmail = "johndoe23@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Logistics Coordinator",
                            LastName = "Doe",
                            Salary = 2635m,
                            UserId = "f81818ee-6da0-4b7a-8e2e-7f52fca8415a"
                        },
                        new
                        {
                            Id = 24,
                            CompanyEmail = "johndoe24@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1627m,
                            UserId = "326c775f-bd4c-47f6-8362-d1434fa33d55"
                        },
                        new
                        {
                            Id = 25,
                            CompanyEmail = "johndoe25@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2170m,
                            UserId = "e7af04cd-637d-4d6b-a4c6-d5375823a78f"
                        },
                        new
                        {
                            Id = 26,
                            CompanyEmail = "johndoe26@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4793m,
                            UserId = "4679c7ad-a82c-4cff-ae95-fc1a9f3cc3aa"
                        },
                        new
                        {
                            Id = 27,
                            CompanyEmail = "johndoe27@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2123m,
                            UserId = "6aa769ad-610d-43e3-be3b-80d5fd905639"
                        },
                        new
                        {
                            Id = 28,
                            CompanyEmail = "johndoe28@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 2009m,
                            UserId = "c4da5967-ffd0-4d4d-97d7-5f498c1057df"
                        },
                        new
                        {
                            Id = 29,
                            CompanyEmail = "johndoe29@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Logistics Coordinator",
                            LastName = "Doe",
                            Salary = 2723m,
                            UserId = "4d9edf85-1092-4aff-a502-03a110413a79"
                        },
                        new
                        {
                            Id = 30,
                            CompanyEmail = "johndoe30@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1787m,
                            UserId = "59bbdfb1-0b27-4e75-9003-24858abb3d6e"
                        },
                        new
                        {
                            Id = 31,
                            CompanyEmail = "johndoe31@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2074m,
                            UserId = "f06c0527-9ef9-484d-90ec-50f79d239319"
                        },
                        new
                        {
                            Id = 32,
                            CompanyEmail = "johndoe32@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4710m,
                            UserId = "3c2a878e-948e-4ed8-9e92-b1a7178e8be0"
                        },
                        new
                        {
                            Id = 33,
                            CompanyEmail = "johndoe33@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2138m,
                            UserId = "76aee70a-d812-460b-962f-3179337de576"
                        },
                        new
                        {
                            Id = 34,
                            CompanyEmail = "johndoe34@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 4404m,
                            UserId = "9442cbef-8313-4f5c-bdc3-ec7e9482191a"
                        },
                        new
                        {
                            Id = 35,
                            CompanyEmail = "johndoe35@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2803m,
                            UserId = "2ff08c27-0d22-48e6-b4dd-e1bd276102e3"
                        },
                        new
                        {
                            Id = 36,
                            CompanyEmail = "johndoe36@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1559m,
                            UserId = "d66ce665-f7b6-4a29-80d0-2d796ecd854f"
                        },
                        new
                        {
                            Id = 37,
                            CompanyEmail = "johndoe37@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2000m,
                            UserId = "2d774fb2-742c-43d7-b578-88d2f37fb5ec"
                        },
                        new
                        {
                            Id = 38,
                            CompanyEmail = "johndoe38@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4309m,
                            UserId = "da53eab8-d2e7-410c-bae0-a50bff9de255"
                        },
                        new
                        {
                            Id = 39,
                            CompanyEmail = "johndoe39@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2065m,
                            UserId = "d7d9235e-ab6f-4740-b093-5438ebce3efb"
                        },
                        new
                        {
                            Id = 40,
                            CompanyEmail = "johndoe40@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 3196m,
                            UserId = "63e8c216-3c5c-45ef-a265-090733151f9c"
                        },
                        new
                        {
                            Id = 41,
                            CompanyEmail = "johndoe41@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2989m,
                            UserId = "95e3c6ad-1e46-408d-a06e-7a9144972d73"
                        },
                        new
                        {
                            Id = 42,
                            CompanyEmail = "johndoe42@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1737m,
                            UserId = "84fe5a16-7952-4e2b-a7be-ffebbaff78f3"
                        },
                        new
                        {
                            Id = 43,
                            CompanyEmail = "johndoe43@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2125m,
                            UserId = "7d0ff76a-2f55-4c82-a04f-84cfce96ed4f"
                        },
                        new
                        {
                            Id = 44,
                            CompanyEmail = "johndoe44@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4531m,
                            UserId = "d875b7ad-53ac-42e0-8489-e356650b4ac1"
                        },
                        new
                        {
                            Id = 45,
                            CompanyEmail = "johndoe45@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2157m,
                            UserId = "5fb73638-24a3-4bb7-936f-79f116a9bf44"
                        },
                        new
                        {
                            Id = 46,
                            CompanyEmail = "johndoe46@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 2574m,
                            UserId = "89e49308-3a6d-44ac-bbd1-c55b06e3dd54"
                        },
                        new
                        {
                            Id = 47,
                            CompanyEmail = "johndoe47@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2856m,
                            UserId = "3747c1d4-72f6-4c55-a999-84270f0e8f97"
                        },
                        new
                        {
                            Id = 48,
                            CompanyEmail = "johndoe48@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1511m,
                            UserId = "cf367814-aee3-446a-b361-cd5f8ca9394c"
                        },
                        new
                        {
                            Id = 49,
                            CompanyEmail = "johndoe49@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2061m,
                            UserId = "d993c0b3-4042-4fee-b72b-8164e6b2b488"
                        },
                        new
                        {
                            Id = 50,
                            CompanyEmail = "johndoe50@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4971m,
                            UserId = "e8c9ba69-d160-4d6e-bf0c-0ed612357a15"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "33fe3df2-a962-446a-900c-ad1117f02c5c",
                            Name = "HR Admin",
                            NormalizedName = "HR ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "421da85d-7540-4c3c-908d-aa8b14068629",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "909282f6-b652-44b4-ad0c-0ab610cd3f9c",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "84c9f667-1b92-4e71-bca0-ffbe2d448d77",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "8dad293a-e2da-43dc-b4aa-03b2b947c921",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "583b51c7-92ac-483d-817b-8f5e879347dd",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "fed6a67c-4e0b-430a-a1e7-12dec58a2c7f",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "16363638-ce9f-4c56-a071-8c8bb4dac1d4",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "b8cab2d7-8a04-4a7f-83e8-5f6c8d683532",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "963f193f-d637-4298-b34e-50cd195e9ca0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "008d35f8-df6d-4042-8a99-e9f785afab49",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3a901c1f-4c78-4500-90e4-91be3686cc6d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8a9ce2d8-f247-4faf-96df-311a461160e8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "87bf58ea-f556-484f-a6a5-afd85779004d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e81725c0-99cd-40c0-a922-c6e472d026e2",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "3a5b3325-6e0b-413c-a00d-5e7370b8aabd",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3909fecf-da7b-4121-9d46-c12af8c303d6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "92f2ce89-f16d-4eda-a7a8-39e9de09ac88",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5577d2a8-529e-4b13-8745-a294d1adb44d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5ddb52bf-2fb1-4c49-8c2b-6db76ac38e8d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "cb7b5ecd-3a09-4a3c-8be6-69394de9f7af",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "0491dece-792d-4ac5-8afc-37f791359c6b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6fabdf76-3369-43b6-8a57-6a45925c0977",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d18f7900-09a2-4fe5-bbc6-28546370498b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4d94921e-282f-49a3-ab6f-d5cca7ac33ed",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "f81818ee-6da0-4b7a-8e2e-7f52fca8415a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "326c775f-bd4c-47f6-8362-d1434fa33d55",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "e7af04cd-637d-4d6b-a4c6-d5375823a78f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4679c7ad-a82c-4cff-ae95-fc1a9f3cc3aa",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6aa769ad-610d-43e3-be3b-80d5fd905639",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "c4da5967-ffd0-4d4d-97d7-5f498c1057df",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4d9edf85-1092-4aff-a502-03a110413a79",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "59bbdfb1-0b27-4e75-9003-24858abb3d6e",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "f06c0527-9ef9-484d-90ec-50f79d239319",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3c2a878e-948e-4ed8-9e92-b1a7178e8be0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "76aee70a-d812-460b-962f-3179337de576",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9442cbef-8313-4f5c-bdc3-ec7e9482191a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2ff08c27-0d22-48e6-b4dd-e1bd276102e3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d66ce665-f7b6-4a29-80d0-2d796ecd854f",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2d774fb2-742c-43d7-b578-88d2f37fb5ec",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "da53eab8-d2e7-410c-bae0-a50bff9de255",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d7d9235e-ab6f-4740-b093-5438ebce3efb",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "63e8c216-3c5c-45ef-a265-090733151f9c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "95e3c6ad-1e46-408d-a06e-7a9144972d73",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "84fe5a16-7952-4e2b-a7be-ffebbaff78f3",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "7d0ff76a-2f55-4c82-a04f-84cfce96ed4f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d875b7ad-53ac-42e0-8489-e356650b4ac1",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5fb73638-24a3-4bb7-936f-79f116a9bf44",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "89e49308-3a6d-44ac-bbd1-c55b06e3dd54",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3747c1d4-72f6-4c55-a999-84270f0e8f97",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "cf367814-aee3-446a-b361-cd5f8ca9394c",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "d993c0b3-4042-4fee-b72b-8164e6b2b488",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e8c9ba69-d160-4d6e-bf0c-0ed612357a15",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HumanCapitalManagement.Data.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
