// <auto-generated />
using HumanCapitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanCapitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250717151325_SeedDb")]
    partial class SeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanCapitalManagement.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d0c6b2a5-8191-473e-bde4-cec7c1a4a865",
                            ConcurrencyStamp = "4254c049-1cbc-41e5-a9e5-7341edd0ddd0",
                            Email = "johndoe1@personal.gmail",
                            NormalizedEmail = "JOHNDOE1@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE1",
                            PasswordHash = "AQAAAAIAAYagAAAAENwGpHBHjr5c+56qCTNGRRFgoRj3tppNE/+0YcKv/R94Z9sdJdv5XuNZiyiPA27f/w==",
                            SecurityStamp = "15b3ddf0-7057-4931-a164-18ec0812c275",
                            UserName = "JohnDoe1"
                        },
                        new
                        {
                            Id = "77819772-2107-48c1-96b5-8f7ede009c39",
                            ConcurrencyStamp = "e1c5b6ce-11ea-4a25-b512-3eec2647fc24",
                            Email = "johndoe2@personal.gmail",
                            NormalizedEmail = "JOHNDOE2@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE2",
                            PasswordHash = "AQAAAAIAAYagAAAAEBZ/81Iu4PolQ5PQtHSQQHqQg5eZ7jMyMBDmWjdknAY7BnMtWUJ5j9yGpd6CA8rALg==",
                            SecurityStamp = "ddbf2730-4ace-4e2f-9884-9da7a2650a62",
                            UserName = "JohnDoe2"
                        },
                        new
                        {
                            Id = "8c0e8e33-afad-4e69-98c5-9f0cd07a0f9f",
                            ConcurrencyStamp = "7f7e0284-92d9-4bf0-bf97-021e842d84de",
                            Email = "johndoe3@personal.gmail",
                            NormalizedEmail = "JOHNDOE3@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE3",
                            PasswordHash = "AQAAAAIAAYagAAAAEOwj23o3+8vU/yCHqV3OTBIBwIvd24qosr1+T4dUooFf5rze/PdfQEn7ivw1MkVqFA==",
                            SecurityStamp = "3d47f35c-a7d1-4276-92ec-b01061e2d448",
                            UserName = "JohnDoe3"
                        },
                        new
                        {
                            Id = "b50189b2-1e85-476f-b43b-7be200eb5a40",
                            ConcurrencyStamp = "dbad5283-61ef-4a42-b304-b855a26589c2",
                            Email = "johndoe4@personal.gmail",
                            NormalizedEmail = "JOHNDOE4@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEHxZucVS6IkLNQiVKoLMwWfy2isoEuC9c5LAQZ/26GS2Wvh0vAClLqhcimTgnPIUCA==",
                            SecurityStamp = "28c54755-beab-4594-8172-9cc87fe8e45c",
                            UserName = "JohnDoe4"
                        },
                        new
                        {
                            Id = "040a0e5e-f7ce-4ded-af4b-f1b5e33aaf42",
                            ConcurrencyStamp = "839c2c62-4dc6-4960-bbd9-5c0b175be060",
                            Email = "johndoe5@personal.gmail",
                            NormalizedEmail = "JOHNDOE5@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE5",
                            PasswordHash = "AQAAAAIAAYagAAAAEPr5FUGgnqv4DxXjdVPsyMEEKLivuUaQjBu2ltndcflDbPnRhuUYUVOpY3lv350mtA==",
                            SecurityStamp = "90298aae-adc4-46c8-8fb4-3ea22fcc036b",
                            UserName = "JohnDoe5"
                        },
                        new
                        {
                            Id = "5a734a3e-8720-460f-86af-36e2a1018ba8",
                            ConcurrencyStamp = "c70bdfc8-ae5c-4db6-b3fb-85a4618c5e0e",
                            Email = "johndoe6@personal.gmail",
                            NormalizedEmail = "JOHNDOE6@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE6",
                            PasswordHash = "AQAAAAIAAYagAAAAEAd/7rBaQncD5wKt45qFC6c97HXEPjwiaQ4EKcUC0m43xHYpU2XcIi1vGKep5ZSo1A==",
                            SecurityStamp = "18173264-4db9-4457-9d5c-063e235bfacf",
                            UserName = "JohnDoe6"
                        },
                        new
                        {
                            Id = "026e3971-3780-4328-88c3-5c1bd38cd2c3",
                            ConcurrencyStamp = "23f53322-f17f-42a9-bba7-87f5d95cbc48",
                            Email = "johndoe7@personal.gmail",
                            NormalizedEmail = "JOHNDOE7@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE7",
                            PasswordHash = "AQAAAAIAAYagAAAAEGYzIk1AaR+Zki2319eu+cSz2siCzXtohtJEF6O6wMyG67NZZwYJ8VgVIqzQkhX9Fg==",
                            SecurityStamp = "21dbadfb-44c1-4f59-8447-a44ba7e3678f",
                            UserName = "JohnDoe7"
                        },
                        new
                        {
                            Id = "937b77b9-8940-41ef-ab75-8980498ad7de",
                            ConcurrencyStamp = "83212deb-0938-420b-a563-1cbaedf6d59d",
                            Email = "johndoe8@personal.gmail",
                            NormalizedEmail = "JOHNDOE8@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE8",
                            PasswordHash = "AQAAAAIAAYagAAAAEMxrSwZJYUhpeq3iK9Jbl6qOfkhUZfhX6ROBgUQDnDPikAQTycG4cnnCLeqI3Jsltg==",
                            SecurityStamp = "a0f0039b-a391-4b97-b4fa-e1ae3a6899d0",
                            UserName = "JohnDoe8"
                        },
                        new
                        {
                            Id = "f7f76ab7-9f72-4acc-af3b-b1e0dd52d8c2",
                            ConcurrencyStamp = "28fa30ed-86d2-4959-b377-710efb36698d",
                            Email = "johndoe9@personal.gmail",
                            NormalizedEmail = "JOHNDOE9@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE9",
                            PasswordHash = "AQAAAAIAAYagAAAAEHV9AUHy0dZPK9et8aeDNXi3g1XENBcD1uLN8VLl6459rIZgVEDVeT0MsPatnTWqjA==",
                            SecurityStamp = "142ec75d-0419-4edd-a7b3-fd7826990eef",
                            UserName = "JohnDoe9"
                        },
                        new
                        {
                            Id = "e188573e-fb64-4593-8ef4-d3d0071fc7e6",
                            ConcurrencyStamp = "918434e1-33e1-43f8-8386-d733c69e8ea6",
                            Email = "johndoe10@personal.gmail",
                            NormalizedEmail = "JOHNDOE10@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE10",
                            PasswordHash = "AQAAAAIAAYagAAAAEI6h7WdB8yq44eRqtglsSqliuwX+LRVndw2vbq6vbZmxQ/qX3gXDcqyC/ttKFmxbsQ==",
                            SecurityStamp = "c38023fe-cb7f-45e8-a1fb-2a50e59e99d4",
                            UserName = "JohnDoe10"
                        },
                        new
                        {
                            Id = "009458af-40c0-4a7c-9300-e47976528523",
                            ConcurrencyStamp = "2e3a4924-1338-4c53-816e-addb1ee3777c",
                            Email = "johndoe11@personal.gmail",
                            NormalizedEmail = "JOHNDOE11@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE11",
                            PasswordHash = "AQAAAAIAAYagAAAAEIWFQhI56XgBBuCgX0sLClOsnh5fTznOa6+97WsNSHkL15z/gPLK0OpX27Poc0ElPQ==",
                            SecurityStamp = "257abef1-303c-4fd6-b281-511aae7d406e",
                            UserName = "JohnDoe11"
                        },
                        new
                        {
                            Id = "1037430f-09d0-4d04-b069-90590151685e",
                            ConcurrencyStamp = "00d0388b-cc08-430c-b989-8969a312efa6",
                            Email = "johndoe12@personal.gmail",
                            NormalizedEmail = "JOHNDOE12@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE12",
                            PasswordHash = "AQAAAAIAAYagAAAAEBgVHCETk8xT9mSxSMceiaIpLhcEdpCZVjk4ARsxwWkW9pTYCfqmqR9Xq+zfMfMnRA==",
                            SecurityStamp = "a486004e-e3e3-49cb-9c17-7405e8b0b4ad",
                            UserName = "JohnDoe12"
                        },
                        new
                        {
                            Id = "e1822941-e544-4b87-8fb4-9c04bca75113",
                            ConcurrencyStamp = "fcd7bba8-dc60-4ba7-adce-86b413e437c3",
                            Email = "johndoe13@personal.gmail",
                            NormalizedEmail = "JOHNDOE13@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE13",
                            PasswordHash = "AQAAAAIAAYagAAAAEAKZdK7EyoTcC8LzpQmx64bE1brCmk5vOXLgRm7jNd5m7f/oyMOt/aN9naLvs4PP4w==",
                            SecurityStamp = "a37b7d15-a612-4c3e-9a2b-99c025d4bcc3",
                            UserName = "JohnDoe13"
                        },
                        new
                        {
                            Id = "26f8970b-4857-46f9-9389-2f71c21e9295",
                            ConcurrencyStamp = "0635a3f0-6cf2-41a7-8578-c6e899bdf6ac",
                            Email = "johndoe14@personal.gmail",
                            NormalizedEmail = "JOHNDOE14@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE14",
                            PasswordHash = "AQAAAAIAAYagAAAAECVcoO5CFpioUsVsIVIzPjRxMVJ8MYtAf2sIpp0nRMfLZ5FF5ggi/C5CQZfRBqfjBA==",
                            SecurityStamp = "7201aefc-028c-483b-aff6-61db7957b288",
                            UserName = "JohnDoe14"
                        },
                        new
                        {
                            Id = "aefcd97e-81f9-4305-a574-d9cfd5a29361",
                            ConcurrencyStamp = "1cb978e4-9110-4276-9bb4-480cb72dfbd2",
                            Email = "johndoe15@personal.gmail",
                            NormalizedEmail = "JOHNDOE15@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE15",
                            PasswordHash = "AQAAAAIAAYagAAAAEEOXoufl5QI1cZJmBDqiXx7EVKGWCTvU0SAok7UA1mj8unK+EPX/+AUANCLb4euzHw==",
                            SecurityStamp = "61c4e163-56f9-4c66-a998-9ab2c1f0eff0",
                            UserName = "JohnDoe15"
                        },
                        new
                        {
                            Id = "908fbda3-dce0-45ed-ac03-7148326006ee",
                            ConcurrencyStamp = "3d9d23be-195c-40c5-a6ab-bcea4de3349b",
                            Email = "johndoe16@personal.gmail",
                            NormalizedEmail = "JOHNDOE16@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE16",
                            PasswordHash = "AQAAAAIAAYagAAAAECYqMTk4Zr17+/h+dTDs8mLURU0LVVp8ODQXGEaMeygCFuLW8Unx3ETEnAjSkIPRNA==",
                            SecurityStamp = "b9673271-c09d-45cd-9902-2bd8ba7fdc76",
                            UserName = "JohnDoe16"
                        },
                        new
                        {
                            Id = "21eb63b8-0a3c-4887-8ea0-eaf7a11266ba",
                            ConcurrencyStamp = "4a62cc4a-ee4d-4ea1-ae33-21b303e2ba4d",
                            Email = "johndoe17@personal.gmail",
                            NormalizedEmail = "JOHNDOE17@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE17",
                            PasswordHash = "AQAAAAIAAYagAAAAEDNAyBM1f/wukFyYXIXCkEymj2KVpQVgnxoAxA5bbVDnaajW9YYrJNCq/WsTxuMIcA==",
                            SecurityStamp = "a6dfa18d-505e-4ee3-95fa-393c051fa68d",
                            UserName = "JohnDoe17"
                        },
                        new
                        {
                            Id = "7307b064-713d-4dee-8482-bc27678b7a00",
                            ConcurrencyStamp = "2d5975a9-ede8-4ad4-9e53-f4ff3e370068",
                            Email = "johndoe18@personal.gmail",
                            NormalizedEmail = "JOHNDOE18@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE18",
                            PasswordHash = "AQAAAAIAAYagAAAAECFO+q3KCPTenfqqCMrlLS4QE1UmQjnjA1jiS2dxae/dIJGmH6VrY9hcVy+Ajn0iKw==",
                            SecurityStamp = "e56d16b2-3a9e-46bc-9db0-92e47068dd5e",
                            UserName = "JohnDoe18"
                        },
                        new
                        {
                            Id = "13d86597-6417-426c-bb16-ac9e7f371728",
                            ConcurrencyStamp = "a9212ffa-4981-4a7a-aaf1-1a0410ea1413",
                            Email = "johndoe19@personal.gmail",
                            NormalizedEmail = "JOHNDOE19@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE19",
                            PasswordHash = "AQAAAAIAAYagAAAAEFbSaAwaf5F+S+c0j15Bpb3KdlnPEHUj3QEeWSsiSX+gLiTwSecr9Dgm6D9CXlFPSQ==",
                            SecurityStamp = "440c92b1-8f88-447d-aa4e-57ab11ba9a94",
                            UserName = "JohnDoe19"
                        },
                        new
                        {
                            Id = "e059c377-1e51-4c73-a867-38b7a9c0eec3",
                            ConcurrencyStamp = "1913c95e-2d2e-4023-bebe-bc8acbf64703",
                            Email = "johndoe20@personal.gmail",
                            NormalizedEmail = "JOHNDOE20@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE20",
                            PasswordHash = "AQAAAAIAAYagAAAAEBmI3g8a5AN/UfWB4g5OGHV9Zrwzjoh5AGV++9Hk987hXVKaQA30aqSg0Bjpy2pIUQ==",
                            SecurityStamp = "b1972935-db89-46d5-bfcc-854a79752a0b",
                            UserName = "JohnDoe20"
                        },
                        new
                        {
                            Id = "da8b00d6-c4a6-48f6-b97b-fe9a52586e5e",
                            ConcurrencyStamp = "62fa3b28-625f-4628-90db-c47f71dc7521",
                            Email = "johndoe21@personal.gmail",
                            NormalizedEmail = "JOHNDOE21@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE21",
                            PasswordHash = "AQAAAAIAAYagAAAAENYju82oQ+Kj3kos3ao9Pu9mhIUViRMcZZ/wUy9hJsJ+/2GmaVBf7YfqUx67ZfEjLw==",
                            SecurityStamp = "ae187493-2856-4f41-95e8-3d874f8ef0ee",
                            UserName = "JohnDoe21"
                        },
                        new
                        {
                            Id = "566260d5-ac1e-4afb-9c10-c3e200afa0f3",
                            ConcurrencyStamp = "081449bf-335e-41e7-a57c-92edd3d89bb7",
                            Email = "johndoe22@personal.gmail",
                            NormalizedEmail = "JOHNDOE22@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE22",
                            PasswordHash = "AQAAAAIAAYagAAAAENy0zyTirY+0Gd5dMXwVOj0RlI7TkgrG0i023nQVeol+Cn9w2ra9N3wbW9RtBeV7vQ==",
                            SecurityStamp = "8a6b30fe-3e32-4e64-918d-1c639f628643",
                            UserName = "JohnDoe22"
                        },
                        new
                        {
                            Id = "82327ea9-d4ce-40d4-a11e-19b037c8f615",
                            ConcurrencyStamp = "b03167a7-5327-48b8-a54c-8c6980e40cd4",
                            Email = "johndoe23@personal.gmail",
                            NormalizedEmail = "JOHNDOE23@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE23",
                            PasswordHash = "AQAAAAIAAYagAAAAEDZm0ghYDRoqvoIRvDlsn/5oaiCGBHyWtnGUL3u/D0vrOwiIGfLtov+mwTK0K1lMOQ==",
                            SecurityStamp = "9e26aaa7-3c9a-467f-b9c0-81bb93fb3705",
                            UserName = "JohnDoe23"
                        },
                        new
                        {
                            Id = "9614c9ac-3010-4737-92d9-eadf3c93cfea",
                            ConcurrencyStamp = "b9ca8716-d937-4558-b8d3-95bd831f3735",
                            Email = "johndoe24@personal.gmail",
                            NormalizedEmail = "JOHNDOE24@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE24",
                            PasswordHash = "AQAAAAIAAYagAAAAEGAzhVHMpF8rr2z5Ad92mGVGCVCATO/zDmQ5+D0dsyDKwptY4E21b0R+WXfKuDC00w==",
                            SecurityStamp = "4e404a6d-f565-4480-a238-68766f6d3c6f",
                            UserName = "JohnDoe24"
                        },
                        new
                        {
                            Id = "2bad1a92-a028-4688-93ba-299295a9aa76",
                            ConcurrencyStamp = "ec45e964-ddc8-4300-9602-1b7d1e7ffb49",
                            Email = "johndoe25@personal.gmail",
                            NormalizedEmail = "JOHNDOE25@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE25",
                            PasswordHash = "AQAAAAIAAYagAAAAEHSzR2t5zpONw5JQmkgHiUwctEYJFEvYh6xE22OnWY1r/PccbVOOpaKswqzJebCyvQ==",
                            SecurityStamp = "4bfc0cbe-659f-41b9-9d04-86654d87ae34",
                            UserName = "JohnDoe25"
                        },
                        new
                        {
                            Id = "6222a67e-989f-4d70-a857-495a3fcfdfb3",
                            ConcurrencyStamp = "c4319ca1-acc2-448b-9251-09668db264e3",
                            Email = "johndoe26@personal.gmail",
                            NormalizedEmail = "JOHNDOE26@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE26",
                            PasswordHash = "AQAAAAIAAYagAAAAEMUPhKTOjpsfqs8w8QoelR3xAnjXuLiF8P2FSGq6hwwO0mGW201B7IQMO23njEy/Gg==",
                            SecurityStamp = "aa548955-90f0-4b58-bbe8-badf7dc029c2",
                            UserName = "JohnDoe26"
                        },
                        new
                        {
                            Id = "89589b78-3cfc-420c-b159-44d7bc15737b",
                            ConcurrencyStamp = "1f8bd987-02d0-487f-ba6f-9b7b36c7b740",
                            Email = "johndoe27@personal.gmail",
                            NormalizedEmail = "JOHNDOE27@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE27",
                            PasswordHash = "AQAAAAIAAYagAAAAEGqmxg0D4XIMgHhjZEOeDmZ915FQsyCgum4/RY+PTbx9Mm+kX054iEJ2pyEk6QTolw==",
                            SecurityStamp = "8f12689c-065a-4230-92db-b2b661b34c46",
                            UserName = "JohnDoe27"
                        },
                        new
                        {
                            Id = "c35f3a93-ebe3-447d-b4a5-c1c713060f69",
                            ConcurrencyStamp = "d988e3cc-cd75-4685-90cd-140bcf529ec9",
                            Email = "johndoe28@personal.gmail",
                            NormalizedEmail = "JOHNDOE28@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE28",
                            PasswordHash = "AQAAAAIAAYagAAAAEE/omMNFVPfGbnGKhyWZxQBSfcduyJHGcoPoYK1ZgNqK0Gyx8faMaEvPtptZjFVVDA==",
                            SecurityStamp = "0ae42760-311a-427c-994b-9eb55f3e9126",
                            UserName = "JohnDoe28"
                        },
                        new
                        {
                            Id = "ad3601d2-3a37-48a7-85a3-81b3ff26dfd0",
                            ConcurrencyStamp = "b3abf00f-bad5-4088-a37d-15736186255a",
                            Email = "johndoe29@personal.gmail",
                            NormalizedEmail = "JOHNDOE29@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE29",
                            PasswordHash = "AQAAAAIAAYagAAAAEGW2huLF3rSC5SayhUkYgUhN9YMHqOilfLx8bnV6FXD69Q3prH70qW4FYJhnX+5Cqg==",
                            SecurityStamp = "add49d22-feb5-44a3-80e8-f389495ccb4e",
                            UserName = "JohnDoe29"
                        },
                        new
                        {
                            Id = "0e251df9-cbdb-4da3-81b1-397386effd8d",
                            ConcurrencyStamp = "b57159a0-c0d8-424e-bc13-35e0d89350e8",
                            Email = "johndoe30@personal.gmail",
                            NormalizedEmail = "JOHNDOE30@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE30",
                            PasswordHash = "AQAAAAIAAYagAAAAEIQBq58LaYu/iY/qJ42U9thpzr9nPiE1ulmA8uGM9P3kAIiXkAYb7O2N2i5j3CcTQg==",
                            SecurityStamp = "95fd1af9-2055-46c1-97e7-8571da793722",
                            UserName = "JohnDoe30"
                        },
                        new
                        {
                            Id = "8c920c04-89e1-46c3-8b52-dee3b528f6f7",
                            ConcurrencyStamp = "5bde3c41-cceb-4b47-b0bb-6256079e37ba",
                            Email = "johndoe31@personal.gmail",
                            NormalizedEmail = "JOHNDOE31@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE31",
                            PasswordHash = "AQAAAAIAAYagAAAAEGhweHosxyh4Q7KEaL3lOoNsVSywvpd6AefYZBTTYF/Y9EIE5olXlsjjfA1zOZzthQ==",
                            SecurityStamp = "7897963d-77b3-4bb3-83f0-4731e6deae2b",
                            UserName = "JohnDoe31"
                        },
                        new
                        {
                            Id = "7f7c54d1-de99-47c1-99dc-0a0ab74a9ea8",
                            ConcurrencyStamp = "44e58c36-b6a6-4955-97b9-61642192ff8b",
                            Email = "johndoe32@personal.gmail",
                            NormalizedEmail = "JOHNDOE32@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE32",
                            PasswordHash = "AQAAAAIAAYagAAAAEDu7ivHuTreAu0VCbUelNCbIiDSeAZVH1sxuVoICtuwZ8JwYBn4nJjGp1GddSYxGjA==",
                            SecurityStamp = "af3d07e2-e14e-48da-9def-f15beb0cead9",
                            UserName = "JohnDoe32"
                        },
                        new
                        {
                            Id = "2bda7639-9d19-49a6-a570-19d578f4389a",
                            ConcurrencyStamp = "9d2eaa1a-ba07-4227-b658-5f191db1e68d",
                            Email = "johndoe33@personal.gmail",
                            NormalizedEmail = "JOHNDOE33@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE33",
                            PasswordHash = "AQAAAAIAAYagAAAAELdkgohbW69jP+NIIVoPlBiriSRtcazoRzMZFOtogjwk+fWttZZJ98nq7Tu9K9/5iQ==",
                            SecurityStamp = "fdb51d0e-569d-4309-a58e-a48d19331005",
                            UserName = "JohnDoe33"
                        },
                        new
                        {
                            Id = "1ba06199-67e8-4577-bc94-acace488ad33",
                            ConcurrencyStamp = "d0bdaabe-8148-4416-929f-ce6381281ad4",
                            Email = "johndoe34@personal.gmail",
                            NormalizedEmail = "JOHNDOE34@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE34",
                            PasswordHash = "AQAAAAIAAYagAAAAECCzUYeVbwMDbEKbCxBUcC43KwxEGH6sOs16RdBBdKIlJ0VNQBCVtpL8a+r+jLRlVg==",
                            SecurityStamp = "c602f8e8-30d9-4315-a9bb-fb71ba41c9bd",
                            UserName = "JohnDoe34"
                        },
                        new
                        {
                            Id = "c8356b13-720b-4b43-a1a4-86688b7cc726",
                            ConcurrencyStamp = "ddca7a4f-8048-450a-b165-837b82c42abf",
                            Email = "johndoe35@personal.gmail",
                            NormalizedEmail = "JOHNDOE35@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE35",
                            PasswordHash = "AQAAAAIAAYagAAAAELy/X/OX/hsw9ggLpgtJBxoQcQvAj1Yx6su1rUipc8OOX2ybwaaS2Im3o9SOnbinAw==",
                            SecurityStamp = "0a865ce4-a5d7-472e-b789-f925bee35d49",
                            UserName = "JohnDoe35"
                        },
                        new
                        {
                            Id = "cd46004a-3500-4029-8fc4-c42cda168214",
                            ConcurrencyStamp = "44cabd9c-8401-4d26-b68a-2dffcafd5aa6",
                            Email = "johndoe36@personal.gmail",
                            NormalizedEmail = "JOHNDOE36@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE36",
                            PasswordHash = "AQAAAAIAAYagAAAAEBjMCqY9zc8bwq7DIyeBPVmTFM9Odaq0IOz/0WkKAGrphYVXNZZug+W8+DY+MBG+uA==",
                            SecurityStamp = "5d47be9f-87cb-4d09-894c-a3595087c51c",
                            UserName = "JohnDoe36"
                        },
                        new
                        {
                            Id = "42190612-182a-4a7a-a06a-4bf0d43498c7",
                            ConcurrencyStamp = "42e78e19-36f2-417b-8e36-5b741e9134de",
                            Email = "johndoe37@personal.gmail",
                            NormalizedEmail = "JOHNDOE37@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE37",
                            PasswordHash = "AQAAAAIAAYagAAAAEM18pAAHp3PTdZg3gZAPD5ExJVzFP6sWPiipyvlFNip/05Q1x0IoW3dCCmmCS79ZiA==",
                            SecurityStamp = "a5d1140c-8de0-46bd-8c2c-c89b503a45a1",
                            UserName = "JohnDoe37"
                        },
                        new
                        {
                            Id = "57387e9a-9a9d-448b-a646-972a2517584b",
                            ConcurrencyStamp = "a6845e29-67ff-4d7c-8e2e-ea18ac626f8a",
                            Email = "johndoe38@personal.gmail",
                            NormalizedEmail = "JOHNDOE38@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE38",
                            PasswordHash = "AQAAAAIAAYagAAAAED7qJnruo0ktKYMXX437VyRUqC/yZ1cnsJLuFAFRbHPOj47IkiJXsD1bU8WD5Y86Ug==",
                            SecurityStamp = "277ccf56-c4ce-480a-bbe6-49dc072cb112",
                            UserName = "JohnDoe38"
                        },
                        new
                        {
                            Id = "0f5240c5-b7c9-4c22-b4b8-df9b5d9c0a77",
                            ConcurrencyStamp = "e0855a2b-7e23-45cc-aab8-645e30b92c59",
                            Email = "johndoe39@personal.gmail",
                            NormalizedEmail = "JOHNDOE39@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE39",
                            PasswordHash = "AQAAAAIAAYagAAAAEAS7c+t6Oo2Q59L0or3ZANO0IhdJ9l8XwhpVPN0sPZ0bBnvCZGEP4GW4KoaSn35ItQ==",
                            SecurityStamp = "93683e31-700e-410a-9ca1-6a23f733d926",
                            UserName = "JohnDoe39"
                        },
                        new
                        {
                            Id = "ee32d4e5-bd77-4f96-8739-ee95fbc35969",
                            ConcurrencyStamp = "f25602b8-fac3-4b47-b2e2-d72af036fdb7",
                            Email = "johndoe40@personal.gmail",
                            NormalizedEmail = "JOHNDOE40@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE40",
                            PasswordHash = "AQAAAAIAAYagAAAAEMEdGhU/rok8TS38BIyuW2NJgoLX+5v9q9gIiF+G0lVNxow+wjcwaN7Th93nL8OHQQ==",
                            SecurityStamp = "a33d7a81-3392-4b1b-87a8-bf57ee24b0c2",
                            UserName = "JohnDoe40"
                        },
                        new
                        {
                            Id = "e5546bd2-c013-487e-bf37-ceafeafd4d1c",
                            ConcurrencyStamp = "d51cdeaf-4b7a-4609-ab30-7dc69e298f97",
                            Email = "johndoe41@personal.gmail",
                            NormalizedEmail = "JOHNDOE41@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE41",
                            PasswordHash = "AQAAAAIAAYagAAAAEAnYLgaSb2WhgOK124QCoMcH3fUabaV0bRK9Zk9l8oo+dwfjZClHpBac6//vFcfpvw==",
                            SecurityStamp = "03ef627f-a10a-4ccb-baac-a64367a31127",
                            UserName = "JohnDoe41"
                        },
                        new
                        {
                            Id = "fa89aa42-ec85-4e8c-91c1-eaea93b64ef4",
                            ConcurrencyStamp = "f44837d5-2d8f-42ea-bdd4-9612e18cbb9c",
                            Email = "johndoe42@personal.gmail",
                            NormalizedEmail = "JOHNDOE42@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE42",
                            PasswordHash = "AQAAAAIAAYagAAAAEDFAP2u/G6XkoXINwxp3eZVEcKW09c5gaLvD4jJ4N/IoZkicgZs6PJgydm1UU7LDYA==",
                            SecurityStamp = "45e22e56-3f38-4543-b065-5d64c1a78394",
                            UserName = "JohnDoe42"
                        },
                        new
                        {
                            Id = "8a386ecb-3e8e-413f-a520-c32d8f86d0b4",
                            ConcurrencyStamp = "1acf8005-8661-4aa7-aa9d-516080f9ccb7",
                            Email = "johndoe43@personal.gmail",
                            NormalizedEmail = "JOHNDOE43@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE43",
                            PasswordHash = "AQAAAAIAAYagAAAAEICcarmvwHTaXUncFyixdYpQdTHVnL3b9cXfnrJmSEOotIuRG7hZbbzy+arO4A9n/g==",
                            SecurityStamp = "9f642294-6d5b-48a5-8d8f-ab46f4c03ad8",
                            UserName = "JohnDoe43"
                        },
                        new
                        {
                            Id = "734ce118-ab9b-49c4-8467-992cd37a8f64",
                            ConcurrencyStamp = "b832d7ee-e93a-4ec7-9ce9-ca4e801a3bf4",
                            Email = "johndoe44@personal.gmail",
                            NormalizedEmail = "JOHNDOE44@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE44",
                            PasswordHash = "AQAAAAIAAYagAAAAEGXhIvon3bm6BBhwUvberLP+fCm++Bcj/+oT5RTrj72kU8WzzRuPv7ZNN/bRI7eI8w==",
                            SecurityStamp = "0a7f7f93-360a-48e9-b03e-059925d5cb8d",
                            UserName = "JohnDoe44"
                        },
                        new
                        {
                            Id = "fdb5ed59-7b70-4616-8869-ee5ca03cc20d",
                            ConcurrencyStamp = "1b0d9050-d124-4198-b962-15518cfc9a9d",
                            Email = "johndoe45@personal.gmail",
                            NormalizedEmail = "JOHNDOE45@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE45",
                            PasswordHash = "AQAAAAIAAYagAAAAECZzma6cTYXhzmU2EsxjvvlLR2E3yKg+hemLGPIBHHYU+Kb13VwTcF0ynOb2i+y/MA==",
                            SecurityStamp = "0ce7541b-ce80-4e2c-9294-024e35df5c7b",
                            UserName = "JohnDoe45"
                        },
                        new
                        {
                            Id = "ec8dc965-cf56-47b1-a2e5-2acb304aea6d",
                            ConcurrencyStamp = "eb097430-bf1b-48df-a134-e3aeae44bd38",
                            Email = "johndoe46@personal.gmail",
                            NormalizedEmail = "JOHNDOE46@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE46",
                            PasswordHash = "AQAAAAIAAYagAAAAEJeV5V3+GpCQCGe/bjLd6FUCKoXC9Ro7pyBr472NsLDsdIjdYiGGhDsdb0AXmX593Q==",
                            SecurityStamp = "c7f149cf-a7c8-4c0d-937d-5782b1dcebb8",
                            UserName = "JohnDoe46"
                        },
                        new
                        {
                            Id = "bdcceafd-4cd8-447f-a4e6-e2b60ab7641c",
                            ConcurrencyStamp = "3587e85f-6edb-47e0-9eb6-2c4e068e395d",
                            Email = "johndoe47@personal.gmail",
                            NormalizedEmail = "JOHNDOE47@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE47",
                            PasswordHash = "AQAAAAIAAYagAAAAEEj9WuQfHolTtU3vniMddAeug0PoBInv6fU4gDjGLDgPx7b570zUmnAtm6qKbdPVYg==",
                            SecurityStamp = "79d8ec7c-6717-460d-aefa-85e3ff5d0d34",
                            UserName = "JohnDoe47"
                        },
                        new
                        {
                            Id = "3a3b2773-5cc6-4ba8-903b-31b2cfaf006d",
                            ConcurrencyStamp = "2cf3689f-135f-41de-a620-4dfefcb190c0",
                            Email = "johndoe48@personal.gmail",
                            NormalizedEmail = "JOHNDOE48@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE48",
                            PasswordHash = "AQAAAAIAAYagAAAAEKbakZ3nnhcGAByoxlMnzEyTWB/EZtS5EI6Oz5IWTbKf3TGnUC4PobhhDbqU5fispg==",
                            SecurityStamp = "03397af5-175b-415c-a8ac-9b8987a1fc60",
                            UserName = "JohnDoe48"
                        },
                        new
                        {
                            Id = "b30a7b36-5516-48cc-9a0b-6cce3e0323af",
                            ConcurrencyStamp = "bd41c242-9d01-4131-9ce5-ca12bf258457",
                            Email = "johndoe49@personal.gmail",
                            NormalizedEmail = "JOHNDOE49@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE49",
                            PasswordHash = "AQAAAAIAAYagAAAAEKV5Hm3YpITryhQ836C+GhQ4Hx+ACFahejNbJWlkgJTyI//IilvIMRS2jW3dIpm7yA==",
                            SecurityStamp = "efe54817-97ab-4aac-baa4-75914e036766",
                            UserName = "JohnDoe49"
                        },
                        new
                        {
                            Id = "3cce224a-e144-4dcd-8256-63c7c40f44ef",
                            ConcurrencyStamp = "7db87307-d06b-4178-9b6b-ca22142b4442",
                            Email = "johndoe50@personal.gmail",
                            NormalizedEmail = "JOHNDOE50@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE50",
                            PasswordHash = "AQAAAAIAAYagAAAAEOXhAU74syTbRG4jVzwWDWY2cI3Oqn80yAQQ8X3cUpqEIfwpS0iEBXQT3zOeWdavuQ==",
                            SecurityStamp = "8c70dc9d-6384-49ae-bf8b-8495f82d871e",
                            UserName = "JohnDoe50"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "johndoe1@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Finance Manager",
                            LastName = "Doe",
                            Salary = 3121.5m,
                            UserId = "d0c6b2a5-8191-473e-bde4-cec7c1a4a865"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "johndoe2@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "IT Manager",
                            LastName = "Doe",
                            Salary = 6678.0m,
                            UserId = "77819772-2107-48c1-96b5-8f7ede009c39"
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "johndoe3@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Manager",
                            LastName = "Doe",
                            Salary = 3297.0m,
                            UserId = "8c0e8e33-afad-4e69-98c5-9f0cd07a0f9f"
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "johndoe4@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Manager",
                            LastName = "Doe",
                            Salary = 3988.5m,
                            UserId = "b50189b2-1e85-476f-b43b-7be200eb5a40"
                        },
                        new
                        {
                            Id = 5,
                            CompanyEmail = "johndoe5@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Manager",
                            LastName = "Doe",
                            Salary = 3766.5m,
                            UserId = "040a0e5e-f7ce-4ded-af4b-f1b5e33aaf42"
                        },
                        new
                        {
                            Id = 6,
                            CompanyEmail = "johndoe6@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Salary = 2620.5m,
                            UserId = "5a734a3e-8720-460f-86af-36e2a1018ba8"
                        },
                        new
                        {
                            Id = 7,
                            CompanyEmail = "johndoe7@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2069m,
                            UserId = "026e3971-3780-4328-88c3-5c1bd38cd2c3"
                        },
                        new
                        {
                            Id = 8,
                            CompanyEmail = "johndoe8@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4444m,
                            UserId = "937b77b9-8940-41ef-ab75-8980498ad7de"
                        },
                        new
                        {
                            Id = 9,
                            CompanyEmail = "johndoe9@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2131m,
                            UserId = "f7f76ab7-9f72-4acc-af3b-b1e0dd52d8c2"
                        },
                        new
                        {
                            Id = 10,
                            CompanyEmail = "johndoe10@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 2860m,
                            UserId = "e188573e-fb64-4593-8ef4-d3d0071fc7e6"
                        },
                        new
                        {
                            Id = 11,
                            CompanyEmail = "johndoe11@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2912m,
                            UserId = "009458af-40c0-4a7c-9300-e47976528523"
                        },
                        new
                        {
                            Id = 12,
                            CompanyEmail = "johndoe12@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1604m,
                            UserId = "1037430f-09d0-4d04-b069-90590151685e"
                        },
                        new
                        {
                            Id = 13,
                            CompanyEmail = "johndoe13@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2136m,
                            UserId = "e1822941-e544-4b87-8fb4-9c04bca75113"
                        },
                        new
                        {
                            Id = 14,
                            CompanyEmail = "johndoe14@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4559m,
                            UserId = "26f8970b-4857-46f9-9389-2f71c21e9295"
                        },
                        new
                        {
                            Id = 15,
                            CompanyEmail = "johndoe15@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2036m,
                            UserId = "aefcd97e-81f9-4305-a574-d9cfd5a29361"
                        },
                        new
                        {
                            Id = 16,
                            CompanyEmail = "johndoe16@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 2759m,
                            UserId = "908fbda3-dce0-45ed-ac03-7148326006ee"
                        },
                        new
                        {
                            Id = 17,
                            CompanyEmail = "johndoe17@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2536m,
                            UserId = "21eb63b8-0a3c-4887-8ea0-eaf7a11266ba"
                        },
                        new
                        {
                            Id = 18,
                            CompanyEmail = "johndoe18@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1636m,
                            UserId = "7307b064-713d-4dee-8482-bc27678b7a00"
                        },
                        new
                        {
                            Id = 19,
                            CompanyEmail = "johndoe19@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2031m,
                            UserId = "13d86597-6417-426c-bb16-ac9e7f371728"
                        },
                        new
                        {
                            Id = 20,
                            CompanyEmail = "johndoe20@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4411m,
                            UserId = "e059c377-1e51-4c73-a867-38b7a9c0eec3"
                        },
                        new
                        {
                            Id = 21,
                            CompanyEmail = "johndoe21@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2163m,
                            UserId = "da8b00d6-c4a6-48f6-b97b-fe9a52586e5e"
                        },
                        new
                        {
                            Id = 22,
                            CompanyEmail = "johndoe22@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 2597m,
                            UserId = "566260d5-ac1e-4afb-9c10-c3e200afa0f3"
                        },
                        new
                        {
                            Id = 23,
                            CompanyEmail = "johndoe23@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2812m,
                            UserId = "82327ea9-d4ce-40d4-a11e-19b037c8f615"
                        },
                        new
                        {
                            Id = 24,
                            CompanyEmail = "johndoe24@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1554m,
                            UserId = "9614c9ac-3010-4737-92d9-eadf3c93cfea"
                        },
                        new
                        {
                            Id = 25,
                            CompanyEmail = "johndoe25@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2107m,
                            UserId = "2bad1a92-a028-4688-93ba-299295a9aa76"
                        },
                        new
                        {
                            Id = 26,
                            CompanyEmail = "johndoe26@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4626m,
                            UserId = "6222a67e-989f-4d70-a857-495a3fcfdfb3"
                        },
                        new
                        {
                            Id = 27,
                            CompanyEmail = "johndoe27@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2138m,
                            UserId = "89589b78-3cfc-420c-b159-44d7bc15737b"
                        },
                        new
                        {
                            Id = 28,
                            CompanyEmail = "johndoe28@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 3789m,
                            UserId = "c35f3a93-ebe3-447d-b4a5-c1c713060f69"
                        },
                        new
                        {
                            Id = 29,
                            CompanyEmail = "johndoe29@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2655m,
                            UserId = "ad3601d2-3a37-48a7-85a3-81b3ff26dfd0"
                        },
                        new
                        {
                            Id = 30,
                            CompanyEmail = "johndoe30@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1644m,
                            UserId = "0e251df9-cbdb-4da3-81b1-397386effd8d"
                        },
                        new
                        {
                            Id = 31,
                            CompanyEmail = "johndoe31@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2060m,
                            UserId = "8c920c04-89e1-46c3-8b52-dee3b528f6f7"
                        },
                        new
                        {
                            Id = 32,
                            CompanyEmail = "johndoe32@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4554m,
                            UserId = "7f7c54d1-de99-47c1-99dc-0a0ab74a9ea8"
                        },
                        new
                        {
                            Id = 33,
                            CompanyEmail = "johndoe33@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2023m,
                            UserId = "2bda7639-9d19-49a6-a570-19d578f4389a"
                        },
                        new
                        {
                            Id = 34,
                            CompanyEmail = "johndoe34@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 2176m,
                            UserId = "1ba06199-67e8-4577-bc94-acace488ad33"
                        },
                        new
                        {
                            Id = 35,
                            CompanyEmail = "johndoe35@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2797m,
                            UserId = "c8356b13-720b-4b43-a1a4-86688b7cc726"
                        },
                        new
                        {
                            Id = 36,
                            CompanyEmail = "johndoe36@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1608m,
                            UserId = "cd46004a-3500-4029-8fc4-c42cda168214"
                        },
                        new
                        {
                            Id = 37,
                            CompanyEmail = "johndoe37@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2076m,
                            UserId = "42190612-182a-4a7a-a06a-4bf0d43498c7"
                        },
                        new
                        {
                            Id = 38,
                            CompanyEmail = "johndoe38@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4814m,
                            UserId = "57387e9a-9a9d-448b-a646-972a2517584b"
                        },
                        new
                        {
                            Id = 39,
                            CompanyEmail = "johndoe39@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2109m,
                            UserId = "0f5240c5-b7c9-4c22-b4b8-df9b5d9c0a77"
                        },
                        new
                        {
                            Id = 40,
                            CompanyEmail = "johndoe40@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 3870m,
                            UserId = "ee32d4e5-bd77-4f96-8739-ee95fbc35969"
                        },
                        new
                        {
                            Id = 41,
                            CompanyEmail = "johndoe41@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2724m,
                            UserId = "e5546bd2-c013-487e-bf37-ceafeafd4d1c"
                        },
                        new
                        {
                            Id = 42,
                            CompanyEmail = "johndoe42@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1609m,
                            UserId = "fa89aa42-ec85-4e8c-91c1-eaea93b64ef4"
                        },
                        new
                        {
                            Id = 43,
                            CompanyEmail = "johndoe43@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2189m,
                            UserId = "8a386ecb-3e8e-413f-a520-c32d8f86d0b4"
                        },
                        new
                        {
                            Id = 44,
                            CompanyEmail = "johndoe44@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4981m,
                            UserId = "734ce118-ab9b-49c4-8467-992cd37a8f64"
                        },
                        new
                        {
                            Id = 45,
                            CompanyEmail = "johndoe45@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2176m,
                            UserId = "fdb5ed59-7b70-4616-8869-ee5ca03cc20d"
                        },
                        new
                        {
                            Id = 46,
                            CompanyEmail = "johndoe46@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 4010m,
                            UserId = "ec8dc965-cf56-47b1-a2e5-2acb304aea6d"
                        },
                        new
                        {
                            Id = 47,
                            CompanyEmail = "johndoe47@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2602m,
                            UserId = "bdcceafd-4cd8-447f-a4e6-e2b60ab7641c"
                        },
                        new
                        {
                            Id = 48,
                            CompanyEmail = "johndoe48@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1642m,
                            UserId = "3a3b2773-5cc6-4ba8-903b-31b2cfaf006d"
                        },
                        new
                        {
                            Id = 49,
                            CompanyEmail = "johndoe49@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2156m,
                            UserId = "b30a7b36-5516-48cc-9a0b-6cce3e0323af"
                        },
                        new
                        {
                            Id = 50,
                            CompanyEmail = "johndoe50@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4265m,
                            UserId = "3cce224a-e144-4dcd-8256-63c7c40f44ef"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "5aac5564-86db-4233-98dc-34d335c6e444",
                            Name = "HR Admin",
                            NormalizedName = "HR ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "f742d469-60cc-4627-a553-4f6e407204e4",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "f2efefae-3150-42b5-9088-f62379b6a60b",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
