// <auto-generated />
using HumanCapitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanCapitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250717153237_AddedRoles")]
    partial class AddedRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanCapitalManagement.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "58181f28-91f9-4a64-a3df-ef909f046b33",
                            ConcurrencyStamp = "c81c37dd-7479-44f3-8075-be4535cf2e5c",
                            Email = "johndoe1@personal.gmail",
                            NormalizedEmail = "JOHNDOE1@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZY+PVZwk0U8/Ftp4vsNvxTI8AjnarQotQoaUJiVoeHG3IxFxE7pCEpJPYLLjI5kw==",
                            SecurityStamp = "85e366b2-9c7c-4151-836c-62a94cb17b9e",
                            UserName = "JohnDoe1"
                        },
                        new
                        {
                            Id = "3942c37e-14a6-4538-95f7-126dfeafc253",
                            ConcurrencyStamp = "7a3cf402-266f-4220-bd79-7f3bf8f065f8",
                            Email = "johndoe2@personal.gmail",
                            NormalizedEmail = "JOHNDOE2@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE2",
                            PasswordHash = "AQAAAAIAAYagAAAAEFtSsPKrSMIYS27HDvhW0mDaieLoveWwYhuocOGl4kqcxSagi34XGzT6cpaE+GdcFQ==",
                            SecurityStamp = "025ec64d-7978-46b7-8d9e-681c1f0c13d7",
                            UserName = "JohnDoe2"
                        },
                        new
                        {
                            Id = "50c9665c-8633-4c52-a072-bf10848ed658",
                            ConcurrencyStamp = "2d9dd2f0-327f-43e1-a436-6af46d5e9fa3",
                            Email = "johndoe3@personal.gmail",
                            NormalizedEmail = "JOHNDOE3@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE3",
                            PasswordHash = "AQAAAAIAAYagAAAAEIH/9JU3VyMzrayf6Z7LLYe6ceTDhQjVeOTQ1wWwFcUWHRDgl4Q2z4UL+5W/AB5Itw==",
                            SecurityStamp = "51b9fff2-dd89-4200-a84d-dd43130bb02d",
                            UserName = "JohnDoe3"
                        },
                        new
                        {
                            Id = "c63626b0-9fe9-4333-af7c-e763ad93ed38",
                            ConcurrencyStamp = "899c05af-333d-4bae-b589-d6830fe02dd9",
                            Email = "johndoe4@personal.gmail",
                            NormalizedEmail = "JOHNDOE4@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEERPwioCMQeBklbXnTBg0Eml1P4OBhOXXn6wux/VBbrqmXWax5KOy/KDPoVPb0gAkg==",
                            SecurityStamp = "611a49b3-cd0c-45f8-9335-1acde08224ec",
                            UserName = "JohnDoe4"
                        },
                        new
                        {
                            Id = "67db0983-40c0-449b-b077-544d4885abac",
                            ConcurrencyStamp = "ff3d8b52-f0b9-4f0a-bdd4-aa75752bb7aa",
                            Email = "johndoe5@personal.gmail",
                            NormalizedEmail = "JOHNDOE5@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE5",
                            PasswordHash = "AQAAAAIAAYagAAAAEB0riXLhJdW0yfnsDga1jU5L9SxSqxtPbSaphtnC3RIn2njpP6q8s0SadMP9oQ9JQg==",
                            SecurityStamp = "28df6871-ed92-4595-8675-5191aa001f18",
                            UserName = "JohnDoe5"
                        },
                        new
                        {
                            Id = "1ceabc7c-ba50-40d6-a0fe-8590d2dbb268",
                            ConcurrencyStamp = "cdb3b173-1dc5-409c-816a-c1442e5ac904",
                            Email = "johndoe6@personal.gmail",
                            NormalizedEmail = "JOHNDOE6@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE6",
                            PasswordHash = "AQAAAAIAAYagAAAAECRQVig5PLZCH5GdLgSR4DB0X6O7US59cvYz+4M0OId2F4inu/FakjJRA8LIy5eX/g==",
                            SecurityStamp = "b698ce78-c430-484e-8be1-edc69facb179",
                            UserName = "JohnDoe6"
                        },
                        new
                        {
                            Id = "d42868ec-505d-4c9c-83a6-4c10735fdb13",
                            ConcurrencyStamp = "493e1c87-c036-478c-901d-35f5e7cf8771",
                            Email = "johndoe7@personal.gmail",
                            NormalizedEmail = "JOHNDOE7@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE7",
                            PasswordHash = "AQAAAAIAAYagAAAAEFCp2JFNilSMKZ/EaIfBfjEJQ4Pdl65BcnxRNwXwmkT5i8PDmj8D+Hnl1o+o6yBgOA==",
                            SecurityStamp = "567c8ef7-2aec-4cd2-9513-da5dd82e7be8",
                            UserName = "JohnDoe7"
                        },
                        new
                        {
                            Id = "d5c0d689-46b4-46be-9a76-90cd6d6d18ad",
                            ConcurrencyStamp = "7f7ac8d8-1b67-4837-a350-33cb47dbcad4",
                            Email = "johndoe8@personal.gmail",
                            NormalizedEmail = "JOHNDOE8@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE8",
                            PasswordHash = "AQAAAAIAAYagAAAAEDeX7PurO/iEYoIFCKN/kDPP8PXBPaKLUJkbdM1RlsPFJ0Q2o5ooLuruWWSGIXqj6Q==",
                            SecurityStamp = "cc1c47ea-910c-4297-8bd1-4df837c7059b",
                            UserName = "JohnDoe8"
                        },
                        new
                        {
                            Id = "2bc94167-68da-4a53-914f-555414efc55f",
                            ConcurrencyStamp = "5acc0d5a-8927-42a4-b4d7-27045f32b751",
                            Email = "johndoe9@personal.gmail",
                            NormalizedEmail = "JOHNDOE9@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE9",
                            PasswordHash = "AQAAAAIAAYagAAAAEHeBV7STn/MnGh2hY+Z92uasy5tYksacx3lxlFqwOYGBucaj65KIk3i1ZpjtOt61Yw==",
                            SecurityStamp = "9df3055d-6983-427c-8769-afee020971bc",
                            UserName = "JohnDoe9"
                        },
                        new
                        {
                            Id = "dddd68cc-25bc-4b8d-a1f0-37a1a1229808",
                            ConcurrencyStamp = "8a6da0f3-e5a2-417e-89bf-bbc8ad0bd542",
                            Email = "johndoe10@personal.gmail",
                            NormalizedEmail = "JOHNDOE10@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE10",
                            PasswordHash = "AQAAAAIAAYagAAAAEMvVQZep8/3G7W0E192RKBl1qGPqlo9ceMyJig7hSqmsTOMLNXcctUxKV/hgOlMPsw==",
                            SecurityStamp = "8dc9500b-d544-4708-80f6-9bb4159710ad",
                            UserName = "JohnDoe10"
                        },
                        new
                        {
                            Id = "dcc38bd9-a063-4b5d-97e6-8620a437de02",
                            ConcurrencyStamp = "eb313c8c-6015-4ea1-b379-3a8bf9964243",
                            Email = "johndoe11@personal.gmail",
                            NormalizedEmail = "JOHNDOE11@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE11",
                            PasswordHash = "AQAAAAIAAYagAAAAEGGloPXB87JczP68870nGY6mg/DKAgUIOeqjj6ptL/oMbzFO1fU2N4y9bXPcpSGfow==",
                            SecurityStamp = "51ebeddd-5630-4071-9423-fb5e49b9e232",
                            UserName = "JohnDoe11"
                        },
                        new
                        {
                            Id = "3961334a-7c0b-43b0-a0b2-46f06eca7b31",
                            ConcurrencyStamp = "9ee87386-5c88-4645-b822-9f955f81ac3e",
                            Email = "johndoe12@personal.gmail",
                            NormalizedEmail = "JOHNDOE12@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE12",
                            PasswordHash = "AQAAAAIAAYagAAAAENSuMwVXUepT+1CmwToWK6j3tRzb0VIGDeDdNkMucxnL4A2G5ULbaUffO4NtbzIlzQ==",
                            SecurityStamp = "5080d6ab-7a83-4ed1-8b7a-c5b39f5fc3d1",
                            UserName = "JohnDoe12"
                        },
                        new
                        {
                            Id = "0a428d4b-58d2-47a5-b6de-6b2f3d88d847",
                            ConcurrencyStamp = "a6f5b789-47f0-437f-badc-ed906b588460",
                            Email = "johndoe13@personal.gmail",
                            NormalizedEmail = "JOHNDOE13@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE13",
                            PasswordHash = "AQAAAAIAAYagAAAAEJCPT09b3Q/zoqmHKrMierr97eIntjQ5OLIadneKhNd7y33n5ODLAtmN1+y6BSvT2g==",
                            SecurityStamp = "388e39e9-212d-4f77-8e01-5e20bf2ee15b",
                            UserName = "JohnDoe13"
                        },
                        new
                        {
                            Id = "440f9a76-0591-4e51-8eb6-50c1bf7bf1b7",
                            ConcurrencyStamp = "28dd1811-92de-4635-a657-c5bcb6ab39f6",
                            Email = "johndoe14@personal.gmail",
                            NormalizedEmail = "JOHNDOE14@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE14",
                            PasswordHash = "AQAAAAIAAYagAAAAEGsAy4NKQNxKLaPHnDdtVVApmpOzz6lqJHSgEyZ4e60dmqmEK7AEUaDW3SYW0S9d2A==",
                            SecurityStamp = "23d5b027-efef-402f-ac40-1c973ec32c91",
                            UserName = "JohnDoe14"
                        },
                        new
                        {
                            Id = "2cbc69fa-7041-4dc9-93b6-a564f485ff60",
                            ConcurrencyStamp = "24df4cda-fd06-4b77-b4a3-1fd2b450f031",
                            Email = "johndoe15@personal.gmail",
                            NormalizedEmail = "JOHNDOE15@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE15",
                            PasswordHash = "AQAAAAIAAYagAAAAENvtY7EMWYQXLwZl1qyMU/IxdLhcT/I4LnSCVoUAjoK0dc885Cvdr27+nA/LRRZ2Mw==",
                            SecurityStamp = "d41a268c-7c66-4ac6-a0c7-99ab793e112e",
                            UserName = "JohnDoe15"
                        },
                        new
                        {
                            Id = "37772433-4b18-467a-b5e2-0fc23508f973",
                            ConcurrencyStamp = "82c75f87-18a0-4c6a-a4be-359882664147",
                            Email = "johndoe16@personal.gmail",
                            NormalizedEmail = "JOHNDOE16@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE16",
                            PasswordHash = "AQAAAAIAAYagAAAAEHTIE6Ct31MWiSyUgce11Fto2u0OdPtBQqZ+CNpqIud/N1NAAiphwkgmyts4BNRkpg==",
                            SecurityStamp = "5d26e97f-144e-42cc-8168-41dfcc5c1703",
                            UserName = "JohnDoe16"
                        },
                        new
                        {
                            Id = "684f3a7b-5ade-4c07-8c53-00aa790d8054",
                            ConcurrencyStamp = "03c14717-39f9-4cad-8a2e-bf8d3d8d53b9",
                            Email = "johndoe17@personal.gmail",
                            NormalizedEmail = "JOHNDOE17@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE17",
                            PasswordHash = "AQAAAAIAAYagAAAAEEhvSxdC1Izuu0PcwB39Vaub3oWf/DpGm94eFYLUL/XFnj5RPDArSRJlv6lLgID1cw==",
                            SecurityStamp = "fbd3c36b-84bc-4efb-a344-311e5816a477",
                            UserName = "JohnDoe17"
                        },
                        new
                        {
                            Id = "a77d7612-28ed-47a4-8c92-44bd14f76b8d",
                            ConcurrencyStamp = "2ac55d50-6279-45f3-a925-2fe944d92bce",
                            Email = "johndoe18@personal.gmail",
                            NormalizedEmail = "JOHNDOE18@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE18",
                            PasswordHash = "AQAAAAIAAYagAAAAEKaCKCPWXQmvcfsGG3uaUO22tAxHTgPF1mOy+luuIXsg+tmprywwA7+HKQoeiT5+sg==",
                            SecurityStamp = "d90b669d-6356-4cf4-8613-11d347e8ab3b",
                            UserName = "JohnDoe18"
                        },
                        new
                        {
                            Id = "fca954eb-2eef-4190-904a-2580754b0ce1",
                            ConcurrencyStamp = "6c536684-3010-4ab7-a1e0-5a8b8f5f79cc",
                            Email = "johndoe19@personal.gmail",
                            NormalizedEmail = "JOHNDOE19@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE19",
                            PasswordHash = "AQAAAAIAAYagAAAAEBK2nsBWqYOqN7Cbh1dsYklbrWpC4qOeYjqm46sexkC0MaOBMpm60ynyX65vDUeIzg==",
                            SecurityStamp = "c7f37a7a-d7d6-4839-bcd4-b1b2584a667d",
                            UserName = "JohnDoe19"
                        },
                        new
                        {
                            Id = "09e44e1d-4e72-4100-91ff-5d1b31ecb3e2",
                            ConcurrencyStamp = "805c6fb7-488e-4857-8666-833c7eabd1da",
                            Email = "johndoe20@personal.gmail",
                            NormalizedEmail = "JOHNDOE20@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE20",
                            PasswordHash = "AQAAAAIAAYagAAAAECMP/bIDLm8kQEkaKjhdHBEIRGssfyAzjBy6cQpjn+ZyJpRfuXP6lj+mGWw+V73ygw==",
                            SecurityStamp = "f4e2eb6f-f50a-4fbd-b1ae-67396b9419dd",
                            UserName = "JohnDoe20"
                        },
                        new
                        {
                            Id = "782d1e28-0c82-4dc8-b601-64865932fb9c",
                            ConcurrencyStamp = "25a1ef8f-0823-49a1-9610-8997929daab7",
                            Email = "johndoe21@personal.gmail",
                            NormalizedEmail = "JOHNDOE21@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE21",
                            PasswordHash = "AQAAAAIAAYagAAAAEMs0AgWingbveWmlcMHCFYGcH7AK+i2Yb0kP825ax478EclU7opU30wBTcw/RcMYjA==",
                            SecurityStamp = "b902004f-a6f8-450c-892a-993dda280c0d",
                            UserName = "JohnDoe21"
                        },
                        new
                        {
                            Id = "92ac3120-4d66-4ecf-baee-130bfd5015ed",
                            ConcurrencyStamp = "e9bbac70-1231-4b26-84f7-7f79f7997cde",
                            Email = "johndoe22@personal.gmail",
                            NormalizedEmail = "JOHNDOE22@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE22",
                            PasswordHash = "AQAAAAIAAYagAAAAEHb/7gUS+PdqRDgB3AjZbYpK/S5wPGcsg/SqnST1dCAWwB9cjHvddq/zFGhdp3ValQ==",
                            SecurityStamp = "9dab455f-ef48-4f0d-9466-795d8a1dee70",
                            UserName = "JohnDoe22"
                        },
                        new
                        {
                            Id = "82a556f8-6d4a-4291-9d7c-49890d51ace0",
                            ConcurrencyStamp = "b3481f0c-b821-40d2-b634-d2c9b3c719d9",
                            Email = "johndoe23@personal.gmail",
                            NormalizedEmail = "JOHNDOE23@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE23",
                            PasswordHash = "AQAAAAIAAYagAAAAEGV0PcYyQaZuEu0vjQwA9otSitAmfEVq/DXy7tdVjhcsphKJ/gU9qmXMHHhvhdOa0g==",
                            SecurityStamp = "1d058c3e-9512-4e96-8eb1-dde174d12852",
                            UserName = "JohnDoe23"
                        },
                        new
                        {
                            Id = "3d50a9ee-44e4-444f-bec2-13d6029f670a",
                            ConcurrencyStamp = "09412f98-614e-4de2-9c69-5cfebd538cc0",
                            Email = "johndoe24@personal.gmail",
                            NormalizedEmail = "JOHNDOE24@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE24",
                            PasswordHash = "AQAAAAIAAYagAAAAEI42jq5EREHtagww2PUE2IuFdvV+tLYAGCy+hYr6J5ZRbk9AGPvxUjf3QE2z/w3HLw==",
                            SecurityStamp = "9d33fa63-3264-4912-852d-5699132a33de",
                            UserName = "JohnDoe24"
                        },
                        new
                        {
                            Id = "479a2b5c-7d25-4377-8644-4fa1ead05ea3",
                            ConcurrencyStamp = "b99cd7d2-0715-4cb2-be32-9d67bf880b8b",
                            Email = "johndoe25@personal.gmail",
                            NormalizedEmail = "JOHNDOE25@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE25",
                            PasswordHash = "AQAAAAIAAYagAAAAEGQT6K3kOOgG0+CcHou8XNshU5GrVPH37rkGfT/tbnnCABFAWC2Uj7oZdkGrttg58A==",
                            SecurityStamp = "2376960e-fc42-427a-a04d-81eddb1789ce",
                            UserName = "JohnDoe25"
                        },
                        new
                        {
                            Id = "cfd46f59-5307-40a7-a02c-a57085883d64",
                            ConcurrencyStamp = "4a89d96a-cf9c-4fbd-a0b7-dde60140adf1",
                            Email = "johndoe26@personal.gmail",
                            NormalizedEmail = "JOHNDOE26@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE26",
                            PasswordHash = "AQAAAAIAAYagAAAAEDcljehmjdlEEK2GTioV7qvXJVB9QOEt9hMgb7bbFXUHK5p2nqveeEP8Eb1yoD4CGg==",
                            SecurityStamp = "36f5a519-9712-4a2e-b2a3-87cf9af1e5dc",
                            UserName = "JohnDoe26"
                        },
                        new
                        {
                            Id = "a732a1ac-8f5d-4a04-ba29-292878f48467",
                            ConcurrencyStamp = "2add984a-d76c-4bf8-8d48-6459ddd99322",
                            Email = "johndoe27@personal.gmail",
                            NormalizedEmail = "JOHNDOE27@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE27",
                            PasswordHash = "AQAAAAIAAYagAAAAEG4J3pjKyPVpXVdHLR/8bVyssbSBkViYWQI6I5RI5ZlUpXvZH7RNJoSLe7F0RyvWpA==",
                            SecurityStamp = "ba85f425-9ea7-4608-8aab-1a687327a369",
                            UserName = "JohnDoe27"
                        },
                        new
                        {
                            Id = "05b27d59-860a-403f-b031-b1d71226b1c0",
                            ConcurrencyStamp = "3ebdc812-f3d3-411f-9f74-c6dd1dcc7bdb",
                            Email = "johndoe28@personal.gmail",
                            NormalizedEmail = "JOHNDOE28@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE28",
                            PasswordHash = "AQAAAAIAAYagAAAAEMwY3A9Qs3eqvLTJ8QYqrkBKwqiYuccFZWJMM/NM9TtKmAtl2ukRnE+YT52rYpc9Pw==",
                            SecurityStamp = "338c1eab-8f15-4124-a3de-fff493a1f26c",
                            UserName = "JohnDoe28"
                        },
                        new
                        {
                            Id = "d05295b9-3eca-485e-86c9-8fdf720ee39f",
                            ConcurrencyStamp = "962176cd-cbda-4e1f-bd99-3ac2fad9048e",
                            Email = "johndoe29@personal.gmail",
                            NormalizedEmail = "JOHNDOE29@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE29",
                            PasswordHash = "AQAAAAIAAYagAAAAEHf2s8wRy/eYWuu5eVuLfytJDCnxPC9nTelSO9sYTWxfe+vVeyQiyLzNoCtsbw/nyA==",
                            SecurityStamp = "390d3a1e-2d0b-4432-b021-823557d547c1",
                            UserName = "JohnDoe29"
                        },
                        new
                        {
                            Id = "0c6a1cd6-99ed-4ff9-a8e4-6847a8b5eaaf",
                            ConcurrencyStamp = "da745e6b-d349-4b2b-b200-bc4643cff2d5",
                            Email = "johndoe30@personal.gmail",
                            NormalizedEmail = "JOHNDOE30@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE30",
                            PasswordHash = "AQAAAAIAAYagAAAAEL6c0M4o5doSxryHmr3tvik73KtS7ExHqh5HQaDHtS0wjUqAsGMNO0jJ/1VK2KFEhg==",
                            SecurityStamp = "eadab7e5-076a-42dc-a44f-913f875f684e",
                            UserName = "JohnDoe30"
                        },
                        new
                        {
                            Id = "4158f70b-8e4e-48f6-ba4a-ce57f4b37c78",
                            ConcurrencyStamp = "2dc8b796-505e-47c5-8cad-d126d6d8f302",
                            Email = "johndoe31@personal.gmail",
                            NormalizedEmail = "JOHNDOE31@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE31",
                            PasswordHash = "AQAAAAIAAYagAAAAEAMNv2DC+La9TojjjR5G0q83dW4V7Bm0SlQo9TqT9ELO50dEaDvLEz/c2wUWBrfXgg==",
                            SecurityStamp = "d84f9ff2-63ae-4074-8afd-08aa2672c307",
                            UserName = "JohnDoe31"
                        },
                        new
                        {
                            Id = "edb5265c-3efc-4b8f-994e-35cda8cb665d",
                            ConcurrencyStamp = "c71829fd-0b3b-4ab0-a362-bd83edad71cf",
                            Email = "johndoe32@personal.gmail",
                            NormalizedEmail = "JOHNDOE32@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE32",
                            PasswordHash = "AQAAAAIAAYagAAAAEDik0zCD2x2QYusETY6I0Q80OpH2kNwb5DhutAImE/iwGKdiI8fEWNwxU4IH6s6t/A==",
                            SecurityStamp = "a8212c12-f762-40ba-8c99-abab18141b63",
                            UserName = "JohnDoe32"
                        },
                        new
                        {
                            Id = "ae16d477-0ce6-4ed5-aeb8-7475ea2a9d28",
                            ConcurrencyStamp = "d1f3b896-f16d-489d-ad04-1c5abb17af0b",
                            Email = "johndoe33@personal.gmail",
                            NormalizedEmail = "JOHNDOE33@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE33",
                            PasswordHash = "AQAAAAIAAYagAAAAECjpB4Y4vlpXhEXouBqnNh7dXeZq/2jpD7QeKQ0JxI/5AQ2qMizcxIA+6/HtwX4Jhw==",
                            SecurityStamp = "0c4e7e74-aeca-4ad9-87ef-ac476f461b18",
                            UserName = "JohnDoe33"
                        },
                        new
                        {
                            Id = "51681ea7-f777-49a2-8d5e-9d807d1493f7",
                            ConcurrencyStamp = "8921b097-7496-445b-a05d-97cf08410fff",
                            Email = "johndoe34@personal.gmail",
                            NormalizedEmail = "JOHNDOE34@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE34",
                            PasswordHash = "AQAAAAIAAYagAAAAEMlkKf78KhI+WbuJ4GsVC+zhFkeHCl7+LQKVsYyubAmbLyUH/ubohcEIjn7tYkzG1w==",
                            SecurityStamp = "906b9c28-97f7-4551-9b60-4e84529a6bce",
                            UserName = "JohnDoe34"
                        },
                        new
                        {
                            Id = "022c36bc-8081-4159-874f-81c7f19ed56b",
                            ConcurrencyStamp = "b45b34c1-7916-41ba-976e-518c5bd1cf98",
                            Email = "johndoe35@personal.gmail",
                            NormalizedEmail = "JOHNDOE35@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE35",
                            PasswordHash = "AQAAAAIAAYagAAAAEGazbbeZKkdCY+lhhEx83wMEwZf7HpltDyg7Em7VsNG6OCPwSK9g+JL1xDWHHGXqSA==",
                            SecurityStamp = "afb3a4bb-4a47-4cbd-aa42-30b15bc0b534",
                            UserName = "JohnDoe35"
                        },
                        new
                        {
                            Id = "0ec762e0-ec2b-41f4-9751-34c7dbc1fc6e",
                            ConcurrencyStamp = "b46faad0-b04a-49ec-beb4-26088a085bfe",
                            Email = "johndoe36@personal.gmail",
                            NormalizedEmail = "JOHNDOE36@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE36",
                            PasswordHash = "AQAAAAIAAYagAAAAENm+hzXE1YiNNWSq7ErkzuDx7YkMyqjptSPkTcTmZy27YlZI1ItxoEC2IbOrQr2rbQ==",
                            SecurityStamp = "7b51251d-9109-43a7-8fef-f575bbf8b390",
                            UserName = "JohnDoe36"
                        },
                        new
                        {
                            Id = "b2a4de94-bfda-4610-8114-24402f2009c3",
                            ConcurrencyStamp = "dd64b84e-01b4-40ff-9289-7e62bfd86de4",
                            Email = "johndoe37@personal.gmail",
                            NormalizedEmail = "JOHNDOE37@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE37",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1xzAAa3xAHAl0BAXz5yL+C3s86BT9nk/rLmShYhNbkbIai2xefIG5KA1236U8+NA==",
                            SecurityStamp = "169b4624-f3ac-4962-9f7e-ac181f6c95d7",
                            UserName = "JohnDoe37"
                        },
                        new
                        {
                            Id = "697dfeeb-677b-4d1e-889e-1df078918597",
                            ConcurrencyStamp = "a76db69d-ed9a-4a19-ab53-934e0ba4aa71",
                            Email = "johndoe38@personal.gmail",
                            NormalizedEmail = "JOHNDOE38@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE38",
                            PasswordHash = "AQAAAAIAAYagAAAAEA4x9AK/QLuuJfEfwXyKXEJVS1W2bXhjOQlH3CqP016PwrqKo/7x5mqH1EgWfqb5Dw==",
                            SecurityStamp = "7db35984-be96-4e52-ad92-d897a7741a8c",
                            UserName = "JohnDoe38"
                        },
                        new
                        {
                            Id = "099bf4d1-ec02-4a69-a1c1-c58d09428bcf",
                            ConcurrencyStamp = "91aab8e5-25b6-426f-af18-33dfdd8c9cbc",
                            Email = "johndoe39@personal.gmail",
                            NormalizedEmail = "JOHNDOE39@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE39",
                            PasswordHash = "AQAAAAIAAYagAAAAEOxdg5KicTIVotoMWs8zSTslE2P5Yl5q4PHlB+VM7PjlV1RWi9SBJkT5pjzm6RZUWQ==",
                            SecurityStamp = "7e40c360-828e-496b-9744-83b5a96d8732",
                            UserName = "JohnDoe39"
                        },
                        new
                        {
                            Id = "06a5680e-143b-454f-a58c-922b7806718c",
                            ConcurrencyStamp = "dfdb0570-c86f-4392-9bcf-0de9311edb34",
                            Email = "johndoe40@personal.gmail",
                            NormalizedEmail = "JOHNDOE40@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE40",
                            PasswordHash = "AQAAAAIAAYagAAAAEK3uGtVUp5B+HFFTeLHyH2esRaL8Gw6wVVDIUI8mcWTr+uwcBFCw2y3yBJBMuXVPVw==",
                            SecurityStamp = "d1b97202-7dce-4ff9-86d9-b8c223d1b7a6",
                            UserName = "JohnDoe40"
                        },
                        new
                        {
                            Id = "57eb8344-013c-4c62-a24a-925e2fe93d39",
                            ConcurrencyStamp = "5f3039f7-e7fa-4ef2-b36e-e2faa6e7c90c",
                            Email = "johndoe41@personal.gmail",
                            NormalizedEmail = "JOHNDOE41@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE41",
                            PasswordHash = "AQAAAAIAAYagAAAAENUHlZKpKEeDKe6H2fuL9ln1i51S9c7WXBEKq+7tGCme9wLVocO9crG0WnJjJn9gMQ==",
                            SecurityStamp = "666107f3-0748-4f5f-962c-4abcc86c4b6a",
                            UserName = "JohnDoe41"
                        },
                        new
                        {
                            Id = "35a803ce-9d5f-4ce1-b343-de7edce5b2d6",
                            ConcurrencyStamp = "bdf7b9ae-5699-4ef9-a6ab-2b274579bd1e",
                            Email = "johndoe42@personal.gmail",
                            NormalizedEmail = "JOHNDOE42@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE42",
                            PasswordHash = "AQAAAAIAAYagAAAAEGnL9GEBKotABLUbF/ay6oaZC/e88jux9UlDrlEfGpppTKwEu21dnFFHe1VgpgPskw==",
                            SecurityStamp = "1300227b-799b-4d98-8431-efa855803cb5",
                            UserName = "JohnDoe42"
                        },
                        new
                        {
                            Id = "2882aa57-8adb-48d0-a730-c8dff27e18f6",
                            ConcurrencyStamp = "3ae4df41-7d09-4bc3-abf6-9eeaabd6d19d",
                            Email = "johndoe43@personal.gmail",
                            NormalizedEmail = "JOHNDOE43@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE43",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0CIpTTXr97QQUrIOEolk96GPaps8Qn1okbP0XJnnfEZssXE10Nivk+ggxIjFw2Yw==",
                            SecurityStamp = "13b6a43d-8a2f-4b08-9208-3f038cdb0209",
                            UserName = "JohnDoe43"
                        },
                        new
                        {
                            Id = "ef44e7db-09ee-4faf-879c-23bf88c6ea8d",
                            ConcurrencyStamp = "6800f0da-cd7e-40aa-896f-6a9488414bc9",
                            Email = "johndoe44@personal.gmail",
                            NormalizedEmail = "JOHNDOE44@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE44",
                            PasswordHash = "AQAAAAIAAYagAAAAEKV4XJQQe/N/l3FEPTGrttkruPrzMK6c4MkJv58Dmj5sn34eAWLoGNGPEiUqV14ieQ==",
                            SecurityStamp = "2e24e690-95a8-4914-b644-5e1af00090b4",
                            UserName = "JohnDoe44"
                        },
                        new
                        {
                            Id = "fb3d84e4-bbec-4e1f-8105-6d6eaecc4086",
                            ConcurrencyStamp = "ff5851e6-bba3-498c-9728-3d03a2c51c81",
                            Email = "johndoe45@personal.gmail",
                            NormalizedEmail = "JOHNDOE45@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE45",
                            PasswordHash = "AQAAAAIAAYagAAAAEMXk3mErPBxCaxgfTwJym26ZT3J9eD/7MfiA1d0G9XdkVNQ7/FGdE6dZptamaRKraA==",
                            SecurityStamp = "59a802f9-12c8-42b4-89e7-cb2ee29ee57c",
                            UserName = "JohnDoe45"
                        },
                        new
                        {
                            Id = "d8060eb6-81a4-46b0-9897-3f5ed97cc286",
                            ConcurrencyStamp = "3486998e-3fb9-4680-b0d3-933a664f8716",
                            Email = "johndoe46@personal.gmail",
                            NormalizedEmail = "JOHNDOE46@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE46",
                            PasswordHash = "AQAAAAIAAYagAAAAEJgzWN2PqggRHw0F+A5UFS4JmztI8A4f03eqXq3NjF4kTpO1g4ILrPm6aVNdxZ2nSA==",
                            SecurityStamp = "b99ba755-d78f-4aff-9a38-3c3883790252",
                            UserName = "JohnDoe46"
                        },
                        new
                        {
                            Id = "b82f8b82-4567-4326-8b62-d7356fe255df",
                            ConcurrencyStamp = "d43b7612-3822-4661-8ba1-976bc0aa1bdf",
                            Email = "johndoe47@personal.gmail",
                            NormalizedEmail = "JOHNDOE47@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE47",
                            PasswordHash = "AQAAAAIAAYagAAAAELmPS0nXmrngbcXs7B6/rEnmZMmjmISlBQTTGNGl7NRFvYtyGO+n6QhLe5oAr3nEQA==",
                            SecurityStamp = "73f5adeb-0f5c-4770-9734-a0e5458d84d1",
                            UserName = "JohnDoe47"
                        },
                        new
                        {
                            Id = "b064362a-c0da-4b6f-bd6b-126608bfee9d",
                            ConcurrencyStamp = "2799ccb2-8397-45fe-87ad-1fce963de483",
                            Email = "johndoe48@personal.gmail",
                            NormalizedEmail = "JOHNDOE48@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE48",
                            PasswordHash = "AQAAAAIAAYagAAAAEOhhoW7xL1y1cOAv2AWRPVJQiceDzXIn4g8/OC7L7ZMiIcsMNKMWvVzRbqKtWD/Pbw==",
                            SecurityStamp = "221dfca4-db48-4b59-aec6-c9b5d2d651b5",
                            UserName = "JohnDoe48"
                        },
                        new
                        {
                            Id = "0fa79691-1937-45ee-8c0c-e2e1f25b0735",
                            ConcurrencyStamp = "b328c781-6d44-4255-af81-347f1e15eb31",
                            Email = "johndoe49@personal.gmail",
                            NormalizedEmail = "JOHNDOE49@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE49",
                            PasswordHash = "AQAAAAIAAYagAAAAEIAPMSz9T7nxWfzwPXtd4Dqh5k9dc1VOlouZKH9hZXj3zqSmdBoWT1NsQXdjD2B9WQ==",
                            SecurityStamp = "2da81b8f-53c7-4677-a4cd-f4f78bf7c93b",
                            UserName = "JohnDoe49"
                        },
                        new
                        {
                            Id = "6a8d59a0-0f17-432a-a049-af5c524d7abe",
                            ConcurrencyStamp = "e7af5bd1-c736-4106-bf22-e138cb8537ef",
                            Email = "johndoe50@personal.gmail",
                            NormalizedEmail = "JOHNDOE50@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE50",
                            PasswordHash = "AQAAAAIAAYagAAAAEKkq7O8se7Zd+1P9nX6NAkC8r+BfLE8Yw+I3htsdISv+N0VxEr7smZeO3gA+dpNPIw==",
                            SecurityStamp = "5ab2b8d0-bb48-4bb7-bd09-c0c4b699920f",
                            UserName = "JohnDoe50"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "johndoe1@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Finance Manager",
                            LastName = "Doe",
                            Salary = 3172.5m,
                            UserId = "58181f28-91f9-4a64-a3df-ef909f046b33"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "johndoe2@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "IT Manager",
                            LastName = "Doe",
                            Salary = 6561.0m,
                            UserId = "3942c37e-14a6-4538-95f7-126dfeafc253"
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "johndoe3@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Manager",
                            LastName = "Doe",
                            Salary = 3039.0m,
                            UserId = "50c9665c-8633-4c52-a072-bf10848ed658"
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "johndoe4@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Manager",
                            LastName = "Doe",
                            Salary = 3634.5m,
                            UserId = "c63626b0-9fe9-4333-af7c-e763ad93ed38"
                        },
                        new
                        {
                            Id = 5,
                            CompanyEmail = "johndoe5@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Manager",
                            LastName = "Doe",
                            Salary = 4071.0m,
                            UserId = "67db0983-40c0-449b-b077-544d4885abac"
                        },
                        new
                        {
                            Id = 6,
                            CompanyEmail = "johndoe6@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Salary = 2484.0m,
                            UserId = "1ceabc7c-ba50-40d6-a0fe-8590d2dbb268"
                        },
                        new
                        {
                            Id = 7,
                            CompanyEmail = "johndoe7@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2078m,
                            UserId = "d42868ec-505d-4c9c-83a6-4c10735fdb13"
                        },
                        new
                        {
                            Id = 8,
                            CompanyEmail = "johndoe8@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4215m,
                            UserId = "d5c0d689-46b4-46be-9a76-90cd6d6d18ad"
                        },
                        new
                        {
                            Id = 9,
                            CompanyEmail = "johndoe9@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2046m,
                            UserId = "2bc94167-68da-4a53-914f-555414efc55f"
                        },
                        new
                        {
                            Id = 10,
                            CompanyEmail = "johndoe10@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 4018m,
                            UserId = "dddd68cc-25bc-4b8d-a1f0-37a1a1229808"
                        },
                        new
                        {
                            Id = 11,
                            CompanyEmail = "johndoe11@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2589m,
                            UserId = "dcc38bd9-a063-4b5d-97e6-8620a437de02"
                        },
                        new
                        {
                            Id = 12,
                            CompanyEmail = "johndoe12@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1520m,
                            UserId = "3961334a-7c0b-43b0-a0b2-46f06eca7b31"
                        },
                        new
                        {
                            Id = 13,
                            CompanyEmail = "johndoe13@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2010m,
                            UserId = "0a428d4b-58d2-47a5-b6de-6b2f3d88d847"
                        },
                        new
                        {
                            Id = 14,
                            CompanyEmail = "johndoe14@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4905m,
                            UserId = "440f9a76-0591-4e51-8eb6-50c1bf7bf1b7"
                        },
                        new
                        {
                            Id = 15,
                            CompanyEmail = "johndoe15@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2022m,
                            UserId = "2cbc69fa-7041-4dc9-93b6-a564f485ff60"
                        },
                        new
                        {
                            Id = 16,
                            CompanyEmail = "johndoe16@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 3093m,
                            UserId = "37772433-4b18-467a-b5e2-0fc23508f973"
                        },
                        new
                        {
                            Id = 17,
                            CompanyEmail = "johndoe17@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2718m,
                            UserId = "684f3a7b-5ade-4c07-8c53-00aa790d8054"
                        },
                        new
                        {
                            Id = 18,
                            CompanyEmail = "johndoe18@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1738m,
                            UserId = "a77d7612-28ed-47a4-8c92-44bd14f76b8d"
                        },
                        new
                        {
                            Id = 19,
                            CompanyEmail = "johndoe19@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2156m,
                            UserId = "fca954eb-2eef-4190-904a-2580754b0ce1"
                        },
                        new
                        {
                            Id = 20,
                            CompanyEmail = "johndoe20@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4692m,
                            UserId = "09e44e1d-4e72-4100-91ff-5d1b31ecb3e2"
                        },
                        new
                        {
                            Id = 21,
                            CompanyEmail = "johndoe21@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2125m,
                            UserId = "782d1e28-0c82-4dc8-b601-64865932fb9c"
                        },
                        new
                        {
                            Id = 22,
                            CompanyEmail = "johndoe22@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 4514m,
                            UserId = "92ac3120-4d66-4ecf-baee-130bfd5015ed"
                        },
                        new
                        {
                            Id = 23,
                            CompanyEmail = "johndoe23@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2864m,
                            UserId = "82a556f8-6d4a-4291-9d7c-49890d51ace0"
                        },
                        new
                        {
                            Id = 24,
                            CompanyEmail = "johndoe24@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1683m,
                            UserId = "3d50a9ee-44e4-444f-bec2-13d6029f670a"
                        },
                        new
                        {
                            Id = 25,
                            CompanyEmail = "johndoe25@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2010m,
                            UserId = "479a2b5c-7d25-4377-8644-4fa1ead05ea3"
                        },
                        new
                        {
                            Id = 26,
                            CompanyEmail = "johndoe26@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4727m,
                            UserId = "cfd46f59-5307-40a7-a02c-a57085883d64"
                        },
                        new
                        {
                            Id = 27,
                            CompanyEmail = "johndoe27@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2168m,
                            UserId = "a732a1ac-8f5d-4a04-ba29-292878f48467"
                        },
                        new
                        {
                            Id = 28,
                            CompanyEmail = "johndoe28@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 3682m,
                            UserId = "05b27d59-860a-403f-b031-b1d71226b1c0"
                        },
                        new
                        {
                            Id = 29,
                            CompanyEmail = "johndoe29@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2584m,
                            UserId = "d05295b9-3eca-485e-86c9-8fdf720ee39f"
                        },
                        new
                        {
                            Id = 30,
                            CompanyEmail = "johndoe30@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1585m,
                            UserId = "0c6a1cd6-99ed-4ff9-a8e4-6847a8b5eaaf"
                        },
                        new
                        {
                            Id = 31,
                            CompanyEmail = "johndoe31@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2102m,
                            UserId = "4158f70b-8e4e-48f6-ba4a-ce57f4b37c78"
                        },
                        new
                        {
                            Id = 32,
                            CompanyEmail = "johndoe32@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4256m,
                            UserId = "edb5265c-3efc-4b8f-994e-35cda8cb665d"
                        },
                        new
                        {
                            Id = 33,
                            CompanyEmail = "johndoe33@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2132m,
                            UserId = "ae16d477-0ce6-4ed5-aeb8-7475ea2a9d28"
                        },
                        new
                        {
                            Id = 34,
                            CompanyEmail = "johndoe34@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 4049m,
                            UserId = "51681ea7-f777-49a2-8d5e-9d807d1493f7"
                        },
                        new
                        {
                            Id = 35,
                            CompanyEmail = "johndoe35@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2957m,
                            UserId = "022c36bc-8081-4159-874f-81c7f19ed56b"
                        },
                        new
                        {
                            Id = 36,
                            CompanyEmail = "johndoe36@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1517m,
                            UserId = "0ec762e0-ec2b-41f4-9751-34c7dbc1fc6e"
                        },
                        new
                        {
                            Id = 37,
                            CompanyEmail = "johndoe37@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2102m,
                            UserId = "b2a4de94-bfda-4610-8114-24402f2009c3"
                        },
                        new
                        {
                            Id = 38,
                            CompanyEmail = "johndoe38@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4374m,
                            UserId = "697dfeeb-677b-4d1e-889e-1df078918597"
                        },
                        new
                        {
                            Id = 39,
                            CompanyEmail = "johndoe39@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2198m,
                            UserId = "099bf4d1-ec02-4a69-a1c1-c58d09428bcf"
                        },
                        new
                        {
                            Id = 40,
                            CompanyEmail = "johndoe40@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 3523m,
                            UserId = "06a5680e-143b-454f-a58c-922b7806718c"
                        },
                        new
                        {
                            Id = 41,
                            CompanyEmail = "johndoe41@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2762m,
                            UserId = "57eb8344-013c-4c62-a24a-925e2fe93d39"
                        },
                        new
                        {
                            Id = 42,
                            CompanyEmail = "johndoe42@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1712m,
                            UserId = "35a803ce-9d5f-4ce1-b343-de7edce5b2d6"
                        },
                        new
                        {
                            Id = 43,
                            CompanyEmail = "johndoe43@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2099m,
                            UserId = "2882aa57-8adb-48d0-a730-c8dff27e18f6"
                        },
                        new
                        {
                            Id = 44,
                            CompanyEmail = "johndoe44@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4796m,
                            UserId = "ef44e7db-09ee-4faf-879c-23bf88c6ea8d"
                        },
                        new
                        {
                            Id = 45,
                            CompanyEmail = "johndoe45@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2018m,
                            UserId = "fb3d84e4-bbec-4e1f-8105-6d6eaecc4086"
                        },
                        new
                        {
                            Id = 46,
                            CompanyEmail = "johndoe46@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 2272m,
                            UserId = "d8060eb6-81a4-46b0-9897-3f5ed97cc286"
                        },
                        new
                        {
                            Id = 47,
                            CompanyEmail = "johndoe47@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2620m,
                            UserId = "b82f8b82-4567-4326-8b62-d7356fe255df"
                        },
                        new
                        {
                            Id = 48,
                            CompanyEmail = "johndoe48@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1745m,
                            UserId = "b064362a-c0da-4b6f-bd6b-126608bfee9d"
                        },
                        new
                        {
                            Id = 49,
                            CompanyEmail = "johndoe49@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2068m,
                            UserId = "0fa79691-1937-45ee-8c0c-e2e1f25b0735"
                        },
                        new
                        {
                            Id = 50,
                            CompanyEmail = "johndoe50@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4642m,
                            UserId = "6a8d59a0-0f17-432a-a049-af5c524d7abe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "7f01c7f4-2c17-4032-9c63-5f0ba0a90931",
                            Name = "HR Admin",
                            NormalizedName = "HR ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "50865b45-adcf-4ae8-ab4d-f607e750041d",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "c0078c37-ac40-451f-979c-f7d45c4eb604",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "58181f28-91f9-4a64-a3df-ef909f046b33",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3942c37e-14a6-4538-95f7-126dfeafc253",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "50c9665c-8633-4c52-a072-bf10848ed658",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "c63626b0-9fe9-4333-af7c-e763ad93ed38",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "67db0983-40c0-449b-b077-544d4885abac",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "1ceabc7c-ba50-40d6-a0fe-8590d2dbb268",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "d42868ec-505d-4c9c-83a6-4c10735fdb13",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d5c0d689-46b4-46be-9a76-90cd6d6d18ad",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2bc94167-68da-4a53-914f-555414efc55f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "dddd68cc-25bc-4b8d-a1f0-37a1a1229808",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "dcc38bd9-a063-4b5d-97e6-8620a437de02",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3961334a-7c0b-43b0-a0b2-46f06eca7b31",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "0a428d4b-58d2-47a5-b6de-6b2f3d88d847",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "440f9a76-0591-4e51-8eb6-50c1bf7bf1b7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2cbc69fa-7041-4dc9-93b6-a564f485ff60",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "37772433-4b18-467a-b5e2-0fc23508f973",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "684f3a7b-5ade-4c07-8c53-00aa790d8054",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a77d7612-28ed-47a4-8c92-44bd14f76b8d",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "fca954eb-2eef-4190-904a-2580754b0ce1",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "09e44e1d-4e72-4100-91ff-5d1b31ecb3e2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "782d1e28-0c82-4dc8-b601-64865932fb9c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "92ac3120-4d66-4ecf-baee-130bfd5015ed",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "82a556f8-6d4a-4291-9d7c-49890d51ace0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3d50a9ee-44e4-444f-bec2-13d6029f670a",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "479a2b5c-7d25-4377-8644-4fa1ead05ea3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "cfd46f59-5307-40a7-a02c-a57085883d64",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a732a1ac-8f5d-4a04-ba29-292878f48467",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "05b27d59-860a-403f-b031-b1d71226b1c0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d05295b9-3eca-485e-86c9-8fdf720ee39f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0c6a1cd6-99ed-4ff9-a8e4-6847a8b5eaaf",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "4158f70b-8e4e-48f6-ba4a-ce57f4b37c78",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "edb5265c-3efc-4b8f-994e-35cda8cb665d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ae16d477-0ce6-4ed5-aeb8-7475ea2a9d28",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "51681ea7-f777-49a2-8d5e-9d807d1493f7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "022c36bc-8081-4159-874f-81c7f19ed56b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0ec762e0-ec2b-41f4-9751-34c7dbc1fc6e",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "b2a4de94-bfda-4610-8114-24402f2009c3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "697dfeeb-677b-4d1e-889e-1df078918597",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "099bf4d1-ec02-4a69-a1c1-c58d09428bcf",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "06a5680e-143b-454f-a58c-922b7806718c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "57eb8344-013c-4c62-a24a-925e2fe93d39",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "35a803ce-9d5f-4ce1-b343-de7edce5b2d6",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2882aa57-8adb-48d0-a730-c8dff27e18f6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ef44e7db-09ee-4faf-879c-23bf88c6ea8d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "fb3d84e4-bbec-4e1f-8105-6d6eaecc4086",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d8060eb6-81a4-46b0-9897-3f5ed97cc286",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b82f8b82-4567-4326-8b62-d7356fe255df",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b064362a-c0da-4b6f-bd6b-126608bfee9d",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "0fa79691-1937-45ee-8c0c-e2e1f25b0735",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6a8d59a0-0f17-432a-a049-af5c524d7abe",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
