// <auto-generated />
using HumanCapitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanCapitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250717160231_SeededDbAgain")]
    partial class SeededDbAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanCapitalManagement.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c9cc4223-eee3-4826-92fa-b774c4c608a3",
                            ConcurrencyStamp = "1a434772-5fba-4259-8401-b4d2c348996b",
                            Email = "johndoe1@personal.gmail",
                            NormalizedEmail = "JOHNDOE1@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEFZN+NtQDPYfmtvWllSbqbtg6iFF71p2IZPMgTI5khlc0xcHqZa1rRKOCIZ5kdfk/Q==",
                            SecurityStamp = "544b1c81-523a-4034-88bd-a0660328e583",
                            UserName = "JohnDoe1"
                        },
                        new
                        {
                            Id = "1f7b8188-0e7c-4764-a453-7b3dfb396dda",
                            ConcurrencyStamp = "319d5319-1c30-47d4-9c7f-08c43a7eb6ac",
                            Email = "johndoe2@personal.gmail",
                            NormalizedEmail = "JOHNDOE2@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE2",
                            PasswordHash = "AQAAAAIAAYagAAAAEGz6cXQmW9Q4M3VrLR56EzLr7rNeVKPVZat9ttPQy8J5VsMOqV36NO8iPUDWCNwmdw==",
                            SecurityStamp = "c9462029-d19b-4a22-bf75-d1f48ddeb1ab",
                            UserName = "JohnDoe2"
                        },
                        new
                        {
                            Id = "64566c45-5a21-4f9a-a074-7719a36d719e",
                            ConcurrencyStamp = "8f237a57-feab-4f45-a341-329398a027e8",
                            Email = "johndoe3@personal.gmail",
                            NormalizedEmail = "JOHNDOE3@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE3",
                            PasswordHash = "AQAAAAIAAYagAAAAECHPcv5poaDXb+6lPdXEeB8Uqm+9lshE5YUIRfoNYp3udDLZGj++np97BVkJJZLZ3Q==",
                            SecurityStamp = "01302b7a-b2f3-4141-9ea4-9e0f7e6966ef",
                            UserName = "JohnDoe3"
                        },
                        new
                        {
                            Id = "1e64def5-b5be-45f7-8f75-36c2a84cc4a0",
                            ConcurrencyStamp = "45eddbf1-69d6-4b8e-9672-3626a04086c5",
                            Email = "johndoe4@personal.gmail",
                            NormalizedEmail = "JOHNDOE4@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEH0fE4OsatArH1W9hw7nqBg3u7PwuQ2ELpJW6H23Fh0D5Lq5kH3lgy88k7Dbr89/xw==",
                            SecurityStamp = "508ed0e3-dfaa-405a-8360-21e9abfa5d88",
                            UserName = "JohnDoe4"
                        },
                        new
                        {
                            Id = "f1df7b6c-af5e-4d0a-9d20-510088708682",
                            ConcurrencyStamp = "f7afbf96-8d22-455d-9fdf-0b4595105df2",
                            Email = "johndoe5@personal.gmail",
                            NormalizedEmail = "JOHNDOE5@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE5",
                            PasswordHash = "AQAAAAIAAYagAAAAEKl/jgyAmTSf5yogrWQOvmE90EEO2GjIH0XAIL/dSdXblTXcf6TPHYJHMnyzfi7vug==",
                            SecurityStamp = "d961d972-44cf-4410-9ca1-ec0dc8a64eb8",
                            UserName = "JohnDoe5"
                        },
                        new
                        {
                            Id = "af4820c9-c023-40e6-ac3c-32915ed3a7e5",
                            ConcurrencyStamp = "e91b6ad5-298f-47ab-bb70-a91fc5d5bc28",
                            Email = "johndoe6@personal.gmail",
                            NormalizedEmail = "JOHNDOE6@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE6",
                            PasswordHash = "AQAAAAIAAYagAAAAECQiAZeQQH7TdZPqSWzm1rXketyg6PcFf5nzeHJ2iY47hFi7ndFxiQ3Akg4wDr2EjQ==",
                            SecurityStamp = "4489e0a0-4a31-440a-afa2-936c900087ad",
                            UserName = "JohnDoe6"
                        },
                        new
                        {
                            Id = "50dd659a-5c61-40bc-bb9b-938bb656251a",
                            ConcurrencyStamp = "d5bf356f-9320-4a34-98ad-20616eccce18",
                            Email = "johndoe7@personal.gmail",
                            NormalizedEmail = "JOHNDOE7@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE7",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ5afttZx0L7Mz6hegrNMQQ57P0OsHeekDR40I7jRxLPy8ate8C1CzUbJF+KM8c4jw==",
                            SecurityStamp = "a0f87ede-814b-45c5-872b-c6307c4011b2",
                            UserName = "JohnDoe7"
                        },
                        new
                        {
                            Id = "d04f0de8-0c22-4d56-9545-552bbba6c4a9",
                            ConcurrencyStamp = "cc4fc7ba-3eba-4db8-8dd3-4b1517ea5db0",
                            Email = "johndoe8@personal.gmail",
                            NormalizedEmail = "JOHNDOE8@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE8",
                            PasswordHash = "AQAAAAIAAYagAAAAEDuDCzHWo61j5yj3oqH8gDGqLKeTgoQ488xF3xiRujkOdgb8bLMvZnskn5iQ5Bv3CA==",
                            SecurityStamp = "7c851a03-0bc2-4d2a-ab08-58cab6bff500",
                            UserName = "JohnDoe8"
                        },
                        new
                        {
                            Id = "03d2df2f-2b82-47f5-a4cb-b902983e27d7",
                            ConcurrencyStamp = "fbc0826c-93a0-47d6-9386-43123bbbecff",
                            Email = "johndoe9@personal.gmail",
                            NormalizedEmail = "JOHNDOE9@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE9",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4BvMKRsvcYWuX3+rb5kIWVtGETyHTy+rmo9c+hQSTAZ5+6dbuw76M+NdLXT9Wg7g==",
                            SecurityStamp = "b08b02d8-cde0-4ed4-a95c-d121abaad18f",
                            UserName = "JohnDoe9"
                        },
                        new
                        {
                            Id = "08431c71-0402-4723-9eb4-ceaf5f0b691c",
                            ConcurrencyStamp = "17a33af6-328e-4f40-9608-e83ef44c80b6",
                            Email = "johndoe10@personal.gmail",
                            NormalizedEmail = "JOHNDOE10@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE10",
                            PasswordHash = "AQAAAAIAAYagAAAAEMcOWuHQg2IBBd7WB5eH9Cf58FATazVbfuZK5UhTwRkFMyBFUZ0+MvCUhZn4ULmlmQ==",
                            SecurityStamp = "caaaff43-8375-4482-910e-00895a91f58a",
                            UserName = "JohnDoe10"
                        },
                        new
                        {
                            Id = "d990afdc-96c1-406f-8b62-d8e0a1c0f676",
                            ConcurrencyStamp = "b2343fd2-5711-41b5-85e2-8f0350fb7d4a",
                            Email = "johndoe11@personal.gmail",
                            NormalizedEmail = "JOHNDOE11@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE11",
                            PasswordHash = "AQAAAAIAAYagAAAAENHgZhSNsJt5vplKdYIoZbo/DjXAMXweEuka5WffKhfZ9AwbSTzM1LtroVp5YgoadA==",
                            SecurityStamp = "3de6d414-b79c-4ab6-b20e-b7aa6db9f0a4",
                            UserName = "JohnDoe11"
                        },
                        new
                        {
                            Id = "c3d80974-4f53-436d-b258-562cccbb5911",
                            ConcurrencyStamp = "bdfb2103-1ba1-48ef-90be-eca268fbe595",
                            Email = "johndoe12@personal.gmail",
                            NormalizedEmail = "JOHNDOE12@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE12",
                            PasswordHash = "AQAAAAIAAYagAAAAEHCazXFtZTzd0VIoDVEbkGUxfdmNRrdLldaeY/tit4sJ0lYNJhRfxOkvVayrQFBZnw==",
                            SecurityStamp = "32a83758-c9a3-4ca7-a5fb-ddafb0b5e55e",
                            UserName = "JohnDoe12"
                        },
                        new
                        {
                            Id = "75ee5357-ff22-4147-9969-c292aa655614",
                            ConcurrencyStamp = "3e0a946f-3ec7-42aa-90d3-a062cd01b649",
                            Email = "johndoe13@personal.gmail",
                            NormalizedEmail = "JOHNDOE13@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE13",
                            PasswordHash = "AQAAAAIAAYagAAAAEI4aqs+gYwp580p5Ue1+bXwYHMbNCNFXEMfWnjrGf1AjlhoBvZRwFXu2oDuWZu3f4Q==",
                            SecurityStamp = "f8a4db76-48e7-42fb-9b5d-7a00651a5d2f",
                            UserName = "JohnDoe13"
                        },
                        new
                        {
                            Id = "2cc909ea-29bb-4eeb-84fc-90cd4abbdc5d",
                            ConcurrencyStamp = "5fc9ebad-bd05-4925-a204-1779c6d91473",
                            Email = "johndoe14@personal.gmail",
                            NormalizedEmail = "JOHNDOE14@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE14",
                            PasswordHash = "AQAAAAIAAYagAAAAEB6S/HHwZbGyg7l6mOYOGr/qvdCuTM7hONliDxe0Q9TLaWYZj5KPoeNrSVwmS+2Hag==",
                            SecurityStamp = "0d994f91-ad77-47a1-8c76-701080faa459",
                            UserName = "JohnDoe14"
                        },
                        new
                        {
                            Id = "7c2c59f6-0d6f-4d8b-a913-d57ba217ecd3",
                            ConcurrencyStamp = "b9e85fb5-bc25-45a9-9f6a-3a919d17a1f3",
                            Email = "johndoe15@personal.gmail",
                            NormalizedEmail = "JOHNDOE15@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE15",
                            PasswordHash = "AQAAAAIAAYagAAAAEIPzT2jxesXtU+A1WlmwnZUr8Qa3qhxOYvzGKZNyHPWiu8fY9S/Uuf+Up+n3mUB7dA==",
                            SecurityStamp = "80244bd6-18c4-4ceb-a68e-4d460023a2b9",
                            UserName = "JohnDoe15"
                        },
                        new
                        {
                            Id = "811863c7-ba6c-49b3-91b4-357d29a9f559",
                            ConcurrencyStamp = "f2e185c4-e0ca-4b91-b068-94c43e61fa53",
                            Email = "johndoe16@personal.gmail",
                            NormalizedEmail = "JOHNDOE16@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE16",
                            PasswordHash = "AQAAAAIAAYagAAAAEFrsL45h5bVBw5QMqg/mWHsMT01apVkQP3s/fqpii9WN0x0R8zeGAt61VgIUB+Eqvg==",
                            SecurityStamp = "e8ff4a8f-ffd7-42f6-85e0-669943f4b2f0",
                            UserName = "JohnDoe16"
                        },
                        new
                        {
                            Id = "10ebc514-f8d2-44cb-aa74-9bf59e51d23d",
                            ConcurrencyStamp = "cf2b9e4a-abd6-4644-8564-c941d6d6652f",
                            Email = "johndoe17@personal.gmail",
                            NormalizedEmail = "JOHNDOE17@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE17",
                            PasswordHash = "AQAAAAIAAYagAAAAECt50dhnXk2EVK7JBqW9t+DJepNcD2Cs2i4YcQJXmGZSDRjFMCkfQHtS/QrJO0X/2g==",
                            SecurityStamp = "3d4c7f85-f504-4d49-8497-d38212ce0752",
                            UserName = "JohnDoe17"
                        },
                        new
                        {
                            Id = "1918af0e-eb9b-42b4-b4f0-668ac161a7e4",
                            ConcurrencyStamp = "57837603-45ea-4b70-a0a6-4b42c336ac7a",
                            Email = "johndoe18@personal.gmail",
                            NormalizedEmail = "JOHNDOE18@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE18",
                            PasswordHash = "AQAAAAIAAYagAAAAEBzvD6CqKsF03HSGPlhmxbpICGZ6j5URJ3oBb1DZmEpsI0GYp0/AD4alh2Yqg/nqRQ==",
                            SecurityStamp = "7e55b3e5-613a-4c69-ae2f-fa146d39e81d",
                            UserName = "JohnDoe18"
                        },
                        new
                        {
                            Id = "d4d9beae-bd9a-4e69-ba80-0f6df463048f",
                            ConcurrencyStamp = "e6d996ad-0122-405d-ac27-f8241c8e84e8",
                            Email = "johndoe19@personal.gmail",
                            NormalizedEmail = "JOHNDOE19@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE19",
                            PasswordHash = "AQAAAAIAAYagAAAAEKmvcFRsFmL/E5hf4NfbFn3S9gQbzZgG7jDK9wZIFW7yHX+q0EDlVOxelgFoJEv6jw==",
                            SecurityStamp = "eb99b75a-1069-404a-abc1-b8a44afdea87",
                            UserName = "JohnDoe19"
                        },
                        new
                        {
                            Id = "4049d633-303e-43df-be36-9ed75daf55a0",
                            ConcurrencyStamp = "9283a0d3-3cb1-4b74-99eb-1fd051885f51",
                            Email = "johndoe20@personal.gmail",
                            NormalizedEmail = "JOHNDOE20@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE20",
                            PasswordHash = "AQAAAAIAAYagAAAAEFBUrejX4p3LAwnm6Z3bDWgbCEtByYr9/qm93eyKDrsWta+wIkuvb/DdKl+B8BUu8g==",
                            SecurityStamp = "8cc68dc2-d96b-4890-a3f2-87d95ca2d679",
                            UserName = "JohnDoe20"
                        },
                        new
                        {
                            Id = "003fbf32-bc9f-47e3-95cc-69f026437353",
                            ConcurrencyStamp = "5a145b81-2d01-48c4-ac3a-950f0a234e7a",
                            Email = "johndoe21@personal.gmail",
                            NormalizedEmail = "JOHNDOE21@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE21",
                            PasswordHash = "AQAAAAIAAYagAAAAEED+aRHxcXJc8d4vbmhIREuA5dTz7O6TXs/O4rwcQiW1saPteKvB0d+euJGskq4F9Q==",
                            SecurityStamp = "57e86ac1-82de-4c01-93ca-693553ac3d76",
                            UserName = "JohnDoe21"
                        },
                        new
                        {
                            Id = "5da6430c-eac0-433d-a4c2-427fa40a937e",
                            ConcurrencyStamp = "f3df1ee4-352c-4176-b406-3456a615acd4",
                            Email = "johndoe22@personal.gmail",
                            NormalizedEmail = "JOHNDOE22@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE22",
                            PasswordHash = "AQAAAAIAAYagAAAAEMB3gDADywhEVyujCQiZH6xEuHMpM8/DVL2uhC71RXX8qZsxsFBJ4xd0IdsoIlYUSg==",
                            SecurityStamp = "de21e002-0d39-40da-a3a3-82c4c35b38fb",
                            UserName = "JohnDoe22"
                        },
                        new
                        {
                            Id = "cabb8b7e-9ca8-4673-9da1-e0a5d25aebe3",
                            ConcurrencyStamp = "56137324-c014-4eaa-a74d-89e5ce1b41da",
                            Email = "johndoe23@personal.gmail",
                            NormalizedEmail = "JOHNDOE23@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE23",
                            PasswordHash = "AQAAAAIAAYagAAAAEGAJkskxH8pbxVZHdz//2x+xCNn3CHYZd8v5JppCrN7aT+LcdH9bzj67WrqdrdJnZQ==",
                            SecurityStamp = "b4392a7b-15c5-4f4a-86f9-d03f5f7f5499",
                            UserName = "JohnDoe23"
                        },
                        new
                        {
                            Id = "4fa52168-45f9-405c-aee5-a198c6d7b29e",
                            ConcurrencyStamp = "4eacb302-55c4-4055-b3b3-ed85d4334d33",
                            Email = "johndoe24@personal.gmail",
                            NormalizedEmail = "JOHNDOE24@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE24",
                            PasswordHash = "AQAAAAIAAYagAAAAEOrJe9WFJYVJEZGR/EZASn+MtYi25QSbVhkR9X8SiCTOm82cxNoP3Em8j8x2Rbn8Zw==",
                            SecurityStamp = "f2b6d412-8571-46e8-8e8e-36c1ef1b8bd6",
                            UserName = "JohnDoe24"
                        },
                        new
                        {
                            Id = "c0d00f17-d7d8-4f79-98fb-80f8db38a1fe",
                            ConcurrencyStamp = "1b1a65e2-7ee1-495b-982b-70dcdd833770",
                            Email = "johndoe25@personal.gmail",
                            NormalizedEmail = "JOHNDOE25@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE25",
                            PasswordHash = "AQAAAAIAAYagAAAAEBAKBNCkXtueG7kaTkt17kCG19k27Nm6KR7DuC8di2PL0EAwiBj/Z7Bgl+B1aYg7Cg==",
                            SecurityStamp = "141102d4-c930-4c57-be16-ba54e81d4deb",
                            UserName = "JohnDoe25"
                        },
                        new
                        {
                            Id = "fdacb9cb-2d8b-496a-bc6c-122aacd910d7",
                            ConcurrencyStamp = "c8175451-7e86-46e9-8cea-14241d032813",
                            Email = "johndoe26@personal.gmail",
                            NormalizedEmail = "JOHNDOE26@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE26",
                            PasswordHash = "AQAAAAIAAYagAAAAEAwIyfFJfEBv/3Jvzlj7n1SsfNuu+Kq6xNok1XG9lO5jImaaZC6wB85Usj8L9tYokg==",
                            SecurityStamp = "86ba2fb5-e5ed-4fd3-8683-dd42dba38a4a",
                            UserName = "JohnDoe26"
                        },
                        new
                        {
                            Id = "9e6b0919-fd9c-4a2c-ac57-8035d1c4b22d",
                            ConcurrencyStamp = "ec1d95a8-7f59-40bc-b7b9-772895767e4f",
                            Email = "johndoe27@personal.gmail",
                            NormalizedEmail = "JOHNDOE27@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE27",
                            PasswordHash = "AQAAAAIAAYagAAAAELqY7g6COVB/YbSqYmUKQ1ZS+sLo6NCJbhE4FjgDrGmKFTWc6HfFgH5vfVrjz6iMFQ==",
                            SecurityStamp = "35f5b111-ca2f-455d-ba41-637a9a7bdf22",
                            UserName = "JohnDoe27"
                        },
                        new
                        {
                            Id = "db7aa3da-3c17-4f6c-94bc-898c08b14009",
                            ConcurrencyStamp = "591e4c80-5171-4755-aecb-f4dcfc062221",
                            Email = "johndoe28@personal.gmail",
                            NormalizedEmail = "JOHNDOE28@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE28",
                            PasswordHash = "AQAAAAIAAYagAAAAEIiMUhm0mCAEptK1ZJA8W4p1wtrMnaC4wZsjffQDtuvF8Mt6YpAMiZ5B0PAw0VqO6w==",
                            SecurityStamp = "affa6f48-057d-48b7-a63d-7ba7690b81ae",
                            UserName = "JohnDoe28"
                        },
                        new
                        {
                            Id = "9df12ac9-105f-4f8e-bd62-f09295e227f3",
                            ConcurrencyStamp = "9fa28b8d-1bb3-409a-8135-9313336e5c3f",
                            Email = "johndoe29@personal.gmail",
                            NormalizedEmail = "JOHNDOE29@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE29",
                            PasswordHash = "AQAAAAIAAYagAAAAEJfD4RPWqBej/LQdTISfqIYMP3eiCHhmGUyLCtGPH4mATmbFaTvzvyxa5xeaVQyBTg==",
                            SecurityStamp = "18e77fd5-ec9f-418a-9986-48b21d84a658",
                            UserName = "JohnDoe29"
                        },
                        new
                        {
                            Id = "ce98b90c-6807-42a1-901f-9b5a37ae9b0f",
                            ConcurrencyStamp = "3358a880-1f1d-4ce7-8577-2cc57406e1e1",
                            Email = "johndoe30@personal.gmail",
                            NormalizedEmail = "JOHNDOE30@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE30",
                            PasswordHash = "AQAAAAIAAYagAAAAEKFhup7xO4gnkceqvbSPCaIujuk+UY272hpWpTs6X7Zz8FMqhAzBMetR1aahYNW19g==",
                            SecurityStamp = "fc3de848-9da8-40e2-bbe8-261a6f9de9ca",
                            UserName = "JohnDoe30"
                        },
                        new
                        {
                            Id = "a25c0148-7e24-4f5f-bbb1-d68b08f81775",
                            ConcurrencyStamp = "c08c31a7-8bbf-48f9-947a-99e9b9c008fc",
                            Email = "johndoe31@personal.gmail",
                            NormalizedEmail = "JOHNDOE31@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE31",
                            PasswordHash = "AQAAAAIAAYagAAAAEJeK7bXABfXqnscwgvd5g2jMB0zAuDTrkmMqA4mtg9ZX39BGLG++WyuRHDEU2epJnw==",
                            SecurityStamp = "19b45a39-7be7-411f-99f6-fb0c7ba4fbf2",
                            UserName = "JohnDoe31"
                        },
                        new
                        {
                            Id = "454f813d-08d9-48eb-8f4f-db046fb742f8",
                            ConcurrencyStamp = "4e07c1ed-500a-4887-a6b2-123e3bec8aa2",
                            Email = "johndoe32@personal.gmail",
                            NormalizedEmail = "JOHNDOE32@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE32",
                            PasswordHash = "AQAAAAIAAYagAAAAEAGlECe22CmC21O0ZzNnU1uIkL8Wru0yoKlhy4mVBr+EaNGKzw8jlrStuuTu1QKncQ==",
                            SecurityStamp = "11e29a74-20c0-4469-a54b-1633a73b63ed",
                            UserName = "JohnDoe32"
                        },
                        new
                        {
                            Id = "af1f1382-3d0a-404e-a479-44941fbcdb67",
                            ConcurrencyStamp = "1830cb28-d1dd-4504-a2bb-cd47a01209bc",
                            Email = "johndoe33@personal.gmail",
                            NormalizedEmail = "JOHNDOE33@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE33",
                            PasswordHash = "AQAAAAIAAYagAAAAEH8PSrMYch0gqAjlNCd/jTWObAAh1rh7xm/NnnBylmKZ48iSbEiTd1JGODVa+tR9DQ==",
                            SecurityStamp = "d6baa66b-1f10-4df7-8889-8f33b1739302",
                            UserName = "JohnDoe33"
                        },
                        new
                        {
                            Id = "d8c8aabe-e15d-464d-9ce5-23fd418a330a",
                            ConcurrencyStamp = "c63ae02d-fa22-43c2-a7eb-337aac99d540",
                            Email = "johndoe34@personal.gmail",
                            NormalizedEmail = "JOHNDOE34@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE34",
                            PasswordHash = "AQAAAAIAAYagAAAAEDNLUyhFUL5Gofilge17gpiH1tHLSyZattiaCSzOJsMw9R8Fe4KFyn2R2eofARkVvw==",
                            SecurityStamp = "8f884a79-25e4-4676-a901-97e736e717c9",
                            UserName = "JohnDoe34"
                        },
                        new
                        {
                            Id = "8534c31b-00ba-4308-82b8-b8aebd523c03",
                            ConcurrencyStamp = "90ff8b38-425c-4850-9618-e3b4b4d0db6f",
                            Email = "johndoe35@personal.gmail",
                            NormalizedEmail = "JOHNDOE35@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE35",
                            PasswordHash = "AQAAAAIAAYagAAAAEGawPX7y1bV1JjUQOQlHu7Tm228zFRDm1dVDcrXa3jldHJ2AhIiyDWC1oP3MfKNVeQ==",
                            SecurityStamp = "f4ac85b9-ab68-4875-9dcc-84c4d9a5f61f",
                            UserName = "JohnDoe35"
                        },
                        new
                        {
                            Id = "375e73d8-865d-45bd-bf29-4a3c769107fc",
                            ConcurrencyStamp = "b492c363-d27a-42ce-b36f-e7808d5a3587",
                            Email = "johndoe36@personal.gmail",
                            NormalizedEmail = "JOHNDOE36@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE36",
                            PasswordHash = "AQAAAAIAAYagAAAAEDsm2+2dCN8HzdLgURicj1gMBtslht47nxXm2OPckOdi69bg3ONoyPIIrDDKhYYnrA==",
                            SecurityStamp = "fe91c580-616f-4c46-adc6-68014adee63a",
                            UserName = "JohnDoe36"
                        },
                        new
                        {
                            Id = "600dc378-22f7-4cee-8c1c-56a0411c1560",
                            ConcurrencyStamp = "bd0ea42f-2b6d-43dd-bb8a-f4eea6f4ef32",
                            Email = "johndoe37@personal.gmail",
                            NormalizedEmail = "JOHNDOE37@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE37",
                            PasswordHash = "AQAAAAIAAYagAAAAEKJm7gOWBAmwmdR3zEmaBli8xlJEXb+cnI+oUJkDjwZo2unmod+R2vsDrrpfOovLUA==",
                            SecurityStamp = "a450443b-bdcc-45d2-bda6-e6b339d9d1b8",
                            UserName = "JohnDoe37"
                        },
                        new
                        {
                            Id = "4f499d5c-4f35-46aa-b921-c1f797dbbcc2",
                            ConcurrencyStamp = "6e62f99f-5cae-43ac-b073-e8f97ccf9090",
                            Email = "johndoe38@personal.gmail",
                            NormalizedEmail = "JOHNDOE38@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE38",
                            PasswordHash = "AQAAAAIAAYagAAAAEOmNLSldteXJ19hXi6jhc6OQEw31xdRU9ZDkWcQR0GP7h4XvsUpJvTilFZ3hfcxVvw==",
                            SecurityStamp = "e61aa120-cb69-4f03-ad56-61b785ab7673",
                            UserName = "JohnDoe38"
                        },
                        new
                        {
                            Id = "a5c15c79-e6e2-4f27-b9c2-a6c7a75a4af5",
                            ConcurrencyStamp = "0bff92b6-eedd-4951-8c05-b7c0223b9eb1",
                            Email = "johndoe39@personal.gmail",
                            NormalizedEmail = "JOHNDOE39@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE39",
                            PasswordHash = "AQAAAAIAAYagAAAAEMTHCQbHHBXd/dcI693z+m2xDWDyXxNkSMvWw7opj98Z4RJJszsyWFzJU5ByLEW1Bw==",
                            SecurityStamp = "5af0f075-0cc4-4631-a107-14e86bafd2a7",
                            UserName = "JohnDoe39"
                        },
                        new
                        {
                            Id = "8f56f664-b90d-4881-b228-6d48672ea436",
                            ConcurrencyStamp = "f2145f01-2089-4f2a-b435-b8bf078b9af0",
                            Email = "johndoe40@personal.gmail",
                            NormalizedEmail = "JOHNDOE40@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE40",
                            PasswordHash = "AQAAAAIAAYagAAAAEMzdpicgw63ZOuLks/IYqlUlQG/cZ4y9VdGh497nLU5LDtBEm6rIoMNKYCpBp/ovBA==",
                            SecurityStamp = "852665ec-6a66-497f-87cd-c3f2aeb56a5c",
                            UserName = "JohnDoe40"
                        },
                        new
                        {
                            Id = "7a855d4d-897f-4f23-b2e5-a0c1d4000b50",
                            ConcurrencyStamp = "020bd9fe-dbd8-4055-a5da-89a1c16b020d",
                            Email = "johndoe41@personal.gmail",
                            NormalizedEmail = "JOHNDOE41@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE41",
                            PasswordHash = "AQAAAAIAAYagAAAAEDjMMOZvIVko/WG+WfUjo7QJEeA2EkgTRWQUazPxp22ILlkbSbMB8Nz5aGd65tmxZw==",
                            SecurityStamp = "4f11d58a-a256-4d73-b2fb-3a9a95b201c3",
                            UserName = "JohnDoe41"
                        },
                        new
                        {
                            Id = "fd01736c-538a-4d84-9c2e-6f9479493fa1",
                            ConcurrencyStamp = "e7a5c25b-f212-4c87-88f9-774aed1201fb",
                            Email = "johndoe42@personal.gmail",
                            NormalizedEmail = "JOHNDOE42@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE42",
                            PasswordHash = "AQAAAAIAAYagAAAAEJawIIMt3E5Y6ytBNYELW2p64pIuKiAAs/KCa7cDw90Pvf2JaMoaG8qAKocPFIgS0Q==",
                            SecurityStamp = "33e66a6b-c8e9-49d3-a5ef-5b28739d0374",
                            UserName = "JohnDoe42"
                        },
                        new
                        {
                            Id = "06b45b7c-0ce5-4ae1-b22c-c49048bf1ee0",
                            ConcurrencyStamp = "89c7d39a-2ea3-4ef0-8236-cd0e24817ba2",
                            Email = "johndoe43@personal.gmail",
                            NormalizedEmail = "JOHNDOE43@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE43",
                            PasswordHash = "AQAAAAIAAYagAAAAEFVYwM6dYrSx6HPKYyr7N6GICyLFo/W56QHWhiNQlWqgQP46iRc5aXvfn0WyhOUrAg==",
                            SecurityStamp = "c0d2dc84-ba7a-4a9e-b3bd-9b4ca9ec3269",
                            UserName = "JohnDoe43"
                        },
                        new
                        {
                            Id = "a634b94b-02d6-4480-9ee5-f133e7fb97c4",
                            ConcurrencyStamp = "4e818ff1-4465-4cfa-b312-aac5181cc1c3",
                            Email = "johndoe44@personal.gmail",
                            NormalizedEmail = "JOHNDOE44@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE44",
                            PasswordHash = "AQAAAAIAAYagAAAAEE2xNm4jfiL8wnYxSZmsWRj7e4T0TPilr+Bjp6GNFyeZqa6vUuA7t+ya4tTVO7Wl9w==",
                            SecurityStamp = "8997ac47-f408-411b-90b3-7793b8be9691",
                            UserName = "JohnDoe44"
                        },
                        new
                        {
                            Id = "63583698-0976-493d-86dc-f862c471f36f",
                            ConcurrencyStamp = "bb0cbf39-adae-430d-92e0-672218755650",
                            Email = "johndoe45@personal.gmail",
                            NormalizedEmail = "JOHNDOE45@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE45",
                            PasswordHash = "AQAAAAIAAYagAAAAEAAlVM5tq5RIIM3ikcpopHWH8OOnmyp99RrMsZwCeFxeVInud2Wa44Mkn9U7iifIXw==",
                            SecurityStamp = "b646666e-809c-4140-9816-68d58f878fb2",
                            UserName = "JohnDoe45"
                        },
                        new
                        {
                            Id = "52f3a972-a5d6-41fa-8c5e-f684a0770235",
                            ConcurrencyStamp = "ef87516e-cd63-48d5-ade5-4f8e025652e3",
                            Email = "johndoe46@personal.gmail",
                            NormalizedEmail = "JOHNDOE46@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE46",
                            PasswordHash = "AQAAAAIAAYagAAAAEL70lTmZsX9S8Y2eXPP2iv34Rs2kUs1r390QuC71dpPBDm/lPtbOYMwLAgsWezrq6Q==",
                            SecurityStamp = "37ae45af-a646-4d55-89cc-0181b70d61b8",
                            UserName = "JohnDoe46"
                        },
                        new
                        {
                            Id = "97405820-3645-4509-9519-5dcf956dab91",
                            ConcurrencyStamp = "d23e0ff4-4959-493f-a932-4f983b444615",
                            Email = "johndoe47@personal.gmail",
                            NormalizedEmail = "JOHNDOE47@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE47",
                            PasswordHash = "AQAAAAIAAYagAAAAED+j/wwYZbOZAvgylPAc0N409dI7KZkSglQAyD0uB7AF6HV7ITYRra72RkkOczM10g==",
                            SecurityStamp = "5258002d-c7fd-4993-81c8-b9dd6da19e53",
                            UserName = "JohnDoe47"
                        },
                        new
                        {
                            Id = "e150cea2-ef1d-4f95-aea1-207cc74bd3e5",
                            ConcurrencyStamp = "340d93b4-4588-4080-bcba-d8687a6f9d53",
                            Email = "johndoe48@personal.gmail",
                            NormalizedEmail = "JOHNDOE48@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE48",
                            PasswordHash = "AQAAAAIAAYagAAAAECKrDDAYrIZzysp+qZaHT3joCV5BMUtB/UhuFC3Q/pnGiOYYJnSYOWLERlSQv9CLJA==",
                            SecurityStamp = "06ec2cd1-a2a4-40a4-9528-0a7b4df8a185",
                            UserName = "JohnDoe48"
                        },
                        new
                        {
                            Id = "1390a1b9-ae19-4b47-ab5a-0f5ed9d5bc28",
                            ConcurrencyStamp = "8749ac49-c002-4d89-8e0e-16636bd8f65b",
                            Email = "johndoe49@personal.gmail",
                            NormalizedEmail = "JOHNDOE49@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE49",
                            PasswordHash = "AQAAAAIAAYagAAAAENVAhXAMNFapO3QZkzEbj8PYch5xqCgxLinYWM9x7pyr4c6AjZ1Gz3mzDVRcgocmZg==",
                            SecurityStamp = "b701bdf7-98bc-493d-9665-6c8df1819206",
                            UserName = "JohnDoe49"
                        },
                        new
                        {
                            Id = "aa6823c8-854f-46f9-af6e-9aa3a1674f62",
                            ConcurrencyStamp = "4e25402f-cca4-417b-92f1-036622cb4377",
                            Email = "johndoe50@personal.gmail",
                            NormalizedEmail = "JOHNDOE50@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE50",
                            PasswordHash = "AQAAAAIAAYagAAAAEMo2IytCiUJkPbzyIw1EcwswnAZYn9WzPxWQs60acYI7nq90M2U6UVD2oOmD2WcF+Q==",
                            SecurityStamp = "6da1ccbf-623a-48d6-b253-76ed4a02fbe1",
                            UserName = "JohnDoe50"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CompanyEmail = "johndoe1@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Finance Manager",
                            LastName = "Doe",
                            Salary = 3213.0m,
                            UserId = "c9cc4223-eee3-4826-92fa-b774c4c608a3"
                        },
                        new
                        {
                            Id = 102,
                            CompanyEmail = "johndoe2@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "IT Manager",
                            LastName = "Doe",
                            Salary = 6084.0m,
                            UserId = "1f7b8188-0e7c-4764-a453-7b3dfb396dda"
                        },
                        new
                        {
                            Id = 103,
                            CompanyEmail = "johndoe3@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Manager",
                            LastName = "Doe",
                            Salary = 3159.0m,
                            UserId = "64566c45-5a21-4f9a-a074-7719a36d719e"
                        },
                        new
                        {
                            Id = 104,
                            CompanyEmail = "johndoe4@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Manager",
                            LastName = "Doe",
                            Salary = 3069.0m,
                            UserId = "1e64def5-b5be-45f7-8f75-36c2a84cc4a0"
                        },
                        new
                        {
                            Id = 105,
                            CompanyEmail = "johndoe5@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Manager",
                            LastName = "Doe",
                            Salary = 4179.0m,
                            UserId = "f1df7b6c-af5e-4d0a-9d20-510088708682"
                        },
                        new
                        {
                            Id = 106,
                            CompanyEmail = "johndoe6@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Salary = 2343.0m,
                            UserId = "af4820c9-c023-40e6-ac3c-32915ed3a7e5"
                        },
                        new
                        {
                            Id = 107,
                            CompanyEmail = "johndoe7@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2062m,
                            UserId = "50dd659a-5c61-40bc-bb9b-938bb656251a"
                        },
                        new
                        {
                            Id = 108,
                            CompanyEmail = "johndoe8@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4962m,
                            UserId = "d04f0de8-0c22-4d56-9545-552bbba6c4a9"
                        },
                        new
                        {
                            Id = 109,
                            CompanyEmail = "johndoe9@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2161m,
                            UserId = "03d2df2f-2b82-47f5-a4cb-b902983e27d7"
                        },
                        new
                        {
                            Id = 110,
                            CompanyEmail = "johndoe10@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 3047m,
                            UserId = "08431c71-0402-4723-9eb4-ceaf5f0b691c"
                        },
                        new
                        {
                            Id = 111,
                            CompanyEmail = "johndoe11@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2672m,
                            UserId = "d990afdc-96c1-406f-8b62-d8e0a1c0f676"
                        },
                        new
                        {
                            Id = 112,
                            CompanyEmail = "johndoe12@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1646m,
                            UserId = "c3d80974-4f53-436d-b258-562cccbb5911"
                        },
                        new
                        {
                            Id = 113,
                            CompanyEmail = "johndoe13@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2023m,
                            UserId = "75ee5357-ff22-4147-9969-c292aa655614"
                        },
                        new
                        {
                            Id = 114,
                            CompanyEmail = "johndoe14@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4832m,
                            UserId = "2cc909ea-29bb-4eeb-84fc-90cd4abbdc5d"
                        },
                        new
                        {
                            Id = 115,
                            CompanyEmail = "johndoe15@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2037m,
                            UserId = "7c2c59f6-0d6f-4d8b-a913-d57ba217ecd3"
                        },
                        new
                        {
                            Id = 116,
                            CompanyEmail = "johndoe16@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 2659m,
                            UserId = "811863c7-ba6c-49b3-91b4-357d29a9f559"
                        },
                        new
                        {
                            Id = 117,
                            CompanyEmail = "johndoe17@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2978m,
                            UserId = "10ebc514-f8d2-44cb-aa74-9bf59e51d23d"
                        },
                        new
                        {
                            Id = 118,
                            CompanyEmail = "johndoe18@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1570m,
                            UserId = "1918af0e-eb9b-42b4-b4f0-668ac161a7e4"
                        },
                        new
                        {
                            Id = 119,
                            CompanyEmail = "johndoe19@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2010m,
                            UserId = "d4d9beae-bd9a-4e69-ba80-0f6df463048f"
                        },
                        new
                        {
                            Id = 120,
                            CompanyEmail = "johndoe20@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4582m,
                            UserId = "4049d633-303e-43df-be36-9ed75daf55a0"
                        },
                        new
                        {
                            Id = 121,
                            CompanyEmail = "johndoe21@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2113m,
                            UserId = "003fbf32-bc9f-47e3-95cc-69f026437353"
                        },
                        new
                        {
                            Id = 122,
                            CompanyEmail = "johndoe22@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 2043m,
                            UserId = "5da6430c-eac0-433d-a4c2-427fa40a937e"
                        },
                        new
                        {
                            Id = 123,
                            CompanyEmail = "johndoe23@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2686m,
                            UserId = "cabb8b7e-9ca8-4673-9da1-e0a5d25aebe3"
                        },
                        new
                        {
                            Id = 124,
                            CompanyEmail = "johndoe24@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1548m,
                            UserId = "4fa52168-45f9-405c-aee5-a198c6d7b29e"
                        },
                        new
                        {
                            Id = 125,
                            CompanyEmail = "johndoe25@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2043m,
                            UserId = "c0d00f17-d7d8-4f79-98fb-80f8db38a1fe"
                        },
                        new
                        {
                            Id = 126,
                            CompanyEmail = "johndoe26@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4174m,
                            UserId = "fdacb9cb-2d8b-496a-bc6c-122aacd910d7"
                        },
                        new
                        {
                            Id = 127,
                            CompanyEmail = "johndoe27@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2153m,
                            UserId = "9e6b0919-fd9c-4a2c-ac57-8035d1c4b22d"
                        },
                        new
                        {
                            Id = 128,
                            CompanyEmail = "johndoe28@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 3344m,
                            UserId = "db7aa3da-3c17-4f6c-94bc-898c08b14009"
                        },
                        new
                        {
                            Id = 129,
                            CompanyEmail = "johndoe29@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2880m,
                            UserId = "9df12ac9-105f-4f8e-bd62-f09295e227f3"
                        },
                        new
                        {
                            Id = 130,
                            CompanyEmail = "johndoe30@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1548m,
                            UserId = "ce98b90c-6807-42a1-901f-9b5a37ae9b0f"
                        },
                        new
                        {
                            Id = 131,
                            CompanyEmail = "johndoe31@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2124m,
                            UserId = "a25c0148-7e24-4f5f-bbb1-d68b08f81775"
                        },
                        new
                        {
                            Id = 132,
                            CompanyEmail = "johndoe32@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4010m,
                            UserId = "454f813d-08d9-48eb-8f4f-db046fb742f8"
                        },
                        new
                        {
                            Id = 133,
                            CompanyEmail = "johndoe33@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2170m,
                            UserId = "af1f1382-3d0a-404e-a479-44941fbcdb67"
                        },
                        new
                        {
                            Id = 134,
                            CompanyEmail = "johndoe34@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 4800m,
                            UserId = "d8c8aabe-e15d-464d-9ce5-23fd418a330a"
                        },
                        new
                        {
                            Id = 135,
                            CompanyEmail = "johndoe35@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2643m,
                            UserId = "8534c31b-00ba-4308-82b8-b8aebd523c03"
                        },
                        new
                        {
                            Id = 136,
                            CompanyEmail = "johndoe36@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1693m,
                            UserId = "375e73d8-865d-45bd-bf29-4a3c769107fc"
                        },
                        new
                        {
                            Id = 137,
                            CompanyEmail = "johndoe37@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2046m,
                            UserId = "600dc378-22f7-4cee-8c1c-56a0411c1560"
                        },
                        new
                        {
                            Id = 138,
                            CompanyEmail = "johndoe38@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4185m,
                            UserId = "4f499d5c-4f35-46aa-b921-c1f797dbbcc2"
                        },
                        new
                        {
                            Id = 139,
                            CompanyEmail = "johndoe39@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2044m,
                            UserId = "a5c15c79-e6e2-4f27-b9c2-a6c7a75a4af5"
                        },
                        new
                        {
                            Id = 140,
                            CompanyEmail = "johndoe40@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 4318m,
                            UserId = "8f56f664-b90d-4881-b228-6d48672ea436"
                        },
                        new
                        {
                            Id = 141,
                            CompanyEmail = "johndoe41@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2982m,
                            UserId = "7a855d4d-897f-4f23-b2e5-a0c1d4000b50"
                        },
                        new
                        {
                            Id = 142,
                            CompanyEmail = "johndoe42@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1724m,
                            UserId = "fd01736c-538a-4d84-9c2e-6f9479493fa1"
                        },
                        new
                        {
                            Id = 143,
                            CompanyEmail = "johndoe43@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2167m,
                            UserId = "06b45b7c-0ce5-4ae1-b22c-c49048bf1ee0"
                        },
                        new
                        {
                            Id = 144,
                            CompanyEmail = "johndoe44@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4646m,
                            UserId = "a634b94b-02d6-4480-9ee5-f133e7fb97c4"
                        },
                        new
                        {
                            Id = 145,
                            CompanyEmail = "johndoe45@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2173m,
                            UserId = "63583698-0976-493d-86dc-f862c471f36f"
                        },
                        new
                        {
                            Id = 146,
                            CompanyEmail = "johndoe46@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 3173m,
                            UserId = "52f3a972-a5d6-41fa-8c5e-f684a0770235"
                        },
                        new
                        {
                            Id = 147,
                            CompanyEmail = "johndoe47@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2829m,
                            UserId = "97405820-3645-4509-9519-5dcf956dab91"
                        },
                        new
                        {
                            Id = 148,
                            CompanyEmail = "johndoe48@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1537m,
                            UserId = "e150cea2-ef1d-4f95-aea1-207cc74bd3e5"
                        },
                        new
                        {
                            Id = 149,
                            CompanyEmail = "johndoe49@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2153m,
                            UserId = "1390a1b9-ae19-4b47-ab5a-0f5ed9d5bc28"
                        },
                        new
                        {
                            Id = 150,
                            CompanyEmail = "johndoe50@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4415m,
                            UserId = "aa6823c8-854f-46f9-af6e-9aa3a1674f62"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "74f1f99a-0e65-446b-b47f-bcf84d854b1d",
                            Name = "HR Admin",
                            NormalizedName = "HR ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "b55e7f94-56e4-4355-b09d-591d6b80d91b",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "65198b62-10b9-4760-a95c-6836821e1a18",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c9cc4223-eee3-4826-92fa-b774c4c608a3",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "1f7b8188-0e7c-4764-a453-7b3dfb396dda",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "64566c45-5a21-4f9a-a074-7719a36d719e",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "1e64def5-b5be-45f7-8f75-36c2a84cc4a0",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "f1df7b6c-af5e-4d0a-9d20-510088708682",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "af4820c9-c023-40e6-ac3c-32915ed3a7e5",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "50dd659a-5c61-40bc-bb9b-938bb656251a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d04f0de8-0c22-4d56-9545-552bbba6c4a9",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "03d2df2f-2b82-47f5-a4cb-b902983e27d7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "08431c71-0402-4723-9eb4-ceaf5f0b691c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d990afdc-96c1-406f-8b62-d8e0a1c0f676",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "c3d80974-4f53-436d-b258-562cccbb5911",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "75ee5357-ff22-4147-9969-c292aa655614",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2cc909ea-29bb-4eeb-84fc-90cd4abbdc5d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7c2c59f6-0d6f-4d8b-a913-d57ba217ecd3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "811863c7-ba6c-49b3-91b4-357d29a9f559",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "10ebc514-f8d2-44cb-aa74-9bf59e51d23d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "1918af0e-eb9b-42b4-b4f0-668ac161a7e4",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "d4d9beae-bd9a-4e69-ba80-0f6df463048f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4049d633-303e-43df-be36-9ed75daf55a0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "003fbf32-bc9f-47e3-95cc-69f026437353",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5da6430c-eac0-433d-a4c2-427fa40a937e",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "cabb8b7e-9ca8-4673-9da1-e0a5d25aebe3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4fa52168-45f9-405c-aee5-a198c6d7b29e",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "c0d00f17-d7d8-4f79-98fb-80f8db38a1fe",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "fdacb9cb-2d8b-496a-bc6c-122aacd910d7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9e6b0919-fd9c-4a2c-ac57-8035d1c4b22d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "db7aa3da-3c17-4f6c-94bc-898c08b14009",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9df12ac9-105f-4f8e-bd62-f09295e227f3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ce98b90c-6807-42a1-901f-9b5a37ae9b0f",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "a25c0148-7e24-4f5f-bbb1-d68b08f81775",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "454f813d-08d9-48eb-8f4f-db046fb742f8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "af1f1382-3d0a-404e-a479-44941fbcdb67",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d8c8aabe-e15d-464d-9ce5-23fd418a330a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8534c31b-00ba-4308-82b8-b8aebd523c03",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "375e73d8-865d-45bd-bf29-4a3c769107fc",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "600dc378-22f7-4cee-8c1c-56a0411c1560",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4f499d5c-4f35-46aa-b921-c1f797dbbcc2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a5c15c79-e6e2-4f27-b9c2-a6c7a75a4af5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8f56f664-b90d-4881-b228-6d48672ea436",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7a855d4d-897f-4f23-b2e5-a0c1d4000b50",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "fd01736c-538a-4d84-9c2e-6f9479493fa1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "06b45b7c-0ce5-4ae1-b22c-c49048bf1ee0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a634b94b-02d6-4480-9ee5-f133e7fb97c4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "63583698-0976-493d-86dc-f862c471f36f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "52f3a972-a5d6-41fa-8c5e-f684a0770235",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "97405820-3645-4509-9519-5dcf956dab91",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e150cea2-ef1d-4f95-aea1-207cc74bd3e5",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "1390a1b9-ae19-4b47-ab5a-0f5ed9d5bc28",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "aa6823c8-854f-46f9-af6e-9aa3a1674f62",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HumanCapitalManagement.Data.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
